### ISSUE TITLE
Issue with RelativeLayout with ScrollView and 'footer' 

### ISSUE THREAD

**Issue by aegis1980** [umano/AndroidSlidingUpPanel#112]
Hi, 
I have the following layout configuration:

SlidingUpPanelLayout
---><b>TOP PANEL</b> RelativeLayout (i.e. my top panel')
---><b>SLIDING PANEL</b> LinearLayout (i.e. start of my sliding panel)
-------><b>HEADER</b> RelativeLayout (shown in collapsed state as header)
------->RelativeLayout
----------><b>SCROLLVIEW</b> ScrollView (with <i>android:layout_above</i> FOOTER)
-------------->RelativeLayout (content for scroller)
----------><b>FOOTER</b>: LinearLayout (with <i>layout_alignParentBottom</i> )

With the intention of achieving this layout:
![untitled drawing](https://f.cloud.github.com/assets/4284988/2156259/63b63ef0-9456-11e3-9483-57ad3a6e39d7.png)
My issue is in the anchored state: the footer does not show and the ScrollView does not scroll properly - the ScrollView seems to 'register' touch and drag but does not move more than a few millimetres. Note, I have set my dragview as my header in anchored mode.

In expanded state things work as one might expect.

Is this an issue that others have had? Has anyone managed to solve it?

**Comment by saberking** [comment]
how to implement this in react-native?
