### ISSUE TITLE
Sliding up panel crashes with Navigation Drawer

### ISSUE THREAD

**Issue by AkshayChordiya** [umano/AndroidSlidingUpPanel#113]
Hi, 

First of all, Thanks for providing this awesome library. I wanna use this library with the new Navigation Drawer.
I tried implementing but the app crashes.

I hope someone can help me solve this problem.

**Comment by pmahsky** [comment]
Inside my code, panel is not getting collapsed when calling slidingPanelLayout.setPanelState(PanelState.COLLAPSED);

Scenario is like this : I have a button in sliding panel when its expanded, clicking on that activity.recreate() is called. I need to collapse sliding panel after that. But its not working. Even if I call the method for collapsing the panel, it appears expanded. Also I've put a check in onCreate() if its collapsed, but getting Collapsed state but its expanded actually. An anchorPoint is also set as 0.5 in my panel.

**Comment by gautamverma** [comment]
I am using it DrawerLayout but the Sliding Panel is not getting dragged. Tried moving it move the fragment but it also didn't help.

Layout File

<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    
    <com.sothree.slidinguppanel.SlidingUpPanelLayout
        xmlns:sothree="http://schemas.android.com/apk/res-auto"
        android:id="@+id/sliding_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="bottom">

        <FrameLayout
            android:id="@+id/base_content_frame"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />

        <LinearLayout
            android:id="@+id/base_drawer"
            android:orientation="horizontal"
            android:paddingTop="8dp"
            android:background="@color/Blue_700"
            android:layout_height="68dp"
            android:layout_width="match_parent">

            <LinearLayout
                android:orientation="vertical"
                android:layout_width="0dp"
                android:layout_weight="6"
                android:layout_height="wrap_content">

                <TextView
                    android:id="@+id/track_title"
                    android:maxLines="1"
                    android:ellipsize="marquee"
                    android:gravity="center"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:textColor="@color/black_text_color"
                    android:textSize="@dimen/text_content_size"/>

                <TextView
                    android:id="@+id/track_desc"
                    android:maxLines="1"
                    android:ellipsize="marquee"
                    android:gravity="center"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:textColor="@color/black_text_color"
                    android:textSize="@dimen/text_subtext_size"/>
            </LinearLayout>

            <ImageView
                android:id="@+id/playPauseButton"
                android:src="@drawable/play_light"
                android:layout_width="0dp"
                android:layout_weight="2"
                android:layout_height="48dp"/>
        </LinearLayout>

    </com.sothree.slidinguppanel.SlidingUpPanelLayout>

    <RelativeLayout
        android:id="@+id/base_left_drawer"
        android:layout_width="280dp"
        android:layout_height="match_parent"
        android:layout_gravity="start" />


</android.support.v4.widget.DrawerLayout>

The method onInterceptTouchEvent of SlidingUpPanelLayout always return false. Even pull the source from https://github.com/ribot/AndroidSlidingUpPanel who applied a fix but still the Sliding Panel remain fixed on bottom.

Any ideas??

**Comment by gautamverma** [comment]
It was my bad, got it working.

**Comment by icangku** [comment]
sliding up panel above navigation drawer how to make it under navigation drawer
![error](https://user-images.githubusercontent.com/14269158/44563022-82665180-a786-11e8-8bbd-21c5e6699df6.jpeg)
