### ISSUE TITLE
Vertically Scrollable SlidingUpPanel (like ScrollView)  - feature request/how to

### ISSUE THREAD

**Issue by electricsunny** [umano/AndroidSlidingUpPanel#116]
Hi,

Firstly, thanks to all contributors for an awesome library, very much appreciated.

I have the need to make the content in the Sliding Up Panel vertically scrollable, that is, when there is too much content to fit in the maximum height of the panel, it is scrollable, just like ScrollView.  I have experimented with ScrollView, but am having no joy, I presume that it is not that easy.

Is anyone able to advise, or provide guidance, or an example as to how to implement this feature?  It is becoming more and more common e.g. Etsy app...

many thanks

**Comment by jonneymendoza** [comment]
What was the proper fix for this? sounds like there are different sorts of ways to do it? some not so efficent etc?

**Comment by tokudu** [comment]
I'm gonna try to add proper support for scrollable views in the next release of the library 3.1.0

**Comment by elikohen** [comment]
Hello! I already used a fork from your library that does exactly that: https://github.com/arbuzz/AndroidSlidingUpPanel-ScrollView 
I was getting back to your repo to see if you already added it too, maybe you can take a look on it. If you already know about that fork, you can just delete this message :D

Thanks for the great job btw!

**Comment by jjhesk** [comment]
@elikohen what is lines and options did u add? any attr declarations?

**Comment by elikohen** [comment]
@jjhesk that is not my repo, I just found it one year ago when I was building an android app that required that. What worked for me (as a client) is that it adds a method called **setScrollableView** that 'fixes' the problem with scrollviews. 
Anyway that fork is based on this other fork:
https://github.com/dlukashev/AndroidSlidingUpPanel

And here you can see *dlukashev* blog post about the fix:
http://android.amberfog.com/?p=915

I hope that helps!

**Comment by qbait** [comment]
@tokudu when can we expect version 3.1.0 with ScrollView support?

**Comment by KingWu** [comment]
Can support it now?

**Comment by tokudu** [comment]
Work in progress in https://github.com/umano/AndroidSlidingUpPanel/tree/3.1

**Comment by KingWu** [comment]
Awesome. Will update for Gradle?

**Comment by tokudu** [comment]
Fixed in master. Provide umanoScrollableView attribute to indicate your scrollable child. Gradle will be updated soon
