### ISSUE TITLE
Hard anchor point by percentage

### ISSUE THREAD

**Issue by sreejithraman** [umano/AndroidSlidingUpPanel#125]
Unless I am missing something, currently the only way to set a hard anchor is by specifying dp. I think there should be a way to specify the anchor point point by percentage. Currently if I specify by dp, it will work fine in portrait mode, but if I rotate the phone the drawer will shoot past the screen height.

So, for example, if I want to only have to drawer come up 75% of the way, I can call some method and have the drawer stop at 75% of the screen height. This way even if the screen is rotated, the drawer will stop at 75% of the new screen height.

**Comment by tokudu** [comment]
Fixed in master. Use `layout_weight` attribute on the sliding view.
