### ISSUE TITLE
Feature Request: Blur behind panel

### ISSUE THREAD

**Issue by stiggybr0** [umano/AndroidSlidingUpPanel#129]
Is there a way to blur the content behind the panel as you slide the panel up (leaving the panel content unblurred)?

I've got the panel transparent, but haven't been able to create thee blur effect.

**Comment by redstonedev** [comment]
There is a way to do this, currently I'm implementing a BlurringView.java class found here: https://github.com/500px/500px-android-blur
The problem is, it only blurs sibling views that are beneath it, not everything beneath it.

-R

**Comment by tokudu** [comment]
Use https://github.com/Manabu-GT/GlassView over the main content and modify the blur on slide change.

**Comment by li-xiaojun** [comment]
or use this one:https://github.com/PomepuyN/BlurEffectForAndroidDesign
