### ISSUE TITLE
AndroidSlidingUpPanel overlapping brother view

### ISSUE THREAD

**Issue by cesards** [umano/AndroidSlidingUpPanel#149]
I'm having a problem using AndroidSlidingUpPanel

I'm using a ViewPager of images in my Activity. I need whole screen visibility for images, so I need to avoid ViewPager as main content child of SlidingUpPanelLayout. It should be a brother of it inside a same FrameLayout or RelativeLayout.

I'm having an issue with this, because I can't detect touch events on the ViewPager. SlidingUpPanel is getting all events. Is there any way to avoid this?:

Here a little schema of the layout:

```
 <FrameLayout
      android:id="@+id/main_content"
      android:layout_width="match_parent"
      android:layout_height="match_parent">

      <ui.widget.ZoomedHorizontalViewPager
          android:id="@+id/details_pager"
          android:layout_width="match_parent"
          android:layout_height="match_parent"/>

      <ui.widget.SlidingUpPanelLayout
          android:id="@+id/sliding_layout"
          android:background="@null"
          android:focusable="false"
          android:layout_width="match_parent"
          android:layout_height="match_parent"
          android:layout_marginTop="?android:attr/actionBarSize"
          android:gravity="bottom"
          app:collapsedHeight="?android:attr/actionBarSize"
          app:dragView="@+id/details_more_info">

          <FrameLayout
              android:layout_width="match_parent"
              android:layout_height="0dp"/>

          <LinearLayout
              android:id="@+id/dcollapse_and_draggable_view"
              ...
            android:orientation="vertical">

    </ui.widget.SlidingUpPanelLayout>
</FrameLayout>
```

**Comment by cryadhu** [comment]
I know its too late, buy if anyone encounter the same issue, add the following to the layout <com.sothree.slidinguppanel.SlidingUpPanelLayout 
 ....
  sothree:umanoOverlay="false"
/>

**Comment by Arpit0492** [comment]
Thanks people for this discussion. As @cesards figured it out. one can set the sothree:umanoOverlay="true" if you want the SlidingUp panel to appear over the main layout from below/top.

**Comment by ansonngch-Sephora** [comment]
this is still helpful in 2020
