### ISSUE TITLE
EditText or Button behind Sliding panel Up receives the onClick

### ISSUE THREAD

**Issue by nicolasjafelle** [umano/AndroidSlidingUpPanel#15]
If you set your dragView and behind the Sliding Panel Up it is a Form layout (with buttons and edittexts) they can be clicked. For example:

slidingUpLayout.setDragView(mediaPlayer);

login.setOnClickListener() {
       //...
       Toast.makeText(getContext, "LoginButton Clicked", Toast.LENGTH_SHORT).show;
}

**Comment by azizimusa** [comment]
Hi. Im having the same problem. setting `.setTouchEnabled(false)` make android soft keyboard not appear when tap on edittext. I want both feature.

**Comment by Ram8948** [comment]
Hi. Im having the same problem
