### ISSUE TITLE
Close the sliding panel programmatically?

### ISSUE THREAD

**Issue by JasonAndujar** [umano/AndroidSlidingUpPanel#171]
Hello, I'm looking for a method to hide the panel if the panel is open. Something along the lines of slidingPanel.hide(); or similar.. I'll search through your library and see if I can implement something myself, just wondering if there was a better way to do this. thanks

**Comment by Aamir-Altaf-Kathu** [comment]
Anyone still trying to get Answer use this: 
slidingUpPanelLayout.setPanelState(SlidingUpPanelLayout.PanelState.COLLAPSED);

**Comment by SluggedGerm2** [comment]
@Aamir-Altaf-Kathu Thanks you!

**Comment by pcg92** [comment]
What about if I want to close the sliding panel with the slide animation?
