### ISSUE TITLE
Question: How can I build use a gradle

### ISSUE THREAD

**Issue by moltak** [umano/AndroidSlidingUpPanel#188]
Hi. I'm moltak. When I try to build a source use gradle, it was occurred 'No such property: nexusUsername for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer' errors.
How can I fix it?

**Comment by wangbourne** [comment]
perfect

**Comment by YmlMark** [comment]
I'd put this in the top-level README
