### ISSUE TITLE
ClassNotFoundException when unmarshalling

### ISSUE THREAD

**Issue by deimos1988** [umano/AndroidSlidingUpPanel#195]
Hello,

I noticed that when I change the language of my device, I get following error when I resume my app, which uses the SlidingUpPanel in one of its fragments:

"ClassNotFoundException when unmarshalling: 
  com.sothree.slidinguppanel.SlidingUpPanelLayout$SavedState"

Is it only me, or is it a known bug (couldn't find anything on that)?

**Comment by valeryDenivip** [comment]
It still happens if use SlidingUpLayout with SupportMapFragment as a first view.

**Comment by varunpappu** [comment]
Yes it still happens with map view on the second swipe of the tablayout

**Comment by varunpappu** [comment]
Hi, @valeryDenivip : Follow this, this helped me solving the above error. http://stackoverflow.com/questions/13900322/badparcelableexception-in-google-maps-code/24651246#24651246
