### ISSUE TITLE
Panel keeps on collapsing on touch of the views inside it (button)

### ISSUE THREAD

**Issue by rendecano** [umano/AndroidSlidingUpPanel#2]
Hi,

First of all, thanks for this one. =)

I just wanna ask, I tried running the Demo app included in the project and then added some buttons inside the sliding panel but I can't click on the buttons, but instead the panel keeps on hiding. 

Am I missing something here? 

Thanks and regards!

**Comment by anandraj16992** [comment]
Hello,

mPanelLayout.setDragView(this.findViewById(R.id.ivPullUp)); 

This method is not working for me. I have tried to set my whole view as dragview still it's not working. Please update for same.
