### ISSUE TITLE
Classnotfound when unmarshalling (same as issue #195, more information)

### ISSUE THREAD

**Issue by deimos1988** [umano/AndroidSlidingUpPanel#232]
Hello,

in issue #195 I wrote that I am getting an error  "android.os.BadParcelableException: ClassNotFoundException when unmarshalling:".
The complete stacktrace of the error can be seen here:

http://pastebin.com/8mMk1W3h

I am putting a google mapview inside it, might this be a problem? I couldn't reproduce it with the original demo app.
I can reproduce it with my app when changing the language of the device, but according to customer it sometimes also occurs spontaneously.

This is the layout where I am using the sliding-panel:
http://pastebin.com/cVviZ6tu

In my code the error occurs in this line:
this.mapView.onCreate(savedInstanceState);

I would be incredibly grateful if the error can be fixed or at least narrowed down!

**Comment by tokudu** [comment]
Please reopen with more information

**Comment by kgritesh** [comment]
This happens also for me @deimos1988 were you able to find any solution. I am also putting a google mapview inside SlidingUpPanelLayout.
