### ISSUE TITLE
Nested AndroidSlidingUpPanel

### ISSUE THREAD

**Issue by MatthewTrout** [umano/AndroidSlidingUpPanel#266]
Hi there,

Just wondered whether there was any experience / inherent caveat in nesting panels, for instance in a nested fragment.  I'm getting some peculiar behaviour where the nested Panel is unreachable by Id (findViewById returns null).   In addition to which, Closing the nested panel, closes the outer panel also.  Can I assume it's just not built for this scenario?

Thanks

**Comment by jaytj95** [comment]
I think the requirement I have is a bit different. I want to put a sliding panel inside of one sliding panel. Something like this:

```
<com.sothree.slidinguppanel.SlidingUpPanelLayout
    xmlns:sothree="http://schemas.android.com/apk/res-auto"
    android:id="@+id/sliding_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="bottom"
    sothree:umanoPanelHeight="68dp"
    sothree:umanoShadowHeight="4dp">

    <TextView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center"
        android:text="Main Content"
        android:textSize="16sp" />

    <include layout="@layout/another_sliding_panel"
</com.sothree.slidinguppanel.SlidingUpPanelLayout>
```

and in the file "another_sliding_panel" there is another `com.sothree.slidinguppanel.SlidingUpPanelLayout`

**Comment by 159159951** [comment]
I share you my code and hope is is work for your case.

`

<com.sothree.slidinguppanel.SlidingUpPanelLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:sothree="http://schemas.android.com/apk/res-auto"
    android:id="@+id/sliding_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="bottom"
    sothree:umanoFadeColor="@android:color/transparent"
    sothree:umanoOverlay="true"
    sothree:umanoPanelHeight="68dp"
    sothree:umanoParallaxOffset="100dp"
    sothree:umanoScrollableView="@+id/sliding_layout_child"
    sothree:umanoShadowHeight="4dp">

    
    <com.sothree.slidinguppanel.SlidingUpPanelLayout
        android:id="@+id/sliding_layout_child"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="bottom"
        sothree:umanoFadeColor="@android:color/transparent"
        sothree:umanoOverlay="true"
        sothree:umanoPanelHeight="168dp"
        sothree:umanoParallaxOffset="100dp"
        sothree:umanoShadowHeight="4dp">

        <TextView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/red"
            android:text="aaaaaaaaaaaaa" />

        <TextView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/green"
            android:text="bbbbbbbbbbbbbbb" />


    </com.sothree.slidinguppanel.SlidingUpPanelLayout>
    
    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/blue">

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentTop="true"
            android:gravity="top|left"
            android:text="This is order ticket top" />

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentBottom="true"
            android:gravity="bottom|right"
            android:text="This is order ticket bottom" />
    </RelativeLayout>


</com.sothree.slidinguppanel.SlidingUpPanelLayout>
`
