### ISSUE TITLE
Feature Request: variable panel widths

### ISSUE THREAD

**Issue by RaffiOhanian** [umano/AndroidSlidingUpPanel#273]
Apparently the lib itself doesn't have the corresponding method, I've tried to set it programatically using LayoutParams but I keep getting an error message that says "HEIGHT should always be MATCH_PARENT) but this is the code im trying .

slidingUpPanel.setLayoutParams(new LayoutParams(x, LayoutParams.MATCH_PARENT))

please advice how to do this

**Comment by lacasrac** [comment]
Is there any solution for create a 50-50% height both elements?

**Comment by axay** [comment]
I have a similar problem while using the panel with a ViewPager. I have asked the question [here](http://stackoverflow.com/questions/30326497/setting-the-panel-height-of-umanos-sliding-up-panel-dynamically). Can someone please help ?

**Comment by tokudu** [comment]
Closing this. For different sizes of the panel, just use a different parent layout.
