### ISSUE TITLE
onPanelCollapsed() call to hidePanel()

### ISSUE THREAD

**Issue by stevenhewitt** [umano/AndroidSlidingUpPanel#280]
For my App, I want it so that sometimes when the sliding panel is closed that it goes away completely instead of just collapsing.  I tried calling hidePanel() in onPanelCollapsed, but hidePanel() does nothing when called there (it does work when called at any other time).  I can't think of any clean alternatives that create the expected behavior.

**Comment by tokudu** [comment]
You can hide the panel from any state in the upcoming version 3.0 https://github.com/umano/AndroidSlidingUpPanel/commit/36c006360f84a95aa628d900e9d464007ec9030e

**Comment by subodh-malgonde** [comment]
@tokudu calling setPanelState(SlidingUpPanelLayout.PanelState.HIDDEN) does not work when called from onPanelCollapsed.
