### ISSUE TITLE
Unable to use like LinearLayout

### ISSUE THREAD

**Issue by guru2010j** [umano/AndroidSlidingUpPanel#294]
I would like to say thanks for superb library and its exactly matches my requirement, but I need set weight-sum and need to divide in to 2 parts. assume sum is 2 need to set to linearlayouts, so it can support all mobiles, the second layout need to cover first layout when  user slides up.please help as soon as possible its an urgent for me. or is there any other way to implement.

Please see below image, there red bordered layout is my firstlayout(MainContent) and green layout is second which is slide up. please help me how can i achieve this requirement.

Regards,
Guruprasad.
![example](https://cloud.githubusercontent.com/assets/5434514/4856375/edb93b32-60b8-11e4-9c8f-a8c787e71a00.png)

**Comment by tokudu** [comment]
What value are you using to set the height?

**Comment by tokudu** [comment]
Please reopen if still having issues.
