### ISSUE TITLE
Bug with Edittext

### ISSUE THREAD

**Issue by longnguyen0410** [umano/AndroidSlidingUpPanel#301]
I have layout below:
"AndroidSlidingUpPane android:gravity="top" 
-------LinearLayout
-------------ListView
-------------EditText
-------LinearLayout
-------TextView
AndroidSlidingUpPanel"

Step 1: Slide down panel
Step 2: Slide up panel
Step 3: Touch on editext
Bug: Android keyboard show up but the keyboard overlay edittext, the edittext disapear :(

**Comment by tokudu** [comment]
Dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/356
