### ISSUE TITLE
Allow transparent panel background in non-overlay mode. 

### ISSUE THREAD

**Issue by Z-13** [umano/AndroidSlidingUpPanel#313]
I create panel:
```java
sLayout = (SlidingUpPanelLayout)findViewById(R.id.sliding_layout);
mainScreen = new MainScreen(sLayout.getContext());
keyboardLayout = new KeyboardLayout(sLayout.getContext());

sLayout.addView(mainScreen);
sLayout.addView(keyboardLayout);
```

My MainScreen params:
```javaLayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT```

MainScreen to contains ListView with params:
```javaLayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT```

KeyboardLayout not setBackgroundColor, BUT it have black background!

a) I set background color for sLayout then KeyboardLayout change background too.
b) I set overlay: sLayout.setOverlayed(true); - background keyboardLayout transparent - it's good, but not quite)

If overlay = true, then MainScreen(ListView) comes under KeyboardLayout
If overlay = false, then MainScreen(ListView) stretched to KeyboardLayout

I want to MainScreen(ListView) stretched to KeyboardLayout and KeyboardLayout backgroung will transparent.

How to do this?

Thank you!

**Comment by tokudu** [comment]
Fixed in https://github.com/umano/AndroidSlidingUpPanel/commit/acd917d7dc29e8b0b734773d74fa8d689e956406. Use the `clipPanel` attribute and set it to false.
