### ISSUE TITLE
How to hide the SlideupPanel when  clicking outside the panel. 

### ISSUE THREAD

**Issue by RethinavelPillai** [umano/AndroidSlidingUpPanel#321]
Here, I am using slidingup panel library. You can see both the panel and listview in the following screen. What i am trying to do is to hide the panel if i click outside the panel(Dim Area). Instead it is clicking on the listview in the above layout. How can i achieve this? 

Here is the XML,

      <?xml version="1.0" encoding="utf-8"?>
      <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
       xmlns:app="http://schemas.android.com/apk/res/com.voucher.point.activity"
       android:layout_width="fill_parent"
       android:layout_height="fill_parent"
       android:orientation="vertical" >

    

    <com.sothree.slidinguppanel.SlidingUpPanelLayout
        xmlns:sothree="http://schemas.android.com/apk/res-auto"
        android:id="@+id/sliding_layout"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:gravity="bottom"
        app:fadeColor="@color/transparent"
        sothree:panelHeight="40dip"
        sothree:paralaxOffset="200dp" >

        <LinearLayout
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            android:background="@color/white"
            android:orientation="vertical" >

            <ListView
                android:id="@+id/offersList"
                android:layout_width="fill_parent"
                android:layout_height="fill_parent"
                android:scrollbars="none"
                android:visibility="gone" >
            </ListView>

        </LinearLayout>

        <include
            android:id="@+id/bottom_menu"
            android:layout_width="fill_parent"
            android:layout_height="270dip"
            layout="@layout/side_menu" />
    </com.sothree.slidinguppanel.SlidingUpPanelLayout>

</LinearLayout> 

Can i do like this?

![unnamed](https://cloud.githubusercontent.com/assets/5887750/5234158/95aebde8-77df-11e4-9654-a613685f26d9.png)

**Comment by tokudu** [comment]
Your can implement your own dimming effect in the main content using the PanelSlideListener and then make your dimmed view clickable.
