### ISSUE TITLE
Not possible to change from hidden to collapsed state

### ISSUE THREAD

**Issue by orrc** [umano/AndroidSlidingUpPanel#322]
The public [`collapsePanel()`](https://github.com/umano/AndroidSlidingUpPanel/blob/1b6109c/library/src/com/sothree/slidinguppanel/SlidingUpPanelLayout.java#L859-L860) method does nothing if the state is `COLLAPSED` (which is understandable), but also if the state is `HIDDEN`.

It would be useful to be able to animate into the collapsed position when the panel is hidden.

**Comment by tokudu** [comment]
Fixed in the upcoming version 3.0 https://github.com/umano/AndroidSlidingUpPanel/commit/36c006360f84a95aa628d900e9d464007ec9030e
