### ISSUE TITLE
Element from panel gets covered by main view

### ISSUE THREAD

**Issue by ghost** [umano/AndroidSlidingUpPanel#328]
Hi, I'm trying to accomplish a view which only contains a listview and my sliding up menu. The sliding up menu has a seek bar on top (as a fragment) which actually overlays the menu. The idea is that the seek bar will be exactly in the middle between the menu and the listview but the problem I'm finding is that the listview (or whichever element is on top for that matters) covers the overlaying half of the seek bar. Is there anyway to avoid that? I've been fiddling with the menu properties and different layouts configurations all day and have been unable to fullfill this.

**Comment by tokudu** [comment]
Have a look at the clipChildren attribuet of the layout. See if that works for you. http://developer.android.com/reference/android/view/ViewGroup.html#attr_android:clipChildren
