### ISSUE TITLE
Multiple swipe effect like Left-Right-Top-Bottom in panel is not working

### ISSUE THREAD

**Issue by ShreyashPromact** [umano/AndroidSlidingUpPanel#331]
Hello,

I have implemented this demo. My requirement is to have multiple swipe effect in the panel. I have added it to the demoActivity. I can able to do Horizontal swipe but i am not able to do Vertical Swipe. because doinf vertical swipe the panel get closed. I guess it detect the touch listener of the panel.

Please help me for how to have that multiple swipe effect in the panel.

For reference i  have added this demo in to the panel: https://bitbucket.org/NxAlex/swipes-navigation-demo/src

**Comment by krishna2122** [comment]
Hi Guys, I am trying to implement right left swipe to close the panel from DragView with animation effect , I am not able to make that , can anyone please help me .
