### ISSUE TITLE
SlidingPanel is draggable even though drag view is not clicked

### ISSUE THREAD

**Issue by Dalanie** [umano/AndroidSlidingUpPanel#335]
I got this strange behaviour to be able to drag the slidingpanel even though my drag view is not clicked.
This occurs only when trying to slide the panel up from the bottom position. In anchored or maximized position the drag-view works as expected. Only when the sliding-panel is on the bottom I can drag it up by clicking anywere within the sliding-panel.

Does anyone know this behaviour or how to fix it?

Regards

Small Layout-Example (might be a problem?):

     <RelativeLayout 
     android:layout_width="wrap_content"
     android:layout_height="wrap_content">

	
    <LinearLayout
        android:id="@+id/alwaysVisibleView"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:layout_alignParentTop="true"
        android:background="@color/app_color"
        android:orientation="vertical">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/app_color"
            android:orientation="horizontal">

			
            <ImageView
                android:id="@+id/currentStateImage"
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_gravity="center_horizontal"
                android:layout_weight="0.15"
                android:padding="5dp"
                android:scaleType="fitCenter"/>

            <TextView
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="0.7"
                android:gravity="center_vertical|center_horizontal"
                android:textColor="@android:color/white"
                android:textSize="16sp" />

            <ImageView
                android:id="@+id/refreshImage"
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="0.15"
                android:padding="5dp"
                android:scaleType="fitCenter"
                android:src="@drawable/ic_refresh" />
        </LinearLayout>
    </LinearLayout>

	
    <android.support.v7.widget.CardView
        android:layout_width="match_parent"
        android:layout_below="@id/alwaysVisibleView"
        card_view:cardCornerRadius="5dp"
        android:layout_margin="5dp"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <TextView
                android:id="@+id/textView3"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginStart="5dp"
                android:layout_marginTop="5dp"
                android:gravity="center"
                android:textAppearance="?android:attr/textAppearanceMedium" />

            <ListView
                android:id="@+id/logView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:padding="10dp" />
        </LinearLayout>
    </android.support.v7.widget.CardView>
     </RelativeLayout>

**Comment by tokudu** [comment]
Please reopen if you are still having issues.
