### ISSUE TITLE
Black background on first time sliding panel expanded

### ISSUE THREAD

**Issue by nocturnalprelude** [umano/AndroidSlidingUpPanel#338]
I've tried to set:

          <FrameLayout 
   android:layout_width="fill_parent"
   android:layout_height="fill_parent"
   android:background="#FFFFFF"
   android:layout_gravity="center" >

in the SLIDING LAYOUT (LinearLayout), but I've noticed that first time panel is expanded, the background is black... then is white as I expected.
How comes this ?

**Comment by tokudu** [comment]
Please reopen with more information
