### ISSUE TITLE
Overlay not working

### ISSUE THREAD

**Issue by ztomaz** [umano/AndroidSlidingUpPanel#339]
Overlay is not working. 
Change:
if (mParallaxOffset > 0 && mSlideOffset >= 0) {
To:
if (mParallaxOffset > 0 && mSlideOffset >= 0 && !mOverlayContent) {
in line 973 of SlidingUpPanelLayout.java

**Comment by tokudu** [comment]
I can't seem to reproduce your error. The demo app seems to be functioning correctly. Have you tried it?
