### ISSUE TITLE
Blank screen on fragment replace if SlidingPanel is expanded.

### ISSUE THREAD

**Issue by burnermanx** [umano/AndroidSlidingUpPanel#340]
I'm trying to put a fragment with SlidingUpPanel to be replaced by a navigation drawer, but if I replace fragment with SlidingPanel is expanded, I got a blank screen which backs to normal (and is draggable, even if I disable it) if I click on it.
If panel is collapsed, I have normal behavior on screen.

EDIT:
debugging it, I discover mSlidebleView is coming null on fragment replace back. Curiously everthing is going back when I click or drag mSlidebleView.

EDIT 2:
Resolved in parts using issue #224 solution, but I want to maintain the panel expanded on fragment replace back. If I call expandPanel() I'll be back on blank screen issue.

**Comment by tokudu** [comment]
@burnermanx can you create a small sample project where I can reproduce the issue? I will reopen the issue, if I can reproduce it.
