### ISSUE TITLE
Collapse Panel: blank chunk at bottom of screen

### ISSUE THREAD

**Issue by romangromov** [umano/AndroidSlidingUpPanel#341]
Hi @tokudu, thank you so much for your great work and awesome library. 

I'm using ```MapFragment``` as Panel content. It works fine, but from time-to-time a little blank chunk appears in the bottom of the map while hiding Panel. Also, the Toolbar height is reduced by the same value as blank chunk height. Please, look at the screenshot:

![screenshot_2014-12-17-14-51-26](https://cloud.githubusercontent.com/assets/1655573/5470833/2e62c2de-8607-11e4-9f55-a83ff2041ecb.png)

I've prepared a sample demo so you can reproduce this issue: https://github.com/romangromov/SlidingPanelDemoIssue

Steps to reproduce:
1. SlidingPanel is expaned by default.
2. Tap somewhere on the Map
3. Sliding Panel disappearing with call to ```hidePanel()```, but a little blank chunk appears at the bottom of the map. The chunk's height is random from time-to-time.

Could you please take a time to look into this? Thanks in advance for any help on this!

**Comment by tokudu** [comment]
Closing since it's a likely issue with the buggy mapview.
