### ISSUE TITLE
Can't slide programmatically and disable touch

### ISSUE THREAD

**Issue by ppamorim** [umano/AndroidSlidingUpPanel#343]
Hi, I've some some troubles with this lib. I'm trying close the view only when the user click in a button with the swipe locked. But the methods on this lib doesn't help.
Anyone can help me?

**Comment by tokudu** [comment]
Fixed in upcoming version 3.0 https://github.com/umano/AndroidSlidingUpPanel/commit/36c006360f84a95aa628d900e9d464007ec9030e

**Comment by Phoenix1708** [comment]
When can we get the 3.0 from maven central ? I am using Gradle. I also need it urgently. Many thanks.

**Comment by lotz** [comment]
I don't need 3.0 urgently, but I am curious if you have a rough timeframe for 3.0.  A week, a month, six months?

Thanks for all your hard and excellent work on this!

**Comment by tokudu** [comment]
There were some other changes I wanted to include into 3.0, but I might
release it without them next week.

Anton

**Comment by lotz** [comment]
Nice, thanks again!
