### ISSUE TITLE
showPanel() not working shortly after hidePanel() and vice versa

### ISSUE THREAD

**Issue by Pkmmte** [umano/AndroidSlidingUpPanel#345]
If I call hidePanel() and shortly afterwards call showPanel(), the showPanel() call gets ignored if called too soon. I think it's because the panel is sliding animating to the hidden state when I call showPanel() and therefore ignores the call. It's easy to replicate this issue by simply calling those two together, maybe with some slight delay.

I understand we're not supposed to use these two so quickly but here's my use case: In my app, the panel hides when user starts dragging the map and reappears when they stop dragging and new data loads. This works fine and all but in some cases my data loads so fast that the panel has yet to finish hiding and therefore ignores the second call.

Example:
https://play.google.com/store/apps/details?id=co.nowl
Right after clicking the location button, the panel hides and refuses to appear again until something else triggers it.

**Comment by tokudu** [comment]
Please execute the call on the handler. Also, keep in mind that the API is changing in the upcoming version 3.0 https://github.com/umano/AndroidSlidingUpPanel/commit/36c006360f84a95aa628d900e9d464007ec9030e

**Comment by subodh-malgonde** [comment]
@Pkmmte how did you handle this?

@tokudu what handler are you talking about?

**Comment by Pkmmte** [comment]
@subodh-malgonde I ended up forking the latest version of this library, having a "queuedState" variable, and having a timer check the currentState with the queuedState every half second to ensure setPanelState() worked correctly. It's not the best solution but at least it works now.

**Comment by subodh-malgonde** [comment]
@Pkmmte Thanks, but I could not find any "queuedState" variable in the latest version? I am looking in the SlidingUpPanelLayout.java.  Can you maybe explain with a code snippet?

**Comment by Pkmmte** [comment]
@subodh-malgonde Essentially, I just created a variable called mQueuedState and a Runnable which compares it to mSlideState recursively. When the view is constructed, it calls a fixState() function that executes that runnable with a 500 millisecond delay.

In short:

	private PanelState mQueuedState;

	private final Runnable runnable = new Runnable() {
		@Override
		public void run() {
			if(mQueuedState != mSlideState && (mSlideState == PanelState.HIDDEN))
				setPanelState(mQueuedState);
			fixState();
		}
	};

public void setPanelState(PanelState state) {
		if (state == null || state == PanelState.DRAGGING) {
			throw new IllegalArgumentException("Panel state cannot be null or DRAGGING.");
		}
		mQueuedState = state;
		if (!isEnabled()
				|| mSlideableView == null
				|| state == mSlideState
				|| mSlideState == PanelState.DRAGGING) return;

		if (mFirstLayout) {
			mSlideState = state;
		} else {
			if (mSlideState == PanelState.HIDDEN) {
				mSlideableView.setVisibility(View.VISIBLE);
				requestLayout();
			}
			switch (state) {
				case ANCHORED:
					smoothSlideTo(mAnchorPoint, 0);
					break;
				case COLLAPSED:
					smoothSlideTo(0, 0);
					break;
				case EXPANDED:
					smoothSlideTo(1.0f, 0);
					break;
				case HIDDEN:
					int newTop = computePanelTopPosition(0.0f) + (mIsSlidingUp ? +mPanelHeight : -mPanelHeight);
					smoothSlideTo(computeSlideOffset(newTop), 0);
					break;
			}
		}
	}

	private void fixState() {
		postDelayed(runnable, 500);
	}


The full gist I made for it:
https://gist.github.com/Pkmmte/57cd4f18b940f5e3bd78
