### ISSUE TITLE
 How to include the library project as a dependency in Eclipse ?

### ISSUE THREAD

**Issue by VincentLin78** [umano/AndroidSlidingUpPanel#348]
I just download the source and import /library to Eclipse as a Existing Android Code. But there's no library.jar in bin after building the project, neither the error message .

I would like to add the library to my developing app. So I guess I have to build it successfully with library.jar being output to /bin. Or is there other way to make dependency between them ?

**Comment by romangromov** [comment]
btw: android studio is modern way to develop for Android and it's recommended by Google Inc.

**Comment by tokudu** [comment]
what @romangromov said. Otherwise, there are lots of tutorials online how to add library projects in eclipse.
