### ISSUE TITLE
No way to force sliding to end at anchor point

### ISSUE THREAD

**Issue by ethpran** [umano/AndroidSlidingUpPanel#349]
Hey, first of all, great library. I've been trying to work this out using the given API and maybe I just haven't implemented it correctly, but here's the issue: If I want to prevent the panel from sliding all the way up to the top, it seems like there's no way to do that.  I tried implementing  the PanelSlideListener interface and calling the achnorPanel method in onPanelExpanded, thinking that I could get cause the panel to animate back to the anchor whenever it was expanded, but that didn't work (the callback occurs but anchorPanel doesn't do anything in this situation). Is there any other way to somehow get an effect of preventing the user from expanding the panel to the top of the screen (using gravity=bottom)?

**Comment by mielet** [comment]
I too am trying to set the panel such that the user is unable to drag all the way to the top, but whenever I play around with the height of the panel, only the panel handle's height increases and does not impede the user from dragging the whole panel upwards
