### ISSUE TITLE
PointerIndex out of range in ViewDragHelper

### ISSUE THREAD

**Issue by RaffiOhanian** [umano/AndroidSlidingUpPanel#351]
Im getting this Exception when i try multitouching the panel so fast in processTouchEvent ACTION_MOVE is this a known issue?

**Comment by Kyson** [comment]
i got the same problem,how to deal with it?

**Comment by RaffiOhanian** [comment]
Well i guess the exception is there and there is nothing you can do with it, so i just put the part where the exception happens in a try catch block, and actually its working just fine , the internal exception isn't stopping anything .

**Comment by Kyson** [comment]
Ok，thx。

**Comment by tokudu** [comment]
Fixed in master.
