### ISSUE TITLE
the slidingUpPanel is not scrolled in grid view.

### ISSUE THREAD

**Issue by fin10** [umano/AndroidSlidingUpPanel#352]
Hello,
I have used your component very well.

but it seems to have a problem that when the sliding layout is the grid view, it's not scrolled.
I had set the grid view to not clickable, and set dragView (but it's impossible, because the grid view is not allow to set clickable.)

I can't solution about this issue, so I've used the grid layout, but I want to use the grid view.
could you check this issue?

thank you!

**Comment by bhuvneshvarma** [comment]
I am using SlidingUpPanel. My SlidingUpPanel consists of GridView.When the sliding up panel is in expandable state then if i swipe up and down on gridview then i want gridview to scroll up and down.But sometimes wht hapeens is that the swipe action is taken by SlidingUp panel and hence on down swiping the panel closes and on up swiping there is no response as panel is already expanded.How can i do it in such a way that panel only responds to swipe action only when user swipe on top above gridview else swipe action should be taken by gridview only?

**Comment by tokudu** [comment]
The panel doesn't currently support this out of the box. Please see the workarounds here https://github.com/umano/AndroidSlidingUpPanel/issues/116
