### ISSUE TITLE
The fade should be over anything you declare within the "MAIN CONTENT"

### ISSUE THREAD

**Issue by eugeneisrambo** [umano/AndroidSlidingUpPanel#355]
I am getting the same effect of the fade behind the main content rather in front of it.  This does not go along side with Google's Material Guidelines.  http://www.google.com/design/spec/components/bottom-sheets.html#bottom-sheets-specs    It should fade infront of anything you put into the Main Content  Layout above the slide layout.  Example of the issue.  
This is my normal layout.  
![screenshot_2014-12-31-09-34-05](https://cloud.githubusercontent.com/assets/7454787/5588252/d132e032-90d1-11e4-8977-363ba0f95f21.png)

This is when the slide is coming up or down doesn't matter.  

![screenshot_2014-12-31-09-33-46](https://cloud.githubusercontent.com/assets/7454787/5588256/eec01f20-90d1-11e4-909a-948a6c416a2b.png)

I would really like to use this library in my project but I cannot use the library unless it is going in the same path of Google's Material Guidelines.  All that being said, I really enjoy this library.  It can help developers bring android to the next level.  Cheers!

**Comment by deronbrown** [comment]
+1 I've discovered this issue as well and briefly mentioned it in #356. The fade works as expected in version 2.0.2.

**Comment by tokudu** [comment]
I believe, it's fixed in https://github.com/umano/AndroidSlidingUpPanel/commit/3c6f003dabcc097a354cde0d6fdb6bd178daa0e8
