### ISSUE TITLE
[Question] Add third view to SlidingUpPanelLayout that shows above SlideableView

### ISSUE THREAD

**Issue by TR4Android** [umano/AndroidSlidingUpPanel#357]
First of all thank you for the good work on the library. It was exactly what I've been looking for.
For the past couple of days though I've been trying to add a third view to the ViewGroup of the SlidingUpPanelLayout (actually a Floating Action Button), as I'm moving forward with Material Design. Whatever I do though, the Floating Action Button always seems to show under the Slideable View instead of above it (on the Z axis) which is not my desired behaviour, even though the Floating Action Button gets laid out last and drawn last. Why is that? Is there anything specific that assures the Slideable View stays on top? ![2015-01-05_10 45 14 1](https://cloud.githubusercontent.com/assets/10142068/5611550/454a6b58-94c8-11e4-91e2-721cd91ef587.png)

**Comment by tokudu** [comment]
the layout always must have two children. I recommend surrounding the
layout with a FrameLayout, where the second child is your action button.
