### ISSUE TITLE
Background fading shadow not working with latest release

### ISSUE THREAD

**Issue by kamikaze2586** [umano/AndroidSlidingUpPanel#361]
Using version 2.0.4, I noticed that the background no longer fades on sliding the panel up (at least testing on android lollipop), but when I revert back to 2.0.2, it does.

Is it the case that this feature been removed in the latest version or is it a bug?

Thanks

ps great work on this, love it.

Antonio

**Comment by tokudu** [comment]
Already fixed in master.

**Comment by jsonfry** [comment]
Any idea when this will be in a release? Cheers for the library :)

**Comment by tokudu** [comment]
Hopefully in a week or so.

Anton
