### ISSUE TITLE
setPanelState cannot resolve method

### ISSUE THREAD

**Issue by saidl14s** [umano/AndroidSlidingUpPanel#364]
![captura de pantalla 11](https://cloud.githubusercontent.com/assets/10568475/5786864/75017420-9db2-11e4-96f0-3704b1c83897.png)
¿Alguna idea de lo que este ocurriendo? Llevo días tratando sin éxito alguno, agradezco cualquier tipo de información.

**Comment by AndroidRio** [comment]
I can't resolve this method either.

**Comment by jagatappv** [comment]
I am facing same issue. Can anyone help me to resolve this.

**Comment by tokudu** [comment]
v3.0 hasn't been pushed to Maven yet.

**Comment by jagatappv** [comment]
Can you help me how can i achieve expand and collapse programatically using older version and how ?

**Comment by jagatappv** [comment]
Is it possible to expand and collapse programatically using current version?
I have current version 2.0.4 and using into Android studio.

**Comment by tokudu** [comment]
Please use expandPanel(). Does that not work for you? Try running it on a handler.
