### ISSUE TITLE
Having Sliding Panel visible programmatically

### ISSUE THREAD

**Issue by nocturnalprelude** [umano/AndroidSlidingUpPanel#366]
I need to hide the Sliding Layout until one button is clicked: in this case, the panel get visibile and it can be expanded \ collapsed.
I tried in this way:

onCreate:

dragview = (LinearLayout) findViewById(R.id.dragView);
dragview.setVisibility(View.GONE);

and on click:

dragview.setVisibility(View.VISIBLE);

But it seems not working... any ideas ?

**Comment by nocturnalprelude** [comment]
solved with:

dragview.hidePanel();

and

dragview.hidePanel();

**Comment by userswlwork** [comment]
very good

**Comment by Meeks91** [comment]
Hi,

I can't find the  hidePanel() method, could you tell me which class it is implemented by. 

Thanks in advance.

**Comment by AndreaLoden** [comment]
Is the method hidePanel() still available? Can't find it
