### ISSUE TITLE
The fadeColor is applied to only one view of my content.

### ISSUE THREAD

**Issue by julj** [umano/AndroidSlidingUpPanel#367]
When expanding the panel, only one view (an apparently random TextView) of the main content is applied the fadeColor. Am I missing something?

Nexus 5 with Android 4.4.4
com.sothree.slidinguppanel:library:2.0.4

Not expanded:

![device-2015-01-23-135212](https://cloud.githubusercontent.com/assets/380531/5874939/896289c2-a307-11e4-9d73-16d4131e0a58.png)

Expanded, only the view surrounded with the green line has the fadeColor applied:

![device-2015-01-23-135249](https://cloud.githubusercontent.com/assets/380531/5874961/baf36e52-a307-11e4-80bf-3adb0460b98b.png)

```xml
<com.sothree.slidinguppanel.SlidingUpPanelLayout
        xmlns:sothree="http://schemas.android.com/apk/res-auto"
        android:id="@+id/sliding_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="top"
        sothree:panelHeight="0dp"
        sothree:shadowHeight="4dp"
        sothree:overlay="true">

        <android.support.v4.view.ViewPager
            android:id="@+id/pager"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

        <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
            android:layout_width="match_parent"
            android:layout_height="164dp"
            android:orientation="vertical">

               <!-- some stuff -->

         </LinearLayout>

</com.sothree.slidinguppanel.SlidingUpPanelLayout>
```

**Comment by tokudu** [comment]
I believe this is fixed in master.

**Comment by julj** [comment]
Ok, I'll wait for the next release then. Thank you.
