### ISSUE TITLE
Sliding Panel not getting Collapsed

### ISSUE THREAD

**Issue by pmahsky** [umano/AndroidSlidingUpPanel#368]
Inside my code, panel is not getting collapsed when calling slidingPanelLayout.setPanelState(PanelState.COLLAPSED);

Scenario is like this : I have a button in sliding panel when its expanded, clicking on that activity.recreate() is called. I need to collapse sliding panel after that. But its not working. Even if I call the method for collapsing the panel, it appears expanded. Also I've put a check in onCreate() if its collapsed, but getting Collapsed state but its expanded actually. An anchorPoint is also set as 0.5 in my panel.

**Comment by tokudu** [comment]
Can you try running setPanelState(PanelState.COLLAPSED) on a handler and let me know if that helps. Are you using the version from master?

**Comment by pmahsky** [comment]
Hi Tokudu,
                  I resolved the issue. I tried earlier using handler, but that didn't worked. I needed to call requestLayout() to resolve the issue.

**Comment by mathieudebrito** [comment]
Hi @pmahsky , I have the same issue, 
When do I have to call requestLayout() please ?

**Comment by pmahsky** [comment]
Hi @mathieudebrito. In my case I had to re launch the activity when I tap the button inside Sliding Panel. As I said before, I had called recreate(). But it let the sliding panel expanded. So I tried with this approach -
             public void  onClick(View view){
				1. slidingPanel.setPanelState(PanelState.COLLAPSED);
				2. slidingPanel.requestLayout();
				3. context.finish();
				4. overridePendingTransition(0, 0);
				5. Intent intent = new Intent(context, <YourClass>.class);
				6. intent.setFlags(Intent.FLAG_ACTIVITY_NO_ANIMATION);
			        7. context.startActivity(intent);
			        8. overridePendingTransition(0, 0);
                             }

Line no 4,6 and 8 need not to be there. It was just my requirement.
