### ISSUE TITLE
Is necessary to FragmentManager

### ISSUE THREAD

**Issue by ppamorim** [umano/AndroidSlidingUpPanel#370]
Hi, I've 2 FrameLayout and replace these guys with 2 fragments. But sometimes, when I try to get the fragment inside the supportFragmentManager(or ChildFragmentManager) when onViewStateRestored is called, the device freeze and logcat say: Fragment (fragment) is not currently in the FragmentManager.

The view(1) of library(SlidingUpPanel) is another fragment and this 2 FrameLayout(2) are inside the view(1).

**Comment by tokudu** [comment]
This doesn't seem like an issue with the library. The panel doesn't do anything specific when it comes to FragmentManagement. If fact, the umanoapp has a very similar functionality, where is slidingView is a fragment, and everything seems to work fine.  I would recommend inspecting your fragment transactions code.
