### ISSUE TITLE
ImageView and Parallax effect disappear in Sliding up panel which is in the ViewPager

### ISSUE THREAD

**Issue by NogerbekNurzhan** [umano/AndroidSlidingUpPanel#371]
@tokudu Hello! Thank you for this awesome project! I have 2 problem. Can you help me with one of them? I have ViewPager with 3 Fragments. In First Fragment (page) I have Sliding Up Panel. Parallax effect works fine but when I change the page (move to another fragment) and go back to 1 fragment position of parallax effect is correct as in the picture below. How can I change it? Another problem that I have in TitleBar of that sliding panel I have ImageView as in the picture below. ImageView changes when user open or close Sliding up panel. MY PROBLEM: When I change the Fragment (move to another page) and go back to first page ImageVIew disappear. Whats the reason?!
![8390](https://cloud.githubusercontent.com/assets/8999232/6026404/c71b9050-ac04-11e4-9699-305da6a3f5bf.png)

Fragment1.java (setPanelSlideListener is in the onViewCreated method which is called immediately when the view is created...)

            mSlidingUpPanelLayout.setPanelSlideListener(new SlidingUpPanelLayout.PanelSlideListener() {
            @Override
            public void onPanelSlide(View panel, float slideOffset) {
                Log.i(TAG, "onPanelSlide, offset " + slideOffset);
            }

            @Override
            public void onPanelCollapsed(View panel) {
                Log.i(TAG, "onPanelCollapsed");
                mImageView.setBackgroundResource(R.drawable.icon_up);
            }

            @Override
            public void onPanelExpanded(View panel) {
                Log.i(TAG, "onPanelExpanded");
                mImageView.setBackgroundResource(R.drawable.icon_down);
                fab.setColorPressed(getResources().getColor(R.color.fab_up_pressed));
            }

            @Override
            public void onPanelAnchored(View panel) {
                Log.i(TAG, "onPanelAnchored");
            }

            @Override
            public void onPanelHidden(View panel) {
                Log.i(TAG, "onPanelHidden");
            }

            @Override
            public void onPanelHiddenExecuted(View panel, Interpolator interpolator, int duration) {
                Log.i(TAG, "onPanelHiddenExecuted");
            }

            @Override
            public void onPanelShownExecuted(View panel, Interpolator interpolator, int duration) {
                Log.i(TAG, "onPanelShownExecuted");
                mImageView.setBackgroundResource(R.drawable.icon_up);
            }

            @Override
            public void onPanelExpandedStateY(View panel, boolean reached) {
                Log.i(TAG, "onPanelExpandedStateY" + (reached ? "reached" : "left"));
            }

            @Override
            public void onPanelCollapsedStateY(View panel, boolean reached) {
                Log.i(TAG, "onPanelCollapsedStateY" + (reached ? "reached" : "left"));
                if (reached) {
          //fab.setColorPressed(getResources().getColor(R.color.fab_pressed));
                    //mTextView.setTextColor(Color.parseColor("#FFFFFF"));
                }else{
                                        //fab.setColorPressed(getResources().getColor(R.color.fab_up_pressed));
                    //mTextView.setTextColor(Color.parseColor("#FFFFFF"));
                }
            }

            @Override
            public void onPanelLayout(View panel, SlidingUpPanelLayout.PanelState state) {
                if(state == SlidingUpPanelLayout.PanelState.COLLAPSED){
                    titleBar.setBackgroundColor(Color.parseColor("#03A9F4"));
                    mImageView.setBackgroundResource(R.drawable.icon_up);
                }
                else if (state == SlidingUpPanelLayout.PanelState.EXPANDED || state == SlidingUpPanelLayout.PanelState.ANCHORED){
                    titleBar.setBackgroundColor(Color.parseColor("#ffff9431"));
                    mImageView.setBackgroundResource(R.drawable.icon_down);
                }
            }
        });

Thanks and have a nice day!

**Comment by tokudu** [comment]
Why not put the panel outside of the viewPager and simply hide it when you scroll to a page where the panel should be hidden?
