### ISSUE TITLE
sliding to end at anchor point during short tap in collapsed mode

### ISSUE THREAD

**Issue by hannesa2** [umano/AndroidSlidingUpPanel#372]
I can move from collapsed mode to anchored mode and expanded mode, but when my activity is collapsed mode, I do a short tab on visible view and SlidingUpPanel opens to expanded mode, but this behavour is not wanted.
How to open just in anchored mode ?

        <com.sothree.slidinguppanel.SlidingUpPanelLayout xmlns:sothree="http://schemas.android.com/apk/res-auto"
            android:id="@+id/sliding_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="bottom"
            sothree:umanoAnchorPoint="0.5"
            sothree:umanoDragView="@+id/map_sliding_layout"
            sothree:umanoInitialState="hidden"
            sothree:umanoPanelHeight="35dp"
            sothree:umanoParalaxOffset="150dp"
            sothree:umanoShadowHeight="4dp" >

Thank you !

**Comment by tokudu** [comment]
Please try version 3.0.0 and see if it's still an issue. The API changed a bit.

**Comment by hannesa2** [comment]
Thank you for your fast response.

I updated to 3.0.0 with any problem and tested my behavior but unfortunately the issue still exists.

**Comment by tokudu** [comment]
If you don't want to expand the panel on click, you can set an onClickListener on the panel, and do nothing inside of it.
