### ISSUE TITLE
setSlidingEnabled(false), hidePanel() is not working.

### ISSUE THREAD

**Issue by Summeraa** [umano/AndroidSlidingUpPanel#374]
I disabled sliding by setSlidingEnabled(false). When onClickerListener on the sliding panel view is clicked, the screen is replaced by another fragment as coded. However, the sliding panel still shows even with hidePanel() in the onClickListener. Is there a way to hide the panel in the new fragment?

**Comment by tokudu** [comment]
Please upgrade to v3.0.0 and use the new API mentioned in the change log.
