### ISSUE TITLE
can't build project since 5pm EST

### ISSUE THREAD

**Issue by spark85** [umano/AndroidSlidingUpPanel#375]
I'm getting the folllowing errors: 
Error:(9) No resource identifier found for attribute 'panelHeight' in package 'com.sothree.slidinguppanel'
Error:(9) No resource identifier found for attribute 'initialState' in package 'com.sothree.slidinguppanel'
Error:(9) No resource identifier found for attribute 'paralaxOffset' in package 'com.sothree.slidinguppanel'
Error:(9) No resource identifier found for attribute 'shadowHeight' in package 'com.sothree.slidinguppanel'

**Comment by tokudu** [comment]
Use the old version 2.0.4 in your gradle.build file or see the changelog and upgrade to v3.0.0

**Comment by vnguyen972** [comment]
I upgraded to 3.0.0 and still couldn't compile... went back to 2.0.4 and the error was gone. So how do we use it in 3.0.0? what are those attributes changed to?

**Comment by tokudu** [comment]
Please see the change log or the sample. An `umano` prefix has been added.

**Comment by AntonioRedondo** [comment]
On your `layout.xml` files you must add the `umano` prefix to `sothree` attributes.

What before was:
```xml
<com.sothree.slidinguppanel.SlidingUpPanelLayout
    xmlns:sothree="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="bottom"
    sothree:panelHeight="68dp"
    sothree:shadowHeight="4dp">
```
from version 3.0 is

```xml
<com.sothree.slidinguppanel.SlidingUpPanelLayout
    xmlns:sothree="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="bottom"
    sothree:umanoPanelHeight="68dp"
    sothree:umanoShadowHeight="4dp">
```
