### ISSUE TITLE
Bug in 3.0.0 

### ISSUE THREAD

**Issue by yshahak** [umano/AndroidSlidingUpPanel#376]
The new version 3.0.0 not worked in my project:
Error:(2) No resource identifier found for attribute 'panelHeight' 
Error:(2) No resource identifier found for attribute 'fadeColor' 
Error:(2) No resource identifier found for attribute 'initialState' 
Error:(2) No resource identifier found for attribute 'overlay' 
Error:(2) No resource identifier found for attribute 'shadowHeight'

**Comment by jithinsunnychalil** [comment]
Please correct this bug as I am facing this bug

**Comment by brotherxteam** [comment]
I had this bug too.

**Comment by retuner87** [comment]
With com.sothree.slidinguppanel:library:3.0.0 I have this bug too.

**Comment by tokudu** [comment]
Use an `umano` prefix for all attributes. Please see the changelog.

**Comment by AntonioRedondo** [comment]
On your `layout.xml` files you must add the `umano` prefix to `sothree` attributes.

What before was:
```xml
<com.sothree.slidinguppanel.SlidingUpPanelLayout
    xmlns:sothree="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="bottom"
    sothree:panelHeight="68dp"
    sothree:shadowHeight="4dp">
```
from version 3.0.0 is

```xml
<com.sothree.slidinguppanel.SlidingUpPanelLayout
    xmlns:sothree="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="bottom"
    sothree:umanoPanelHeight="68dp"
    sothree:umanoShadowHeight="4dp">
```
