### ISSUE TITLE
Allow calling of setPanelState without a handler.

### ISSUE THREAD

**Issue by r-deleon** [umano/AndroidSlidingUpPanel#377]
I updated the library to 3.0 and start using the method `setPanelState`.
The thing is I'm not able to hide the panel after created. Its always collapsed even though I set explicitly to HIDDEN.

```
 @Override
  public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {

    ... 
    ...
 

    mSlidingPanel = (SlidingUpPanelLayout) mRootView.findViewById(R.id.sliding_layout);
    mSlidingPanel.setOverlayed(false);
    mSlidingPanel.setPanelState(SlidingUpPanelLayout.PanelState.HIDDEN);
    Log.d("panel status", mSlidingPanel.getPanelState().toString());  // always "COLLAPSED"
 



```

**Comment by tokudu** [comment]
use `umanoInitalState attribute`

**Comment by LJoonas** [comment]
How to handle a situation where some times the initial state has to be hidden and sometimes it needs to be collapsed on start? What to do to get the setPanelState to work when creating new activity

**Comment by tokudu** [comment]
use two different layouts or run `setPanelState` on a handler.

**Comment by LJoonas** [comment]
Sorry, but what do you mean by running it on a handler? 
this?
```
 new Handler().post(new Runnable() {
                @Override
                public void run() {
                    mSlidingUpPanelLayout.setPanelState(SlidingUpPanelLayout.PanelState.HIDDEN);
                }
            });
```

**Comment by tokudu** [comment]
Yes.

**Comment by LJoonas** [comment]
```
 new Handler().post(new Runnable() {
                @Override
                public void run() {
                    mSlidingUpPanelLayout.setPanelState(SlidingUpPanelLayout.PanelState.HIDDEN);
                }
            });
```
When I add this to my activity onCreate or onResume then the panel is still not hidden consistently. Sometimes with the debugger attached It correctly hides after a few seconds, but I don't understand the delay.
Without the debugger it just remains Collapsed and nothing happens until I rotate the screen and then it is hidden.

**Comment by sothree** [comment]
I will keep the issue open and look into it.

On Tue, Feb 10, 2015 at 12:26 PM, Joonas <notifications@github.com> wrote:

>  new Handler().post(new Runnable() {
>                 @Override
>                 public void run() {
>                     mSlidingUpPanelLayout.setPanelState(SlidingUpPanelLayout.PanelState.HIDDEN);
>                 }
>             });
>
> When I add this to my activity onCreate or onResume then the panel is
> still not hidden consistently. Sometimes with the debugger attached It
> correctly hides after a few seconds, but I don't understand the delay.
> Without the debugger it just remains Collapsed and nothing happens until I
> rotate the screen and then it is hidden.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umano/AndroidSlidingUpPanel/issues/377#issuecomment-73776855>
> .
>



-- 
*Anton Lopyrev*
Co-Founder & CTO • Umano
Follow me @tokudu <http://twitter.com/tokudu>
http://umano.me

**Comment by LJoonas** [comment]
Just a heads up that using a 500ms (150 was too low and did not hide the panel) delay for the handler solves the problem for me on first launch.

**Comment by tokudu** [comment]
Fixed in https://github.com/umano/AndroidSlidingUpPanel/commit/468bb12b361348b3a67112445da2f0d8652a8b7d. Will be out in the next release.
