### ISSUE TITLE
setPanelState not changing panel state.

### ISSUE THREAD

**Issue by dimbslmh** [umano/AndroidSlidingUpPanel#379]
compile 'com.sothree.slidinguppanel:library:3.0.0' // app\build.gradle

    import com.sothree.slidinguppanel.SlidingUpPanelLayout;
    import com.sothree.slidinguppanel.SlidingUpPanelLayout.PanelState;

    private SlidingUpPanelLayout mLayout;
    ...............
    mLayout = (SlidingUpPanelLayout) findViewById(R.id.sliding_layout);
    Log.d(TAG, "mLayout.getPanelState(): " + mLayout.getPanelState()); // D/MainActivity﹕ mLayout.getPanelState(): COLLAPSED
    mLayout.setPanelState(PanelState.HIDDEN);
    Log.d(TAG, "mLayout.getPanelState(): " + mLayout.getPanelState()); // D/MainActivity﹕ mLayout.getPanelState(): COLLAPSED

**Comment by tokudu** [comment]
Use umanoInitialState or run setPanelState on a handler.
