### ISSUE TITLE
Bug with transparent background?

### ISSUE THREAD

**Issue by Frasprite** [umano/AndroidSlidingUpPanel#380]
Hi,
i have used your library on my app for a while and with the new update (3.0), the background of the second panel is no more transparent; this is what i used until now:
...
umano:dragView="@+id/detail_visible_layout"
umano:overlay="true"
And the LinearLayout named "detail_visible_layout" has:
android:background="@color/transparent"
(transparent on Android color xml is #99000000).
I know that you added clipPanel attribute for supporting transparent panels in non-overlay mode, so I changed a bit my code and added clipPanel attribute and setted overlay="false", but the result is the same.
Did i miss something?

**Comment by tokudu** [comment]
Please post your complete layout.

**Comment by Frasprite** [comment]
Sorry, here you are:
<?xml version="1.0" encoding="utf-8"?>
<com.sothree.slidinguppanel.SlidingUpPanelLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:umano="http://schemas.android.com/tools"
    android:id="@+id/sliding_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="bottom"
    umano:dragView="@+id/comic_detail_visible_layout"
    umano:overlay="true">

    <ImageView
        android:id="@+id/cover_image_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:adjustViewBounds="true"
        android:contentDescription="@string/cover_description"
        android:gravity="center"
        android:scaleType="centerCrop" />

    <LinearLayout
        android:id="@+id/comic_detail_main_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/transparent"
        android:gravity="center|top"
        android:orientation="vertical">
    </LinearLayout>

</com.sothree.slidinguppanel.SlidingUpPanelLayout>

**Comment by tokudu** [comment]
Can you reproduce the issue in the demo app? If I set the background on the layout and make the dragView transparent, everything seems to work fine.

**Comment by Frasprite** [comment]
My bad: i was using this "xmlns:umano="http://schemas.android.com/tools" and tag like umano:dragView="@+id/comic_detail_visible_layout" / umano:overlay="true".
I have changed it with "xmlns:sothree="http://schemas.android.com/apk/res-auto" and sothree:umanoDragView="@+id/comic_detail_visible_layout" / sothree:umanoOverlay="true", which solved my problem.

**Comment by androidvsourz** [comment]
This solved my problem too. Thank you so much @Frasprite

**Comment by Pranoy1c** [comment]
@Frasprite solution worked for me too!
