### ISSUE TITLE
Visibility changes and SlidingUpPanel

### ISSUE THREAD

**Issue by luiges90** [umano/AndroidSlidingUpPanel#381]
Basically they don't work very well.

`rootView.findViewById(R.id.slidingPanel).setVisibility(View.GONE);` in the beginning (i.e. `onResume` in my case), and then `rootView.findViewById(R.id.slidingPanel).setVisibility(View.VISIBLE);` will cause sliding panel having zero height, even I have slidingPanel height set in XML. 

Vice versa, `rootView.findViewById(R.id.slidingPanel).setVisibility(View.VISIBLE);` in the beginning, and then `rootView.findViewById(R.id.slidingPanel).setVisibility(View.GONE);` will cause the panel to goes white but still occupy space, covering main content, despite `overlay` is false all the time.

If I set the sliding panel height in code after calling `rootView.findViewById(R.id.slidingPanel).setVisibility(View.VISIBLE);`, then the main content will get covered by the sliding panel, despite `overlay` is false all the time.

**Comment by tokudu** [comment]
Try using `setPanelState(HIDDEN)`

**Comment by luiges90** [comment]
So I update library, so far so good. :smile:
