### ISSUE TITLE
Panel with fixed position content

### ISSUE THREAD

**Issue by or-bar** [umano/AndroidSlidingUpPanel#383]
Hi,

Is it possible to use the Library to show fixed position content. What I mean by that is the the content of the panel will stay in the same position on the screen when the panel is expanded. 

For example my panel needs to contain a title and a listview with a varying number of rows. The panel is positioned at the top of the screen. When the panel is anchored I want to display the title and the first row in the list. when the panel is expanded I want to show the title and the rest of the list.

Is something like this possible? is it on the road map?

Thank you

**Comment by tokudu** [comment]
I think you can take advantage of the panelSlideListener and reposition your content yourself when the panel moves.
