### ISSUE TITLE
Reverting dragView to entire panel after dragView has been set

### ISSUE THREAD

**Issue by ethpran** [umano/AndroidSlidingUpPanel#388]
I know the default behavior is for the whole panel to act as a drag view.  If I want to initially set a dragview which will be the only view that can consume drag events, I use either sothree:umanoDragView in XML or the setDragView method.  Now, if I want to programatically revert to the default behavior of the whole panel as draggable, it seems problematic.  I thought I could do something like setDragView(null), but that doesn't seem to work.  How would I programatically revert to the whole panel acting as the drag view after I declared a drag view?

**Comment by tokudu** [comment]
setDragView(null) should technically work. What behavior are you seeing?

**Comment by tokudu** [comment]
Please reopen with more information
