### ISSUE TITLE
parallax effect when sliding panel expanding

### ISSUE THREAD

**Issue by suresh777** [umano/AndroidSlidingUpPanel#389]
First of all thank you for providing sliding up library,in my project i am using your library.I tried parallax effect by measuring height of the screen according to that i am setting alpha to layout but from this i am not getting parallax effect perfectly,is there any alternative way to get parallax effect when moving bottom to top and top to bottom.

**Comment by suresh777** [comment]
public void onPanelSlide(View panel, float slideOffset) {

              int ratio = (int) -( 0 - (slideOffset) * 255);                  
              int newAlpha = 255 - ratio ;

              mActionBarBackgroundDrawable.setAlpha(newAlpha);

**Comment by tokudu** [comment]
Have a look at getCurrentParalaxOffset
