### ISSUE TITLE
SlidingUpPanelLayout won't collapse on resume after OS kill my activity

### ISSUE THREAD

**Issue by kentxshi** [umano/AndroidSlidingUpPanel#391]
I am using the latest version (3.0) of the SlidingUpPanelLayout library. Periodically the Android OS would kill my Activity if it's running in the background (exit by pressing Home instead of Back). If that happens, and the panel was expanded when the user last used the app, then the panel would still be expanded when it's created but all the content inside would be gone. Basically a blank screen.  The user is able to drag down the panel and every would be fine, but that's not a good experience.

In this scenario, I actually want to reset the activity to it's initial state (open after a full exit), which is collapsed. But I can't get that to work. In the layout xml, I am setting the initial state to collapsed.

<com.sothree.slidinguppanel.SlidingUpPanelLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:sothree="http://schemas.android.com/apk/res-auto"
    android:id="@+id/sliding_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="bottom"
    sothree:umanoPanelHeight="48dp"
    sothree:umanoShadowHeight="4dp"
    sothree:umanoInitialState="collapsed" >

I also placed this line

slidingUpPanelLayout.setPanelState(PanelState.COLLAPSED);

at a few places in onCreate() just to make sure, but panel is not collapsing. I printed the panel state before and after each collapse attempt and found that the panelState is actually set to collapsed before the very first collapse attempt, even though it clearly isn't collapsed.

So is this a bug in the library, or am I doing something wrong.

Thanks

**Comment by kentxshi** [comment]
I tried calling slidingUpPanelLayout.setPanelState(PanelState.COLLAPSED) in onDestroy(), and that didn't the problem.

**Comment by tokudu** [comment]
I'm not sure I understand why all the children inside of the panel are gone onResume of the activity. Can you clarify?

**Comment by kentxshi** [comment]
The views are there.  The tab (very top of the panel that you drag on) contain a couple icons, and they did show.  Although I use different icons based on the state of the panel.  It is showing the icons for panel collapsed, even though it is actually expanded.

The rest of the panel is just a list view.  The list view is initialized to empty (in onCreate), and I populate it when the user drag the panel up, because it is based on user input when panel was collapsed and it requires a server call.

So in this scenario, the app is showing an empty list with a couple (incorrect) icons at the top.  Sorry about not being more clear.

Thanks

**Comment by tokudu** [comment]
Based on your description, I don't think it's an issue with the library. The layout has not control what icons would or would not show. I would recommend reviewing your logic for initializing the panel contents. based on the state.

Also, calling slidingUpPanelLayout.setPanelState(PanelState.COLLAPSED) in onDestroy() is a bad idea. You should always let the views maintain their state across orientation changes.

**Comment by RonyBrosh** [comment]
For me the problem was that inside activity it works and inside (nested) fragment with less available height the panel just won't collapse..

I've found that the bug was with the slidePanelAnchorPoint..
It should be set according to the available height in order to work...
I believe that the sliding panel should check the slidePanelAnchorPoint to make sure it's not over the general sliding panel height (which I believe caused the problem)...

**Comment by vmkononenko** [comment]
Was struggling with the same issue. Setting slidePanelAnchorPoint to 0 as suggested by @RonyBrosh helped but I still don't see an explanation for it, did not debug deep enough.

**Comment by hufman** [comment]
I managed to work around this by adding logic in onResume to `setPanelState(SlidingUpPanelLayout.PanelState.HIDDEN)`. In my case, I wanted to conditionally ignore the saved bundle after some time had elapsed.
