### ISSUE TITLE
Question: How to know the next state of the AndroidSlidingUpPanel

### ISSUE THREAD

**Issue by joaofyz** [umano/AndroidSlidingUpPanel#395]
Hi guys,

First off all congratulations for your great work.

I'm using the AndroidSlidingUpPanel component in my project and I want to do a map interaction similar to the Google Maps.

I use 4 states of the component:
- Initially the component is in the HIDDEN state
- When a marker is selected it changes to COLLAPSED state
- If the user clicks on the DrawView goes to the ANCHORED state
- Finally if the user slides up goes to the EXPANDED state

The listeners we have available only tell us in what state the component is at the moment (after the transaction occurred). There's any way to know to which state the component is changing?
In order to performed the correspondent animations such as showing/hiding the action bar, centring the map, changing the map padding...

How can we handle the states changes before they happen to animate all simultaneously?

Thanks for your help.

**Comment by tokudu** [comment]
Look at the `slideOffset` param in the `onPanelSlide`. 
positive, increasing - expanding
positive, decreasing - collapsing
negative, increasing - collapsing
negative, decreasing - hiding
