### ISSUE TITLE
I Need fixed bottom margin at the end of screen

### ISSUE THREAD

**Issue by Hesamedin** [umano/AndroidSlidingUpPanel#396]
Hi,

I need to have fixed area (width: match_parent, height:50dp) at the end of screen and sliding area be on top of that.

I tried to do it like this in my activity:
```sh
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <FrameLayout
        android:id="@+id/tracking_frame"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginBottom="50dp"/>
    
    <View
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:layout_alignParentBottom="true"
        android:background="@color/red"/>
    
</RelativeLayout>
```

My fragment will be loaded in Framelayout. and It contains `com.sothree.slidinguppanel.SlidingUpPanelLayout` and two views inside itself,  based on your doc. Everything is fine but have no idea why `SlidingUpPanelLayout` is still covers the whole of screen since I put bottom 50dp margin.

Any advice would be appreciated. Thanks.

**Comment by tokudu** [comment]
This doesn't look like an issue with the panel, but rather your layout. Verify that the frame layout displays correctly without adding the sliding panel, but instead by setting it's background to red or smth.
