### ISSUE TITLE
Exact panelHeight is not respected

### ISSUE THREAD

**Issue by johnjohndoe** [umano/AndroidSlidingUpPanel#397]
I would like to update to the latest version of the library. After reading the [changelog](https://github.com/umano/AndroidSlidingUpPanel/releases/tag/3.0.0) and the updated README I still find it too difficult to guess what I have to change to meet the new library API. From what I read from the panel state class I can expand, anchor, hide, ... the panel via `.setPanelState(PanelState...)`. It is however not clear which state matches the former `.showPanel()` or `.hidePanel()` methods. I tried `Panel.EXPANDED` and `Panel.HIDDEN` but they behave different.

Therefore, I recommend you add some kind of **migration guide** for the major release. It can go into the wiki.

**Comment by tokudu** [comment]
I was under impression that it was clear that:
showPanel - EXPANDED
collapsePanel - COLLAPSED
hidePanel - HIDDEN

**Comment by johnjohndoe** [comment]
But `EXPANDED` does not do the same as `showPanel()`. `EXPANDED` opens the panel to the full screen height, `showPanel()` stopped at what is configured as the `panelHeigth`.

**Comment by tokudu** [comment]
I think you might be reporting a bug that panelHeight is not respected. I'll look into this.

**Comment by tokudu** [comment]
I just tested everything in the latest version of the library, and I can't reproduce your issue. Please reopen with specific repro steps (ideally in the example project).
