### ISSUE TITLE
How to set background of sliding up panel  to transparent

### ISSUE THREAD

**Issue by Jim-Chang** [umano/AndroidSlidingUpPanel#4]
I have tried to set    android:background="#00000000  in following code.

```
<com.sothree.slidinguppaneldemo.SlidingUpPanelLayout
    android:id="@+id/sliding_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#00000000 >
```

or set the same code on the layout (for example, RelativeLayout) whitch is inner SlidingUpPanelLayout, but the background is still white.
How do I write the code to make background transparent?

**Comment by sud007** [comment]
@dominicthomas worked for me as well but I can see some black color behind!

**Comment by DinhPhucTran** [comment]
You need to set umanoOverlay="true" to make sliding panel overlay main content.

**Comment by maximPetlyuk** [comment]
@dominicthomas, also worked for me. Thanks. But how can we add umanoFadeColor to all the first child, because when we make sliding layout transparent, part of the first child is under the umanoFadeColor attribute, and some part is not.

**Comment by GarvitKushwaha** [comment]
@DinhPhucTran  thanks bro..i just stucked from 3 days to resolve that bug
