### ISSUE TITLE
Stuck with PanelState.DRAGGING after device rotation

### ISSUE THREAD

**Issue by lupsaa** [umano/AndroidSlidingUpPanel#401]
Hello, recently I stumbled upon one issue with SlidingUpPanel.

I have the layout totally hidden by default and I open it from a floating action button using
slidingUpLayout.setPanelState(PanelState.EXPANDED);
Closing the layout is handled by the default drag action.

If by any chance the user is dragging the layout and a screen rotation is triggered, the layout will resume with its state equal to PanelState.DRAGGING.

This makes it impossible to open it again programmatically using setPanelState() as I've read through the method code because of: 
if (!isEnabled()
                || (!mFirstLayout && mSlideableView == null)
                || state == mSlideState
                || mSlideState == PanelState.DRAGGING) return;

A fix would be to disable storing PanelState as DRAGGING in onSaveInstanceState().

EDIT: I fixed this temporarilyextending the class and using reflection in onRestoreInstanceState()

**Comment by lacasrac** [comment]
It is a big issue. Is there any way to refresh view hierarchy after orientation changed or the soft keyboard is present?

**Comment by lacasrac** [comment]
I added this code to fix my problemes:

    @Override
    public void onConfigurationChanged(Configuration myConfig) {
        super.onConfigurationChanged(myConfig);
        int orient = getResources().getConfiguration().orientation;
        
        int newTop = 0;
 
        switch(orient) {
            case Configuration.ORIENTATION_LANDSCAPE:
            	newTop = mScreenWidth;
                break;
            case Configuration.ORIENTATION_PORTRAIT:
            	newTop = mScreenHeight;
                break;
            default:
        }
        
        refreshViews(newTop);
    }
    
    public void refreshViews(int newTop) {
        final int childCount = getChildCount();
        if (childCount != 2) {
            throw new IllegalStateException("Sliding up panel layout must have exactly 2 children!");
        }
        mMainView = getChildAt(0);
        mSlideableView = getChildAt(1);

        int defaultHeight = getHeight() - getPaddingBottom() - getPaddingTop() - mPanelHeight;
        LayoutParams lp = (LayoutParams)mMainView.getLayoutParams();
        
        if (mSlideOffset <= 0 && !mOverlayContent) {
            lp.height = mIsSlidingUp ? (newTop - getPaddingBottom()) : (getHeight() - getPaddingBottom() - mSlideableView.getMeasuredHeight() - newTop);
            mMainView.requestLayout();
        } 
        else if (lp.height != defaultHeight && !mOverlayContent) {
            lp.height = defaultHeight;
            mMainView.requestLayout();
        }    	
    }

**Comment by tokudu** [comment]
Fixed in https://github.com/umano/AndroidSlidingUpPanel/commit/3b773c78b108789de1f05adec8724f9dc43b3b0a
