### ISSUE TITLE
the main layout can not scroll to the right position

### ISSUE THREAD

**Issue by Mohism** [umano/AndroidSlidingUpPanel#402]
When I  setPanlestate( hide)   ,  the main layout can not scroll to the right position;But setPanlestate( anchor )  play good.  
  sothree:umanoPanelHeight="@dimen/umano_panel_height"
            sothree:umanoShadowHeight="4dp"
            sothree:umanoParalaxOffset="140dp"
            sothree:umanoFadeColor="@android:color/transparent"
            sothree:umanoInitialState="hidden"
            sothree:umanoDragView="@+id/dragView"

![qq 20150309121411](https://cloud.githubusercontent.com/assets/4285106/6549887/3ec2d774-c656-11e4-9446-27238e54a593.png)

**Comment by Mohism** [comment]
I comment  here and It works. Any Tips ?

**Comment by tokudu** [comment]
I'm not sure I understand the problem. which lines are you commenting out? Are you using the latest version of the panel?

**Comment by Mohism** [comment]
/*&& mSlideOffset >= 0*/
