### ISSUE TITLE
Collapse panel on main view touch?

### ISSUE THREAD

**Issue by kassim** [umano/AndroidSlidingUpPanel#403]
I need to be able to have the panel collapse when a touch event gets through to the main view.
As my main layout already consumes touch events (on of its children is a ViewPager) it means I must create a custom view and override the onInterceptTouch() method in order to have this behaviour.

Creating this custom view isn't a big chore but this behaviour seems like it may be a common need, and I was wondering what may be a good way of putting it into the library.

I was thinking perhaps having the mainLayout automatically inserted into a custom FrameLayout which overrides onInterceptTouch(), and the addition of a 'collapseOnMainViewTouch' boolean property. Or maybe a 'mainViewTouchBehavior' enum property which can collapse or go to anchor.

**Comment by tokudu** [comment]
Just call setPanelState on the panel when the mainView is clicked.
