### ISSUE TITLE
Starting sliding from the top of custom container

### ISSUE THREAD

**Issue by augustopicciani** [umano/AndroidSlidingUpPanel#405]
I need to start sliding panel from the top of a custom LinearLayout or RelativeLayout container positioned at the bottom of the screen. Is there a way to tell to SlidingPanel to start sliding from there and not from the bottom of the screen?

Thanks so much.

**Comment by tokudu** [comment]
Have you tried setting the 'gravity'?

**Comment by augustopicciani** [comment]
Hi,

I leaved the default setting gravity.
Can you make me a simple example ?

thanks.
Augusto

2015-03-12 17:39 GMT+01:00 Anton Lopyrev <notifications@github.com>:

**Comment by tokudu** [comment]
set ```layout_gravity="top"````
