### ISSUE TITLE
How to add a Button Below Sliding Up Panel

### ISSUE THREAD

**Issue by vivekkiran** [umano/AndroidSlidingUpPanel#408]
How can I add a button under the sliding up panel, the panel should be shown by default and under that I want to have a button which is static and width is match_parent, height is wrap _content and is  alignparentbottom. and next above it I want to have this sliding up panel.How do I do that?

**Comment by tokudu** [comment]
Im not sure I understand what you are trying to achieve. Please post a screenshot.
