### ISSUE TITLE
How to release scroll on any position, then avoid auto slide down or slide up?

### ISSUE THREAD

**Issue by gordonpro** [umano/AndroidSlidingUpPanel#409]
I want to slide up the panel at center of screen, then touch up. Then I want the view keep this position.

**Comment by tokudu** [comment]
have you trying defining an anchor point?

**Comment by gordonpro** [comment]
@tokudu just avoid avoid auto slide down or slide up when I release touch.

**Comment by gordonpro** [comment]
@tokudu Thanks! It works fine.
