### ISSUE TITLE
Take margin top into account for slidable view

### ISSUE THREAD

**Issue by thuytrinh** [umano/AndroidSlidingUpPanel#412]
First, thanks for the awesome lib!

How?
It'd be nice if the slidable view can be aware of its margin top so that we can achieve the following effect.
![untitled-1](https://cloud.githubusercontent.com/assets/1214816/6767918/5dbcc746-d080-11e4-825e-13118c48f2ad.gif)

There're many different ways to make it work but the simplest we found is to specify ```layout_marginTop``` for the slidable view with whatever dimen we expect:
```xml
<!-- SLIDING LAYOUT -->
<LinearLayout
    android:layout_marginTop="?actionBarSize"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:clickable="true"
    android:focusable="false"
    android:id="@+id/dragView">
```

Currently the slidable view always matches its parent (SlidingUpPanelLayout) height.

**Comment by hamzawct** [comment]
Hey , Amazing Lib.
It'd be nice if the slidable view can also be aware of its margin left and right as its now aware of margin top.
