### ISSUE TITLE
Main Layout margin does not have any effect. 

### ISSUE THREAD

**Issue by MoizAli** [umano/AndroidSlidingUpPanel#414]
My view is as follows:
 <com.sothree.slidinguppanel.SlidingUpPanelLayout xmlns:sothree="http://schemas.android.com/apk/res-auto"
        android:id="@+id/sliding_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="bottom"
        sothree:umanoDragView="@+id/dragView"
        sothree:umanoOverlay="false"
        sothree:umanoPanelHeight="68dp"
        sothree:umanoParalaxOffset="100dp"
        sothree:umanoShadowHeight="4dp"
        >

        <ListView
            android:id="@+id/list_songs"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:divider="@null"
            android:layout_marginLeft="8dp"
            android:layout_marginRight="8dp"/>

        <FrameLayout
            android:id="@+id/dragView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="center|top"></FrameLayout>

    </com.sothree.slidinguppanel.SlidingUpPanelLayout>

As you can see I am providing my mainlayout (listview) with margin left and margin right. But I see that it has not effect when I run the app.

**Comment by thuytrinh** [comment]
@MoizAli A workaround is to put the ListView inside a FrameLayout though it increases the depth of view hierarchy by 1.
