### ISSUE TITLE
setPanelState does not work until onMeasure is called

### ISSUE THREAD

**Issue by frostymarvelous** [umano/AndroidSlidingUpPanel#415]
I used to hide the panel based on some checks in `onStart` of my activity.

However, I just update and unfortunately, this doesn't work anymore. After about a couple of hours debugging (I thought it was my code I swear), I realized `setPanelState` won't work if the `mSlideableView` is null.

Unfortunately, it is until `onMeasure` is called where it is set using `this.mSlideableView = this.getChildAt(1);`

This wouldn't be an issue, but there is no proper way of detecting `onMeasure` without subclassing.
`onAttachedToWindow` looks promising, but it says it may be called before or after `onMeasure`.

I can't also find a suitable way to detect when the activity is fully drawn.

**Comment by jsa-nic** [comment]
I just came across this issue as well. The problem is compounded by the fact that onMeasure isn't tied to the Activity/Fragment life cycle (https://groups.google.com/forum/#!topic/android-developers/E4TZMz9LWvE), and more to the point it seems to be getting called after onResume() and therefore there is no easy way to set the initial state of the layout pragmatically besides setting mSlideableView's visibility, which just seems like the wrong way to go about setting the sliding panel's initial state.

**Comment by frostymarvelous** [comment]
@jsa-nic same solution I used. I check if it's the first run then set the slideableview's visibility to Gone. 

I hope it gets fixed. The views can be assigned during construction. Anyway, fingers crossed.

**Comment by tokudu** [comment]
Will get this fixed for the next release!

**Comment by tokudu** [comment]
I just tried this in the demo app. I use ```setPanelState(HIDDEN)``` in onResume method of the activity and everything works fine. Why is your mSlideableView null on Resume?

**Comment by frostymarvelous** [comment]
Closing this isn't fair. I took the time to debug and pinpoint the actual issue. It wasn't  just logged frivolously. 
As @jsa-nic mentioned, on measure isn't tied to the life cycle. It could be an Android version issue.

**Comment by sothree** [comment]
What Android version are you using using? Please provide repro steps and
I'd be happy to reopen this.

On Mon, Apr 20, 2015 at 10:36 PM, Froelich Stefan <notifications@github.com>
wrote:

> Closing this isn't fair. I took the time to debug and pinpoint the actual
> issue. It wasn't just logged frivolously.
> As @jsa-nic <https://github.com/jsa-nic> mentioned, on measure isn't tied
> to the life cycle. It could be an Android version issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umano/AndroidSlidingUpPanel/issues/415#issuecomment-94643969>
> .
>



-- 
*Anton Lopyrev*
Co-Founder & CTO • Umano
Follow me @tokudu <http://twitter.com/tokudu>
http://umano.me

**Comment by frostymarvelous** [comment]
I am running Android 5.0.1 on the S4 (TouchWiz).

I can't help with reproduction since I can't tell why it is happening except the cause.

As I said, moving `this.mSlideableView = this.getChildAt(1);` out of onMeasure will fix the issue.
