### ISSUE TITLE
Issue & suggestion.  Making the shadow clickable to prevent clicks underneath it & collapse the panel 

### ISSUE THREAD

**Issue by eugeneisrambo** [umano/AndroidSlidingUpPanel#419]
I am using Sliding up Panel to create a Bottom sheet from googles material guidelines.  How do I make the shadow clickable and collapse the panel.  http://www.google.com/design/spec/components/bottom-sheets.html

Here is my example:

Pre slide:

![device-2015-03-26-095538](https://cloud.githubusercontent.com/assets/7454787/6847797/7e82ec0e-d39f-11e4-9c36-045f201c2c3f.png)

After slide:

![device-2015-03-26-095616](https://cloud.githubusercontent.com/assets/7454787/6847801/88957388-d39f-11e4-97bc-c97cca30fbfd.png)

The items under the shadow are clickable. 

Suggestion is to make this library to meet googles bottom sheet guidelines. I use your library in many of my applications and enjoy it very much.

**Comment by tokudu** [comment]
The easiest ways to add your own clickable shadow view in the main content and show/hide in the onPanelSlide listener.
