### ISSUE TITLE
mLayout.setPanelState(EXPANDED) doesn't work in onResume()

### ISSUE THREAD

**Issue by jndefosse** [umano/AndroidSlidingUpPanel#422]
Hi,

I use your library before the update. I update the version but i have some problem.

In my app, in the onResume method, i used the fonction "expand()" for expand the slider and it was worked perfectly.

Since the update, the only way to expand is to use setPanelState but the slide doesn't expand with this method. If i click, the panel slide of course but I need the Slider expand.

I can't use the umanoInitialState in the xml because the user choose if the slider must be expand or must be collapse at the launch  of the app.

How can I fix it?

**Comment by tokudu** [comment]
I haven't been able to reproduce this in the sample app. Either way try running setPanelState inside of handler, let me know if that helps.

**Comment by jndefosse** [comment]
It's work with a delay:

                final Handler handler = new Handler();
                handler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        //Do something after 1000ms
                        Log.d(TAG, "Set Panel State : Expanded");
                        mLayout.setPanelState(EXPANDED);
                    }
                }, 1000);

**Comment by Mohism** [comment]
view.post  should be ok
