### ISSUE TITLE
Changing the visibility of child of SlidingUpPanel programmatically

### ISSUE THREAD

**Issue by bhuvneshvarma** [umano/AndroidSlidingUpPanel#426]
I have integrated SlidingUpPanelLayout.I want that the child layout of SlidingUpPanelLayout to be invisible by default and to be visible only whenuser clicks on an item in main layout.For that I set the visiblity of childlayout gone inside xml.But when on clicking on item in main layout i am trying to make child layout visible, it is not visible.However if i change the visiblity of child layout in xml to visible then its always visible(which i don't want).Why i am not able to change its visibility programmatically?

<com.sothree.slidinguppanel.SlidingUpPanelLayout
        xmlns:sothree="http://schemas.android.com/apk/res-auto"
        android:id="@+id/sliding_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="bottom"
        sothree:umanoPanelHeight="300dp"
        sothree:umanoShadowHeight="4dp"
        android:visibility="visible">

    <RelativeLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/maps"

        android:visibility="visible">
        <fragment
            android:id="@+id/location_map"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            class="com.google.android.gms.maps.MapFragment" />
        <ImageView
            android:id="@+id/btn_video"
            android:layout_width="40dp"
            android:layout_height="40dp"
            android:layout_marginLeft="5dp"
            android:src="@drawable/create_video_icon"
            android:layout_alignParentLeft="true" />
        <RelativeLayout
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:background="@color/search_bg_color"
            android:layout_marginRight="90dp"
            android:layout_toRightOf="@+id/btn_video"
            android:orientation="horizontal" >

            <ImageView
                android:id="@+id/btn_find"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:src="@drawable/search"

                android:layout_alignParentRight="true" />

            <EditText
                android:id="@+id/location"
                android:layout_width="fill_parent"
                android:layout_height="wrap_content"
                android:inputType="text"
                android:hint="@string/hnt_et_location"

                android:layout_toLeftOf="@id/btn_find" />

        </RelativeLayout>
    </RelativeLayout>
        <RelativeLayout
            xmlns:android="http://schemas.android.com/apk/res/android"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:id="@+id/panelslider"
            android:background="@color/black"
            android:visibility="gone">
            <GridView
                android:id="@+id/maps_video_gridview"
                android:layout_width="match_parent"
                android:layout_height="match_parent"

                android:layout_marginLeft="10dp"
                android:layout_marginRight="10dp"
                android:layout_marginTop="10dp"
                android:drawSelectorOnTop="true"
                android:gravity="center"
                android:numColumns="2"
                android:stretchMode="columnWidth"
                android:verticalSpacing="5dp"
                android:visibility="visible" />
        </RelativeLayout>
    </com.sothree.slidinguppanel.SlidingUpPanelLayout>

**Comment by DEV-NEP** [comment]
@bkjbkjbnkj687698698 did you solve this??
