### ISSUE TITLE
Show view below SlidingUpPanel?

### ISSUE THREAD

**Issue by levuphuong** [umano/AndroidSlidingUpPanel#428]
<com.sothree.slidinguppanel.SlidingUpPanelLayout
    xmlns:sothree="http://schemas.android.com/apk/res-auto"
    android:id="@+id/sliding_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="bottom"
    sothree:umanoPanelHeight="68dp"
    sothree:umanoShadowHeight="4dp">

    <TextView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center"
        android:text="Main Content"
        android:textSize="16sp" />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center|top"
        android:text="The Awesome Sliding Up Panel"
        android:textSize="16sp" />
</com.sothree.slidinguppanel.SlidingUpPanelLayout>
    <TextView
        android:layout_above ="@+id/sliding_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:text="only test"
        android:layout_alignParentBottom="true"
        android:textSize="16sp" />

Text view will show in bottom but SlidingUpPanelLayout make overlays it
Please help me set SlidingUpPanelLayout above text view.
Thanks so much.

**Comment by tokudu** [comment]
Not sure what you are trying to achieve. Post a screenshot?

**Comment by levuphuong** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:ads="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".myActivity" >

    <com.google.android.gms.ads.AdView
        android:id="@+id/adView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@+id/drawer_layout"
        ads:adSize="BANNER"
        ads:adUnitId="my pin code" >
    </com.google.android.gms.ads.AdView>

    <android.support.v4.widget.DrawerLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/drawer_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent" >

        <com.sothree.slidinguppanel.SlidingUpPanelLayout
            xmlns:sothree="http://schemas.android.com/apk/res-auto"
            android:id="@+id/sliding_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            umanoClipPanel="true"
            android:gravity="bottom"
            sothree:umanoDragView="@+id/dragView"
            sothree:umanoPanelHeight="68dp"
            sothree:umanoParalaxOffset="100dp"
            sothree:umanoShadowHeight="4dp" >

            <FrameLayout
                android:id="@+id/frame_main"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

            <FrameLayout
                android:id="@+id/frame_slider"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:background="@drawable/boder" />
        </com.sothree.slidinguppanel.SlidingUpPanelLayout>

        <ExpandableListView
            android:id="@+id/left_drawer"
            android:layout_width="240dp"
            android:layout_height="match_parent"
            android:layout_gravity="left"
            android:background="#ffffff"
            android:divider="@android:color/transparent"
            android:dividerHeight="1dp"
            android:groupIndicator="@null" />
    </android.support.v4.widget.DrawerLayout>

</RelativeLayout>


Hey this is my xml
i want to show ads below com.sothree.slidinguppanel.SlidingUpPanelLayout
but it show "Not enough space to show ad. Needs 320x50 dp, but only has 360x0 dp."

thanks

**Comment by tokudu** [comment]
Something is wrong with your layout. Your code doesn't show what the main layout is. You should probably be using a vertical linear layout.

**Comment by levuphuong** [comment]
OK
i change to 
xmlns:sothree="http://schemas.android.com/apk/res-auto"
android:id="@+id/sliding_layout"
android:layout_width="match_parent"
android:layout_height="0dp"
android:weight =1
android:gravity="bottom"
sothree:umanoPanelHeight="68dp"
sothree:umanoShadowHeight="4dp">

it completely works 
Thanks
