### ISSUE TITLE
SlidingUpPanel Tap issue

### ISSUE THREAD

**Issue by bhuvneshvarma** [umano/AndroidSlidingUpPanel#429]
I am using [SlidingUpPanel][1].I have kept AnchorPoint as 0.63.I want when my sliding panel is in anchor state and user taps on it it should go to expanded state rather than hidden state.Similarly whem my panel is in expanded state and user taps on it it should go to anchor state rather than hidden state.How could i do that?
I tried using below code but with this no click or swipe event works.Through log i checked tht its not going inside onSingleTapConfirmed() or onDoubleTap()-

    slidingPaneLayout.setOnTouchListener(new View.OnTouchListener() {
        @Override
        public boolean onTouch(View v, MotionEvent event) {
       detector.onTouchEvent(event);
           return true;
        }
    });
    
    class GestureTap extends GestureDetector.SimpleOnGestureListener {
        @Override
        public boolean onDoubleTap(MotionEvent e) {
            Log.i("onDoubleTap :", "" + e.getAction());
            return true;
        }
    
        @Override
        public boolean onSingleTapConfirmed(MotionEvent e) {
            Log.i("onSingleTap :", "" + e.getAction());
            return true;
        }
    }

  [1]: https://github.com/umano/AndroidSlidingUpPanel

**Comment by tokudu** [comment]
set your own OnClickListener on the drag view and do your own dispatching based on the panel state.
