### ISSUE TITLE
match_parent but hides some infos in ANCHORED mode

### ISSUE THREAD

**Issue by hannesa2** [umano/AndroidSlidingUpPanel#433]
I've a fragment like 

    <?xml version="1.0" encoding="utf-8"?>
    <LinearLayout xmlns:custom="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/map_main"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:focusableInTouchMode="true"
        android:orientation="vertical"
        tools:ignore="ContentDescription" >

        <com.sothree.slidinguppanel.SlidingUpPanelLayout
            xmlns:sothree="http://schemas.android.com/apk/res-auto"
            android:id="@+id/sliding_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="bottom"
            sothree:umanoAnchorPoint="0.5"
            sothree:umanoDragView="@+id/map_sliding_layout"
            sothree:umanoInitialState="hidden"
            sothree:umanoPanelHeight="?android:attr/listPreferredItemHeight"
            sothree:umanoParalaxOffset="150dp"
            sothree:umanoShadowHeight="4dp" >
        <RelativeLayout...>

        <LinearLayout
            android:id="@+id/map_sliding_drawer"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical" >

            <TextView
                android:id="@+id/map_poi_detail"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

            <ListView
                android:id="@+id/list_container"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="horizontal" >
            </ListView>
        </LinearLayout>
    </com.sothree.slidinguppanel.SlidingUpPanelLayout>

but in ANCHORED mode I see just a part from ListView and miss the red area and can't scroll to it till I full expand the slider
![slider](https://cloud.githubusercontent.com/assets/3314607/7115816/2fd57800-e1ec-11e4-81f2-5156d5f5e142.png)

Do you have any hint how to solve this, or what's wrong here ?

Thank you !

**Comment by tokudu** [comment]
The sliding panel doesn't handle listviews well in the sliding view. There is a feature request for it. https://github.com/umano/AndroidSlidingUpPanel/issues/116
