### ISSUE TITLE
Keyboard overlapping input fields after drag view is first expanded

### ISSUE THREAD

**Issue by fgoncalves** [umano/AndroidSlidingUpPanel#434]
Hi,

First let me thank you for the work on the library, it's quite impressive.

I've been working and experimenting with it and I found that when the drag view contains a scrollable view (ListView, ScrollView, etc.), input fields get hidden by the soft keyboard. Let me elaborate on this.

[Here](https://github.com/umano/AndroidSlidingUpPanel/compare/master...fgoncalves:overlaping-on-soft-keyboard) you'll find some of my experiments with the demo app. I basically changed the main layout to contain an edit text at the bottom and the drag view to contain a list view.

While installing this app, I found that when the text view gains focus the main window resizes while the soft keyboard pops up. In general this means the user sees what he's typing.

However, after I slide the drag view up and down, clicking on the text view would no longer resize the main window correctly. Basically the user could not see anymore what he was typing.

In the same diff I provided in this post you can see I changed something in the class ``com.sothree.slidinguppanel.SlidingUpPanelLayout``. I found out that this will measure the view like it's suppose to and resize it as I intended. My problem here is that I'm not an expert in android layout manipulation and for sure not an expert in the Sliding Up Panel library you made. Therefore I thought I'd ask you about this and would like to know what you think about it? Do you foresee any issues with this fix?

Thanks a lot for the support!

**Comment by tokudu** [comment]
Where is your TextView located? In the main layout?
 
I will look into this. I hope to release better support for scrollable views in the sliding panel soon.

**Comment by fgoncalves** [comment]
Sorry about that. I meant EditText. Yes it's in the main layout - [here](https://github.com/umano/AndroidSlidingUpPanel/compare/master...fgoncalves:overlaping-on-soft-keyboard#diff-ee5b2ce3ac0f5d8b65655f3a582fd6fdR40)

**Comment by tokudu** [comment]
I think your issue should be fixed now (related to https://github.com/umano/AndroidSlidingUpPanel/issues/356). Please reopen if you are still having issues.
