### ISSUE TITLE
Why to support API level 8?

### ISSUE THREAD

**Issue by alex-shpak** [umano/AndroidSlidingUpPanel#435]
Hi.
I'm wondering, why you decided to support API starting from level 8. It looks like nineoldandroids is required only to translate view and can be dropped with support versions starting from API 10.

Looks like for now android 2.2 and below is about 0.5% of devices.

The reason why I'm asking is that I wanted to use this lib, but I don't want to include nineoldandroid as dependency.

**Comment by tokudu** [comment]
At the time of writing it made sense to support level 8. Either way, you should be using proguard so that unused dependencies don't impact your final binary size.
