### ISSUE TITLE
Sroll issue in gridview  

### ISSUE THREAD

**Issue by bhuvneshvarma** [umano/AndroidSlidingUpPanel#436]
My SlidingUpPanel consists of GridView.When the sliding up panel is in expandable state then if i swipe up and down on gridview then i want gridview to scroll up and down.But sometimes wht hapeens is that the swipe action is taken by SlidingUp panel and hence on down swiping the panel closes and on up swiping there is no response as panel is already expanded.How can i do it in such a way that panel only responds to swipe action only when user swipe on top above gridview else swipe action should be taken by gridview only?

**Comment by tokudu** [comment]
Please see work arounds in https://github.com/umano/AndroidSlidingUpPanel/issues/116
