### ISSUE TITLE
Issue working with FragmentStatePagerAdapter

### ISSUE THREAD

**Issue by nJackx** [umano/AndroidSlidingUpPanel#437]
I'm having a problem using SlidingUpPanel and FragmentStatePagerAdapter.

I have 3 fragments in the pager: the first two with a sliding panel (one a fragment and one a hardcoded layout) and the third without it.
When I had a pager with just two fragments the panel were working perfectly fine. Now that I've added a third they are not working anymore.

At first the fragment are created correctly, but when I swipe all the way to the third and then come back the panel get messed up.
Basically the panel that used to be on the first fragment is now on the panel of the second one, the hardcoded layout of the second panel is now gone and the panel of the first fragment is empty.

The main content of all fragment is still correct and behaves as intended.

My code to select the fragment is:

    public Fragment getItem(int i) {
        Fragment fragment = null;
        switch (i) {
            case 0:
                fragment = new MatchListFragment();
                break;
            case 1:
                fragment = new StreamFragment();
                break;
            case 2:
                fragment = new PendingMatches();
                break;
            default:
                break;
        }
        return fragment;
    }

Layout of first fragment (MatchListFragment):

    <?xml version="1.0" encoding="utf-8"?>
    <com.sothree.slidinguppanel.SlidingUpPanelLayout           

    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:sothree="http://schemas.android.com/apk/res-auto"
    android:id="@+id/sliding_panel"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="top"
    android:orientation="vertical"
    sothree:umanoOverlay="false"
    sothree:umanoPanelHeight="58dp"
    sothree:umanoShadowHeight="4dp">

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/container_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/white"
        android:gravity="center"
        android:orientation="vertical"
        android:visibility="visible">

       CONTENT

    </RelativeLayout>

    <FrameLayout
        android:id="@+id/scrollable_panel"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</com.sothree.slidinguppanel.SlidingUpPanelLayout>

Layout of second fragment (StreamFragment)

    <?xml version="1.0" encoding="utf-8"?>
    <com.sothree.slidinguppanel.SlidingUpPanelLayout    
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:sothree="http://schemas.android.com/apk/res-auto"
    android:id="@+id/stream_panel"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white"
    android:gravity="top"
    android:orientation="vertical"
    sothree:umanoOverlay="false"
    sothree:umanoPanelHeight="18dp"
    sothree:umanoShadowHeight="4dp">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <ListView
            android:id="@+id/log_list"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:clickable="false"
            android:divider="@drawable/material_divider"
            android:dividerHeight="1dp"
            android:visibility="visible" />

    </LinearLayout>

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/scrollable_panel"
        android:layout_width="match_parent"
        android:layout_height="88dp"
        android:background="@color/white"
        android:gravity="center">

        <ImageView
            android:id="@+id/icon"
            android:layout_width="match_parent"
            android:layout_height="20dp"
            android:layout_alignParentBottom="true"
            android:background="@color/light_gray" />

        <ImageView
            android:layout_width="25dp"
            android:layout_height="10dp"
            android:layout_alignParentBottom="true"
            android:layout_centerHorizontal="true"
            android:layout_margin="5dp"
            android:src="@drawable/green_pill" />

        <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:app="http://schemas.android.com/apk/res-auto"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_above="@id/icon"
            android:layout_alignParentTop="true"
            android:orientation="horizontal">

            <com.coffeestrap.android.Widgets.IconAndText
                android:id="@+id/profile_switch"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_margin="4dp"
                android:layout_weight="1"
                app:resource="@drawable/ic_profile_icon"
                app:undertext="New" />

            <com.coffeestrap.android.Widgets.IconAndText
                android:id="@+id/talk_switch"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_margin="4dp"
                android:layout_weight="1"
                app:resource="@drawable/ic_talk_icon"
                app:undertext="Learning" />

            <com.coffeestrap.android.Widgets.IconAndText
                android:id="@+id/conversation_switch"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_margin="4dp"
                android:layout_weight="1"
                app:resource="@drawable/ic_conversation_icon"
                app:undertext="Teaching" />

            <com.coffeestrap.android.Widgets.IconAndText
                android:id="@+id/all_switch"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_margin="4dp"
                android:layout_weight="1"
                app:resource="@drawable/ic_all_icon"
                app:undertext="All" />

        </LinearLayout>

    </RelativeLayout>

</com.sothree.slidinguppanel.SlidingUpPanelLayout>

After discussing with one of my colleagues I think it might be caused by the fact that the PageAdapter inflates the layout of the screen adjacent to the one currently displayed.
It could be that, going from the third screen to the second, while inflaing the layout of the first screen it's panel get mistakenly substituted to the correct one, due to the fact stated above.

This theory is also supported by the fact that if I add  a couple of empty fragment before the first one and, after triggering the panel switch, I swipe all the way to the left and then again to the right, the panels are correctly placed.

See image below 
![example](https://cloud.githubusercontent.com/assets/6040180/7232407/abf079aa-e77b-11e4-8c3a-05efaad5cebe.png)

**Comment by tokudu** [comment]
The sliding panel layout does not do any sort of fragment manipulation, so it's likely that the issue is related to your fragment management code.

**Comment by nJackx** [comment]
After further investigation I found out it was due to a bad interaction between the pageadapter and my code.
