### ISSUE TITLE
View visibility issue in android 5.1

### ISSUE THREAD

**Issue by alimehmood10pearls** [umano/AndroidSlidingUpPanel#439]
Hello,

I've been encountering a strange issue after upgrading my nexus 5 to android 5.1, the views inside sliding panel flickers (i.e. showing/hiding). It was working fine on prior versions including android 5.0. Any help would be appreciated. Thank you.

Regards.

**Comment by tokudu** [comment]
I can't reproduce this in the sample app (using nexus 5 with 5.1). Please provide repro steps for the sample app.
