### ISSUE TITLE
SetPanelState Not Working when called from panel slide listener

### ISSUE THREAD

**Issue by Yolobro** [umano/AndroidSlidingUpPanel#442]
mLayout.setPanelSlideListener(new PanelSlideListener() {
            @Override
            public void onPanelSlide(View panel, float slideOffset) {
                Log.i(TAG, "onPanelSlide, offset " + slideOffset);
            }

            @Override
            public void onPanelExpanded(View panel) {
                Log.i(TAG, "onPanelExpanded");

            }

            @Override
            public void onPanelCollapsed(View panel) {
                Log.i(TAG, "onPanelCollapsed");
                mLayout.setPanelState(PanelState.HIDDEN);
            }

            @Override
            public void onPanelAnchored(View panel) {
                Log.i(TAG, "onPanelAnchored");
            }

            @Override
            public void onPanelHidden(View panel) {
                Log.i(TAG, "onPanelHidden");
            }
        });

Used this code but this doesn't work.

**Comment by tokudu** [comment]
Call it on a handler.
