### ISSUE TITLE
Remove Parallex effect from First child of Sliding panel

### ISSUE THREAD

**Issue by zelin** [umano/AndroidSlidingUpPanel#448]
Hi, i am adding a MapFragment as first child and a listView as a second child. I do not want my MapFragment to be compressed or reduce in size, instead its height should match entire Sliding Panel main Holder height. 

Right now when sliding panel is up the the map size is reduced, sliding panel behaving like linear layout. How can i remove this effect

**Comment by tokudu** [comment]
set `umanoParalaxOffset` to zero
