### ISSUE TITLE
Compatibility with windowDrawsSystemBarBackgrounds

### ISSUE THREAD

**Issue by mroczis** [umano/AndroidSlidingUpPanel#449]
Hey,
"android:windowDrawsSystemBarBackgrounds" set to "true" results that everything may be drawn under status bar on Lollipop and above. Sliding with height of match_parent fully expands under statusbar and part of it is overlayed with status bar.
Is there any way to set layout_marginTop to sliding panel to statusBar height? I just want apply this rule for expanded panel, not main layout. I tired to do it in panel's layout or programmatically but nothing worked.

Sliding up...
![screenshot_2015-05-04-18-44-42](https://cloud.githubusercontent.com/assets/12201961/7457572/c69ace32-f28d-11e4-977a-419cab81be5b.png)

Final position
![screenshot_2015-05-04-18-44-24](https://cloud.githubusercontent.com/assets/12201961/7457571/c6977930-f28d-11e4-8855-73d986d39db8.png)

**Comment by zzn2** [comment]
Hi,

Have you tried [android:fitsSystemWindows](http://developer.android.com/reference/android/view/View.html#attr_android:fitsSystemWindows)  to the expanded panel?

**Comment by WonShaw** [comment]
try this
        ((ViewGroup) activity.findViewById(android.R.id.content)).getChildAt(0)
            .setPadding(0, ViewUtils.getStatusBarHeight(activity) , 0, 0);



    public static int getStatusBarHeight(Context context) { 
        int result = 0;
        int resourceId = context.getResources().getIdentifier("status_bar_height", "dimen", "android");
        if (resourceId > 0) {
            result = context.getResources().getDimensionPixelSize(resourceId);
        } 
        return result;
    }

**Comment by tokudu** [comment]
Please reopen if still having issues.
