### ISSUE TITLE
umanoInitialState set to expanded does not parallax the panel

### ISSUE THREAD

**Issue by YuriHeupa** [umano/AndroidSlidingUpPanel#453]
In the xml i set the following params to my SlidingUpPanelLayout:

umanoParalaxOffset="150dp"
umanoInitialState="expanded"

The panel start expanded but the main view has no parallax, i need to touch the drag panel to parallax the main view, is there any workaround?

**Comment by tokudu** [comment]
Seems to be fixed in master
