### ISSUE TITLE
Lock at an anchor point

### ISSUE THREAD

**Issue by jbruckne** [umano/AndroidSlidingUpPanel#455]
Is there a way to lock at an anchor point. For example, if I set an anchor point at right below my toolbar, can I make it so the user can't slide it past that point?

**Comment by tokudu** [comment]
have you tried setSlidingEnabled?

**Comment by jbruckne** [comment]
Thats what I tried at first but when I disable it at a certain point how do I know when to renable it when they swipe down. I don't want it to lock both ways, I just want to set the top of the second panel at a certain point. Does that make sense?

**Comment by tokudu** [comment]
Then use custom android:layout_height on the panel.
