### ISSUE TITLE
Sliding Panel Overlay

### ISSUE THREAD

**Issue by Abhiseshan** [umano/AndroidSlidingUpPanel#459]
Is there a way to add a layer (full width and height) over the sliding panel? 
For example a floating action button that is over both the sliding panel and the underlying view that is independant of both the views and their behaviors.

**Comment by tokudu** [comment]
Have a look here: https://github.com/umano/AndroidSlidingUpPanel/pull/362

**Comment by subodh-malgonde** [comment]
I did this simply by changing my activity's xml layout. Works well.

Instead of having the SlidingUpPanelLayout as the root element, put it inside a RelativeLayout. Add your floating action button below the SlidingUpPanelLayout inside the RelativeLayout so that the button's z index is greater than the SlidingUpPanelLayout. Now use the layout_above or layout_below attributes to specify the relative position of the two elements.

Example:

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.sothree.slidinguppanel.SlidingUpPanelLayout
            xmlns:sothree="http://schemas.android.com/apk/res-auto"
            android:id="@+id/sliding_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="bottom"
            android:layout_above="@+id/floating_action_button"
            sothree:umanoPanelHeight="68dp" // can be set to 0dp if you want the floation action button to completely overlay the panel
            sothree:umanoShadowHeight="4dp">

           
           <TextView
               android:layout_width="match_parent"
               android:layout_height="match_parent"
               android:gravity="center"
               android:text="Main Content"
               android:textSize="16sp" />

        
        <TextView
               android:layout_width="match_parent"
               android:layout_height="match_parent"
               android:gravity="center|top"
               android:text="The Awesome Sliding Up Panel"
               android:textSize="16sp" />
        </com.sothree.slidinguppanel.SlidingUpPanelLayout>

        <Button
                android:id="@+id/floating_action_button"
                android:layout_width="match_parent"
                android:layout_height="@dimen/sliding_panel_height"  //should be equal to the panel's height if you want the button to completely overlay the collapsed panel
                android:layout_alignParentBottom="true" />
    <RelativeLayout>
