### ISSUE TITLE
Difficulty to slide to anchor point by swiping down from expanded state

### ISSUE THREAD

**Issue by DeepakSenapati** [umano/AndroidSlidingUpPanel#460]
It seems that it is really difficult to swipe down and reach the anchor point when the slideUpPanel is in expanded state. Even with slowest of swipes, it moves completely down. As I see in google map, there is a clear distinction between the velocity needed to swipe till the anchor point and swipe completely down. What changes will have to be made to achieve something similar using this library?

**Comment by tokudu** [comment]
I will look into for the next release.

**Comment by davidluuAU** [comment]
I have submitted a PR which should fix this https://github.com/umano/AndroidSlidingUpPanel/pull/510
