### ISSUE TITLE
Problems using the library. What I am missing?

### ISSUE THREAD

**Issue by badwolfy2003** [umano/AndroidSlidingUpPanel#464]
Hello!

I'm getting this errors when using the library:

The method expandPanel() is undefined for the type SlidingUpPanelLayout
The method collapsePanel() is undefined for the type SlidingUpPanelLayout

I'm trying to use some code found in another post:

    protected static final int EXPAND_PANEL = 0x101;
    private static SlidingUpPanelLayout mLayout;
    private ImageView img;
    
    static Handler myHandler = new Handler() {
        public void handleMessage(Message msg) {
            switch (msg.what) {
                case TestActivity.EXPAND_PANEL:
                    mLayout.expandPanel();
                    break;
            }
            super.handleMessage(msg);
        }
    };
    
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.test);
		
		mLayout = (SlidingUpPanelLayout) findViewById(R.id.sliding_layout);
        mLayout.setEnabled(false); // disable
        //new Thread(new myThread()).start();

        img = (ImageView) findViewById(R.id.image);
        
        Button b1 = (Button) findViewById(R.id.buttonImage);
        
        b1.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                img.setVisibility(View.VISIBLE);

                Message message = new Message();
                message.what = TestActivity.EXPAND_PANEL;
                myHandler.sendMessage(message);
            }
        });
        
        Button b2 = (Button) findViewById(R.id.buttonNoImage);
        
        b2.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                img.setVisibility(View.GONE);

                Message message = new Message();
                message.what = TestActivity.EXPAND_PANEL;
                myHandler.sendMessage(message);
            }
        });
        
        Button b3 = (Button) findViewById(R.id.buttonCollapse);
        
        b3.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                mLayout.collapsePanel();
            }
        });
    }

    @Override
    public void onBackPressed() {
        if (mLayout != null && mLayout.isPanelExpanded() || mLayout.isPanelAnchored()) {
            mLayout.collapsePanel();
        } else {
            super.onBackPressed();
        }
    }

**Comment by akhtarali786** [comment]
The method expandPanel() is undefined for the type SlidingUpPanelLayout
The method collapsePanel() is undefined for the type SlidingUpPanelLayout

**Comment by tokudu** [comment]
use `setPanelState`
