### ISSUE TITLE
Trying to ignore touch events everywhere but the handle for the sliding panel

### ISSUE THREAD

**Issue by mielet** [umano/AndroidSlidingUpPanel#465]
I want the only way to expand / collapse the sliding panel to be from a touch event on the "handle" of the sliding panel (the part that is exposed on the main layout while the sliding panel is collapsed) is this a feature of the library?

**Comment by tokudu** [comment]
set `setTouchEnabled(false)` and then put a clickable view in the panel, which would collapse and expand the panel manually through setPanelState

**Comment by mielet** [comment]
Preferably I would still like the user to be able to drag the panel, with this fix it becomes more of a click to open/close. Is this possible?

**Comment by mielet** [comment]
For some reason through my multiple readings of the documentation i missed the .setDragView function available to a sliding panel layout. I set the handle to the sliding panel to the dragview and that disabled the entire panel reading input for sliding the entire panel
