### ISSUE TITLE
Overshoot animation on panel expand

### ISSUE THREAD

**Issue by subodh-malgonde** [umano/AndroidSlidingUpPanel#466]
Is there a way to add a overshoot animation when the panel expands?

Something like in the gif below:

![unnamed](https://cloud.githubusercontent.com/assets/5463437/7897099/5fc36e0c-06ed-11e5-85b4-e7d228e8af02.gif)

**Comment by tokudu** [comment]
Not currently, feel free to submit a PR if you get it to work.

**Comment by subodh-malgonde** [comment]
Awesome! Thanks.
