### ISSUE TITLE
Sometimes setPanelState(HIDDEN) doesn't work

### ISSUE THREAD

**Issue by AkshayChordiya** [umano/AndroidSlidingUpPanel#470]
Hi,

I'm using this library since a long time, I upgraded to 3.0 which broke the use of 
`public hidePanel();
public showPanel()`

but then I used the ```setPanelState()``` method which works fine, including ```HIDDEN``` state but at some position(in code) it doesn't work. I confirmed it by getting immediately after calling ```setPanelState()``` if panel is hidden which came ```false``` which means panel is not hidden even after calling ```setPanelState```

I have no idea why this is happening. 
I hope you check this out.

**Comment by tokudu** [comment]
This is fixed in master. Will be available in 3.1 soon.
