### ISSUE TITLE
Can't use ListView in Sliding Panel Layout

### ISSUE THREAD

**Issue by 228313** [umano/AndroidSlidingUpPanel#472]
Following is my xml layout:
![x1](https://cloud.githubusercontent.com/assets/12810459/8053484/c536c036-0eae-11e5-887c-163eb69653c4.PNG)

Please Note: The ids of the views have been deliberately wiped.
Whenever I run this code I am getting the following exception:
![e1](https://cloud.githubusercontent.com/assets/12810459/8053520/1b0ead66-0eaf-11e5-86ab-b70dcf246021.PNG)

Also setting the ItemClickListener instead of the OnClickListener on the ListView in the Activity file dos not help.
Can you please help me out with this one.

**Comment by erumhannan** [comment]
any success how u reolsved ? @228313

**Comment by 228313** [comment]
Hi, I got this to work with the following updated xml code:

![img1](https://cloud.githubusercontent.com/assets/12810459/8404248/13f15bea-1e69-11e5-8310-de8494361030.PNG)
![img2](https://cloud.githubusercontent.com/assets/12810459/8404254/1e2dcbe8-1e69-11e5-8184-cd7afd135656.PNG)
![img3](https://cloud.githubusercontent.com/assets/12810459/8404257/239eca6e-1e69-11e5-93b9-80e700f27083.PNG)

**Comment by 228313** [comment]
Hi,

I have replied on GitHub.

On 29 June 2015 at 14:02, erumhannan <notifications@github.com> wrote:

> any success how u reolsved ? @228313 <https://github.com/228313>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/umano/AndroidSlidingUpPanel/issues/472#issuecomment-116522704>
> .
>



-- 
Warm Wishes,
Parimal
