### ISSUE TITLE
SlidingUpPanel with full screen activity

### ISSUE THREAD

**Issue by technohowl** [umano/AndroidSlidingUpPanel#473]
Hi,

I have a requirement to show full screen activity.
My app theme is set as
```
 <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/myPrimaryColor</item>
        <item name="colorPrimaryDark">@color/myPrimaryDarkColor</item>
        <item name="colorAccent">@color/myAccentColor</item>
        <item name="android:windowNoTitle">true</item>
        <item name="windowNoTitle">true</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowContentOverlay">@null</item>
        <item name="android:windowActionBarOverlay">true</item>
        <item name="windowActionBar">false</item>
    </style>
```
When I set the activity to full screen the slidingup panel layout do not take this into consideration. 

![screen shot 2015-06-09 at 3 08 24 pm](https://cloud.githubusercontent.com/assets/568958/8054875/78c8fd58-0eb9-11e5-8988-6305c3e835a7.png)

This is how the layout looks like. How do I remove the status bar space in Sliding up layout?

**Comment by bardigolriz** [comment]
Did you figure out how to work around this? I'm running into a similar issue.

**Comment by iadcialim** [comment]
@technohowl Can share how did u cover the status bar too?
