### ISSUE TITLE
Set Anchor point problem ?

### ISSUE THREAD

**Issue by piiyo** [umano/AndroidSlidingUpPanel#475]
Hey first of all awesome libary !
There is one question. Open the panel to 30% of the screen then when I press a button it goes to the anchor point (50%) works awesome with set panelstate.anchored ... but now I want to set a new anchor point when the panel i's at 50% to 70%  and call again set panel state anchored . But it doesn't bring me to 70% the panel stays at 50%. Doesn't thus work ?

**Comment by hauseja3** [comment]
I'm facing the same issue, could be the anchor point settings dynamic?

**Comment by tokudu** [comment]
Will look into that for the next release

**Comment by tokudu** [comment]
Fixed in https://github.com/umano/AndroidSlidingUpPanel/commit/b27e95987a3e0d4abfcfd35a4c7fbfbf386c3f63

Will be released with 3.3.
