### ISSUE TITLE
Open drawer on a button click

### ISSUE THREAD

**Issue by supareek** [umano/AndroidSlidingUpPanel#484]
hi, I want to open the main drawer on a button click instead of sliding up. Can this be achieved by some workaround? Thanks!!

**Comment by TroniPM** [comment]
Declare in somewhere "reachable"
SlidingUpPanelLayout = slidingPanel;

And just put something like this in "onclick" method:
slidingPanel.setPanelState(SlidingUpPanelLayout.PanelState.COLLAPSED);
or 
slidingPanel.setPanelState(SlidingUpPanelLayout.PanelState.EXPANDED);

Should do the trick
