### ISSUE TITLE
Can't set panelState in code

### ISSUE THREAD

**Issue by 12520054** [umano/AndroidSlidingUpPanel#487]
Hi there,
First, I set the panel state in xml:  sothree:umanoInitialState="hidden"
Then in onCreate function of Activity I have this code:
if( mSlidingUpLayout != null &&
                    (mSlidingUpLayout.getPanelState() == SlidingUpPanelLayout.PanelState.ANCHORED ||
                    mSlidingUpLayout.getPanelState() == SlidingUpPanelLayout.PanelState.COLLAPSED ||
                    mSlidingUpLayout.getPanelState() == SlidingUpPanelLayout.PanelState.HIDDEN))
            {
                mSlidingUpLayout.setPanelState(SlidingUpPanelLayout.PanelState.EXPANDED);
                Toast.makeText(getApplicationContext(), mSlidingUpLayout.getPanelState().toString() , Toast.LENGTH_SHORT).show();
            }
The panel still hidden, and the text of toast still Hidden?
I don't know how to fix it. Can you help me to solve it?
My thanks,

**Comment by tokudu** [comment]
Try running it inside of a handler.

**Comment by 12520054** [comment]
I don't know what are you recommending?

**Comment by tokudu** [comment]
Example here http://stackoverflow.com/questions/1921514/how-to-run-a-runnable-thread-in-android
