### ISSUE TITLE
OnExpanded isn't always called

### ISSUE THREAD

**Issue by FireFly3000** [umano/AndroidSlidingUpPanel#491]
Even though the panel always expands, the onExpanded event isn't always fired.

**Comment by tokudu** [comment]
Can you please provide repro steps.

**Comment by FireFly3000** [comment]
What I have is an XML file like the following and. The content of the sliding content varies in the height. Sometimes the height of the sliding content becomes too heigh and sometimes too small. The content of the sliding content is set just before I call 
slidingPanel.setPanelState(SlidingUpPanelLayout.PanelState.EXPANDED);to show the panel programatically. I hope this helped otherwise just ask again.
 
 
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/BackgroundGray">
    <TextView
        android:id="@+id/selectPrinterMapHeader"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        style="@style/textHeader"
        android:text="@string/_map"
        android:layout_alignParentTop="true"/>
    <Button
        android:id="@+id/selectPrinterMapButtonCancel"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:text="@string/back"
        style="@style/buttonLargeWhite"
        android:onClick="returnFromMapView"
        android:layout_margin="0dp"/>
    <View
        android:id="@+id/mapViewDivider"
        android:layout_width="match_parent"
        style="@style/horizontalLine"
        android:layout_above="@id/selectPrinterMapButtonCancel"/>
    <com.sothree.slidinguppanel.SlidingUpPanelLayout
        xmlns:sothree="http://schemas.android.com/apk/res-auto"
        android:id="@+id/map_sliding_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@id/mapViewDivider"
        android:layout_below="@id/selectPrinterMapHeader"
        android:gravity="bottom"
        sothree:umanoPanelHeight="0dp"
        sothree:umanoShadowHeight="4dp"
        sothree:umanoParalaxOffset="0dp"
        sothree:umanoDragView="@+id/dragView"
        sothree:umanoFadeColor="#40000000"
        sothree:umanoOverlay="false"
        sothree:umanoFlingVelocity="0"
        sothree:umanoInitialState="collapsed"
        android:background="@color/White">
        
        <fragment
            android:id="@+id/selectPrinterMapMap"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:name="com.google.android.gms.maps.MapFragment" />
        
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            android:clickable="true"
            android:focusable="false"
            android:id="@+id/dragView"
            android:gravity="bottom"
            android:paddingRight="@dimen/table_padding_right">
            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="horizontal"
                android:layout_gravity="center"
                android:gravity="center"
                android:background="@color/White">
                <TextView android:id="@+id/infoViewTitle"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:textAllCaps="true"
                    style="@style/textNormalTitle"
                    android:layout_marginLeft="0dp"
                    android:layout_marginStart="0dp"
                    android:gravity="center"
                    android:layout_marginTop="0dp"
                    android:layout_weight="5" />
                <ImageButton
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:src="@drawable/navigation_sign"
                    android:layout_margin="5dp"
                    android:background="#00FFFFFF"
                    android:onClick="startNavigation"
                    android:layout_gravity="center_vertical"
                    android:layout_weight="1"/>
            </LinearLayout>
            <View
                android:layout_width="match_parent"
                style="@style/horizontalLine"/>
            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical"
                android:background="@color/White">
                <TextView android:id="@+id/infoViewLocationTitle"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    style="@style/textNormalTitle"
                    android:text="@string/location"/>
                <TextView android:id="@+id/infoViewAddress"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    style="@style/textNormal"/>
                <TextView android:id="@+id/infoViewPrinterLocation"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    style="@style/textNormal"/>
                <TextView android:id="@+id/infoViewDistance"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    style="@style/textNormal"/>
                <TextView android:id="@+id/infoViewOpeningHoursTitle"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    style="@style/textNormalTitle"
                    android:text="@string/access_hours"/>
                <TextView android:id="@+id/infoViewOpeningHoursDesc"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    style="@style/textNormal"/>
                <TextView android:id="@+id/infoViewCapabilitiesTitle"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    style="@style/textNormalTitle"
                    android:text="@string/capabilities"/>
                <TextView android:id="@+id/infoViewCapabilitiesDuplex"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    style="@style/textNormal"/>
                <TextView android:id="@+id/infoViewCapabilitiesColor"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    style="@style/textNormal"/>
                <TextView android:id="@+id/infoViewPriceTitle"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    style="@style/textNormalTitle"
                    android:text="@string/price"/>
                <TextView android:id="@+id/infoViewPriceBlackWhite"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    style="@style/textNormal"/>
                <TextView android:id="@+id/infoViewPriceColour"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    style="@style/textNormal"/>
                <TextView android:id="@+id/infoViewPriceStartPrice"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    style="@style/textNormal"/>
                <TextView android:id="@+id/infoViewPriceIncludes"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    style="@style/textNormal"/>
            </LinearLayout>
        </LinearLayout>
    </com.sothree.slidinguppanel.SlidingUpPanelLayout>
</RelativeLayout>

**Comment by tokudu** [comment]
Try calling setPanelState inside of a handler, it should fix your issues. Since you are changing the content of the panel you need to wait for relayout before calling setPanelState.

**Comment by FireFly3000** [comment]
Thanks, it worked to putting it into a worker.
