### ISSUE TITLE
Hidden State in library

### ISSUE THREAD

**Issue by Transformat** [umano/AndroidSlidingUpPanel#494]
if(this.mSlideState == SlidingUpPanelLayout.PanelState.HIDDEN) {
                        this.mSlideableView.setVisibility(0);
                        this.requestLayout();
                    }

The visibility during the HIDDEN is set to visible. So using state HIDDEN actually makes it visible.

**Comment by tokudu** [comment]
Not sure what you mean here, please reopen with a better description.
