### ISSUE TITLE
How to change the velocity of Panel

### ISSUE THREAD

**Issue by 12520054** [umano/AndroidSlidingUpPanel#495]
Hi there,
I don't know how to change or reduce the flyingvelocity of Panel.
When it Hidden and I change State to Expand or when it Expand I change to Hidden. It's move to fast.
I have change the         sothree:umanoFlingVelocity="50" but It make no slowly effect.
Thanks for any help.

**Comment by Bierrot** [comment]
Same here

**Comment by tokudu** [comment]
Dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/365

**Comment by abhiank209** [comment]
@tokudu Has this feature been implemented yet?
