### ISSUE TITLE
Problem changing dragview

### ISSUE THREAD

**Issue by hoseinit** [umano/AndroidSlidingUpPanel#498]
Hi
I have a Dragview defined in the main xml as the second child of the slidinguppanel.
I want to change the dragview as it's EXPANDED.
Here what I have done:
I have another layout defined in Layout folder and set a listnerer to change it but npt yet successful: 

mLayout.setPanelSlideListener(new SlidingUpPanelLayout.PanelSlideListener() {
            @Override
            public void onPanelSlide(View panel, float slideOffset) {
                Log.i(TAG, "onPanelSlide, offset " + slideOffset);
                if (slideOffset <= 0) {
                    mLayout.setDragView(R.id.dragView);
                }

                // If the panel is not fully expanded set the whole panel as dragview
                else if (slideOffset > 0) {
                    mLayout.setDragView(R.id.dragViewexpanded);
                }
            }
           @Override
            public void onPanelExpanded(View panel) {
                Log.i(TAG, "onPanelExpanded");
                mLayout.setDragView(R.id.dragViewexpanded);
            }

**Comment by hoseinit** [comment]
It is obligated to only change Fragments when we want to change the Layout ?

**Comment by tokudu** [comment]
What behavior do you see?

**Comment by hoseinit** [comment]
I want to have two completely different layout for dragview when expanded and collapsed

**Comment by hoseinit** [comment]
The only way works for me is to Replace a different Fragment upon SlideStateListener state changes.

**Comment by tokudu** [comment]
Try executing the setDragView code inside of a Runnable posted on a handler.

**Comment by hoseinit** [comment]
Can you explain more? 
Is it possible to have two xml LAYOUTs for a dragview by executing the setDragView inside of a Runnable posted on a handler ?
or should I continue calling and replacing fragments onslidestatechangelistener ?

**Comment by tokudu** [comment]
onslidestatechangelistener is the right solution. 
```
Handler handler=new Handler();
Runnable r=new Runnable() {
    public void run() {
        tv.append("Hello World");               
    }
};
handler.post(r);
```

**Comment by hoseinit** [comment]
I follow this approach, seems fine to me:
 mLayout.setPanelSlideListener(new SlidingUpPanelLayout.PanelSlideListener() {
            @Override
            public void onPanelExpanded(View panel) {
                Log.i(TAG, "onPanelExpanded");
                getSupportFragmentManager()
                        .beginTransaction()
                        .replace(R.id.dragViewholder, new DragViewExpanded())
                        .commit();
            }

            @Override
            public void onPanelCollapsed(View panel) {
                Log.i(TAG, "onPanelCollapsed");
                getSupportFragmentManager()
                        .beginTransaction()
                        .replace(R.id.dragViewholder, new DragView())
                        .commit();
            }
