### ISSUE TITLE
Child views get clicked when moving the panel

### ISSUE THREAD

**Issue by PhpXp** [umano/AndroidSlidingUpPanel#504]
Hi!

Can you please change SlidingUpPanelLayout.java:966 from

    up.setAction(MotionEvent.ACTION_UP);

to

    up.setAction(MotionEvent.ACTION_CANCEL);

so the child views don't get clicked when moving the panel.

Thanks.

**Comment by tokudu** [comment]
Thanks! Fixed in https://github.com/umano/AndroidSlidingUpPanel/commit/e9ae5b089653e2414e1ff47c42d813b23cc3d6fb
