### ISSUE TITLE
Can't scroll up when specifying `umanoScrollableView`

### ISSUE THREAD

**Issue by barbeau** [umano/AndroidSlidingUpPanel#506]
@tokudu Thanks for implementing scrollable views (https://github.com/umano/AndroidSlidingUpPanel/issues/116)!

Is this expected to work for ListFragments too?

I'm seeing the following behavior with AndroidSlidingUpPanel v3.1.0:
https://youtu.be/0N3b7yK1WVo

Pulling up on the list (scrolling down) scrolls perfectly, but pulling down on the list always pulls the header down too, which means I can't scroll back up the list.

Code for the app is here:
https://github.com/OneBusAway/onebusaway-android/tree/develop

Main layout that includes `SlidingUpPanelLayout`:
https://github.com/OneBusAway/onebusaway-android/blob/develop/onebusaway-android/src/main/res/layout/main.xml#L29

ListFragment is added programmatically to the layout for the sliding panel.  I'm specifying `                sothree:umanoScrollableView="@+id/slidingPanel"`, where `"@+id/slidingPanel"` is the layout that contains the sliding panel contents.

**Comment by tokudu** [comment]
sothree:umanoScrollableView should be your listview.

**Comment by barbeau** [comment]
Ah, of course.  For anyone else wanting to do something similar where you don't have access to the XML id of the listview, I ended up solving this by removing the `sothree:umanoScrollableView` XML attribute and setting the scrollable view programmatically, using a listener for when the ListView in the ListFragment is initialized.

So, I have a callback interface in my ArrivalsListFragment:

~~~
public interface Listener {

        /**
         * Called when the ListView has been created
         *
         * @param listView the ListView that was just created
         */
        void onListViewCreated(ListView listView);
}
~~~

...and I make the callback to any registered listeners in ArrivalsListFragment.onResume:

~~~
    @Override
    public void onResume() {
        // Notify listener that ListView is now created
        if (mListener != null) {
            mListener.onListViewCreated(getListView());
        }
~~~

In my `HomeActivity` where I have my `mSlidingPanel` (which uses `main.xml` linked to above), I'm creating the `ArrivalsListFragment` programmatically, and registering as a listener with `ArrivalsListFragment` for `onListViewCreated()` callbacks, so I can set the scrollable view as soon as its initialized:

~~~
@Override
    public void onListViewCreated(ListView listView) {
        // Set the scrollable view in the sliding panel
        mSlidingPanel.setScrollableView(listView);
    }
~~~

And that works perfectly!

Thanks again @tokudu!
