### ISSUE TITLE
create a fragment within the slide up panel and make it close on slide up?

### ISSUE THREAD

**Issue by RaffiOhanian** [umano/AndroidSlidingUpPanel#508]
Im try to implement a photo viewer just liike facebooks, and i think using the slideuppanel i should be able to achieve that . can you help me on that?

**Comment by tokudu** [comment]
It might be an overkill to use the sliding up panel for something like that. Consider writing a custom component and using DragViewHelper for your dragging needs.

**Comment by RaffiOhanian** [comment]
ok.  Thanks for the reply !
