### ISSUE TITLE
Clicking on an anchored panel should expand, not collapse.

### ISSUE THREAD

**Issue by cody-young-move** [umano/AndroidSlidingUpPanel#511]
I would argue the behavior of clicking on an anchored panel should be expanding not collapsing. Perhaps this could be available as an option?

**Comment by tokudu** [comment]
Yeah, let's make it an option - because you could argue both ways.

**Comment by tokudu** [comment]
Actually, you can already modify the behavior, but assigning your own `onClickListener` for the drag view. So closing this.

**Comment by cody-young-move** [comment]
Oh of course. I didn't see a way to do that through the panel api itself, but as you mention I can just set my own onclick handler on the view.
