### ISSUE TITLE
Make first layout in sliding panel not movable after sliding the panel

### ISSUE THREAD

**Issue by JenyaKirmiza** [umano/AndroidSlidingUpPanel#515]
I tried to use setOverlay, but still the content is moving top.

     <com.sothree.slidinguppanel.SlidingUpPanelLayout xmlns:sothree="http://schemas.android.com/apk/res-auto"
        android:id="@+id/sliding_layout"
        android:layout_below="@id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="bottom"
        sothree:umanoDragView="@+id/dragView"
        sothree:umanoOverlay="true"
        sothree:umanoPanelHeight="68dp"
        sothree:umanoParalaxOffset="100dp"
        sothree:umanoScrollableView="@+id/list"
        sothree:umanoShadowHeight="4dp">
    .....
    </com.sothree.slidinguppanel.SlidingUpPanelLayout>

**Comment by azizimusa** [comment]
sothree:umanoOverlay="false"

**Comment by JenyaKirmiza** [comment]
@azizimusa  thanks
