### ISSUE TITLE
Recyclerview support let's the items be clicked

### ISSUE THREAD

**Issue by khusravsh** [umano/AndroidSlidingUpPanel#517]
The recent support for RecyclerView (and other scroll views) is what I've been waiting for very long - thanks for it. There's one small issue, though - when you scroll quickly and release the finger on a clickable item within the scrolling item, it gets clicked.

**Comment by tokudu** [comment]
I believe I fixed that issue in the latest release. Can you please confirm.

**Comment by khusravsh** [comment]
Looks fixed, thank you!
