### ISSUE TITLE
Difficult page swiping when using ViewPager with scrollable View

### ISSUE THREAD

**Issue by TR4Android** [umano/AndroidSlidingUpPanel#518]
First of all thanks a lot for implementing the scrollable view support. It's amazing and almost feels magical :smiley:. I have one small issue though:

When using a `ViewPager` and fragments that contain scrollable views (which get set via `setScrollableView()` in the `setPrimaryItem(...)` method of the `PagerAdapter`), the `SlidingUpPanelLayout` often takes over the touch events and cancels the horizontal swipe which makes it difficult to switch between pages.
See [here](https://github.com/TR4Android/AndroidSlidingUpPanel/tree/viewpager-demo) for a demo that shows this. Just try swiping the `ViewPager` a few times and you'll notice it. When commenting out [this line](https://github.com/TR4Android/AndroidSlidingUpPanel/blob/viewpager-demo/demo/src/com/sothree/slidinguppanel/demo/DemoActivity.java#L244) with the `setScrollableView()` this issue isn't present.

**Comment by ngsilverman** [comment]
+1

**Comment by vipinhelloindia** [comment]
+1 

<ViewPager><<Fragment1>><<<AndrodSlidingUpPanel>>><<<<ChildOneViewPager>>><<<<ChildTwoSlidingView>>>>

**Comment by vsahu1986** [comment]
+1

**Comment by mjp-goto10** [comment]
Until there's a fix I'm using a workaround like this: http://dallasgutauckis.com/2013/04/30/android-putting-a-viewpager-inside-a-listview/

It mentions a ListView but it applies to any case where a ViewPager is fighting over touch events with a scrolling view.

**Comment by tokudu** [comment]
I will look into this shortly

**Comment by vsahu1986** [comment]
Thanks

**Comment by TR4Android** [comment]
@tokudu Thanks for the update!

**Comment by pmurph0** [comment]
+1

**Comment by sebastianmarschall** [comment]
+1

**Comment by tokudu** [comment]
Hey @TR4Android, can you just follow the work around linked in http://dallasgutauckis.com/2013/04/30/android-putting-a-viewpager-inside-a-listview/.  And do:
```
            @Override
            public void onPageScrollStateChanged(int state) {
                // All of this is to inhibit any scrollable container from consuming our touch events as the user is changing pages
                if (mPreviousState == ViewPager.SCROLL_STATE_IDLE) {
                    if (state == ViewPager.SCROLL_STATE_DRAGGING) {
                        mSlidingLayout.setTouchEnabled(false);
                    }
                } else {
                    if (state == ViewPager.SCROLL_STATE_IDLE || state == ViewPager.SCROLL_STATE_SETTLING) {
                        mSlidingLayout.setTouchEnabled(true);
                    }
                }

                mPreviousState = state;
            }
```

**Comment by tokudu** [comment]
Please reopen if this doesn't work.
