### ISSUE TITLE
Close panel when touching the shadow

### ISSUE THREAD

**Issue by duduBaiao** [umano/AndroidSlidingUpPanel#519]
Is it possible to close the panel when the user touches the shadow?

**Comment by dany-kun** [comment]
One workaround could be to override dispatchTouchEvent in your activity/fragment view and check if the event is on the shadow or not

**Comment by duduBaiao** [comment]
Thanks Dany!

To be honest, I was surprised that this is not the default behavior.

When we use an anchor point, is very intuitive try to touch at the shadow to close the panel.

For now, I removed the shadow. It seems that this way is less confusing.

**Comment by tokudu** [comment]
Dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/476

**Comment by tokudu** [comment]
FIxed in https://github.com/umano/AndroidSlidingUpPanel/commit/b69a6bf77e7c9e702815893f85b21703141701e2

Will be released in 3.3.0
