### ISSUE TITLE
Do not push up main content #question

### ISSUE THREAD

**Issue by mountaingoat99** [umano/AndroidSlidingUpPanel#522]
I am looking to get the overlay panel to pull up, but keep the main content in the same spot. When reading the "Caveats..." is says to set the SetOverlayed or umanoOverlay, but that does not seem to be working for me when I do it in the layout or in the code behind. I am missing something else?

mlayout = (SlidingUpPanelLayout)findViewById(R.id.sliding_layout);
mlayout.setOverlayed(true);

**Comment by TR4Android** [comment]
@mountaingoat99 The `umanoOverlay` attribute does something different than what you want: it controls whether or not the main layout extends below the panel (in collapsed state).
What you probably have is a parallax offset. You'll have to check whether you have the `umanoParallaxOffset` set or use `setParallaxOffset()`. Delete those and you should be fine.

**Comment by mountaingoat99** [comment]
@TR4Android Perfect. Just what I needed. Thanks!
