### ISSUE TITLE
Panel won't expand since 3.1.0

### ISSUE THREAD

**Issue by bubu333gh** [umano/AndroidSlidingUpPanel#524]
Everything works fine with 3.0.0 but if I rebuild the project without changing anything except

compile 'com.sothree.slidinguppanel:library:3.0.0'

to

compile 'com.sothree.slidinguppanel:library:3.1.x'

the panel stops listening to click and drag events.

<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.sothree.slidinguppanel.SlidingUpPanelLayout
        xmlns:sothree="http://schemas.android.com/apk/res-auto"
        android:id="@+id/slidingPanel"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="bottom"
        sothree:umanoOverlay="true"
        sothree:umanoFadeColor="@color/black_system_default_alpha"
        sothree:umanoPanelHeight="@dimen/movie_details_sliding_panel_hidden_height"
        sothree:umanoShadowHeight="@dimen/movie_details_shadow_size">

        <ScrollView
            android:id="@+id/posterScrollView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:paddingBottom="@dimen/movie_details_sliding_panel_hidden_height"
            android:scrollbars="none">

            <FrameLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <ImageView
                    android:id="@+id/posterTransitioner"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:adjustViewBounds="true"
                    android:background="@color/white_paper"
                    android:transitionName="posterTransition"/>

                <ProgressBar
                    android:id="@+id/progressBar"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:paddingBottom="@dimen/movie_details_progress_bar_bottom_padding"
                    style="?android:attr/progressBarStyle"
                    android:layout_gravity="center"
                    android:visibility="gone"/>

                <ImageView
                    android:id="@+id/posterPlaceholder"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:adjustViewBounds="true"
                    android:src="@drawable/poster_placeholder"/>

                <ImageView
                    android:id="@+id/poster"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:adjustViewBounds="true"
                    android:scaleType="fitCenter"/>

            </FrameLayout>

        </ScrollView>

        <LinearLayout
            android:id="@+id/slidingPanelLayout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:padding="@dimen/movie_details_margin_small"
            android:background="@color/white_paper"
            android:orientation="vertical"
            android:transitionName="titleAndInfoLayoutTransition">

            <TextView
                android:id="@+id/title"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginBottom="@dimen/movie_details_margin_tiny"
                android:maxLines="2"
                android:ellipsize="end"
                android:textSize="@dimen/text_size_medium"
                android:textColor="@color/black"
                android:text="Title"
                android:transitionName="titleTransition"/>

            <TextView
                android:id="@+id/year"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginBottom="@dimen/movie_details_margin_tiny"
                android:lines="1"
                android:textSize="@dimen/text_size_tiny"
                android:transitionName="yearTransition"
                android:text="(year)"/>

            <TextView
                android:id="@+id/duration"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginBottom="@dimen/movie_details_margin_large"
                android:lines="1"
                android:textSize="@dimen/text_size_tiny"
                android:transitionName="durationTransition"
                android:text="xxx minutes"/>

            <Button
                android:id="@+id/trailerButton"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginBottom="@dimen/movie_details_margin_large"
                android:paddingLeft="@dimen/button_padding"
                android:paddingRight="@dimen/button_padding"
                android:background="@drawable/button_primary_light"
                android:text="@string/trailer_button"
                android:textColor="@drawable/button_text_color_white"
                android:textSize="@dimen/text_size_small"/>

            <TextView
                android:id="@+id/director"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginBottom="@dimen/movie_details_margin_tiny"
                android:textSize="@dimen/text_size_tiny"
                android:text="Director:"/>

            <TextView
                android:id="@+id/cast"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginBottom="@dimen/movie_details_margin_small"
                android:textSize="@dimen/text_size_tiny"
                android:text="Cast:"/>

            <TextView
                android:id="@+id/description"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:textSize="@dimen/text_size_small"
                android:text="Description"/>

        </LinearLayout>

    </com.sothree.slidinguppanel.SlidingUpPanelLayout>

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/playButton"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentRight="true"
        android:layout_alignParentEnd="true"
        android:layout_alignParentBottom="true"
        android:layout_marginRight="@dimen/movie_details_play_button_margin"
        android:layout_marginEnd="@dimen/movie_details_play_button_margin"
        android:layout_marginBottom="@dimen/movie_details_play_button_margin_bottom_closed"
        android:clickable="true"
        android:src="@drawable/fab_play"
        app:backgroundTint="@color/secondary"
        app:rippleColor="@color/black_system_default_alpha"
        app:borderWidth="0dp"
        app:elevation="@dimen/floating_action_button_elevation"/>

</RelativeLayout>

**Comment by neoteknic** [comment]
My panel at the bottom just disapeared with 3.1.1... , reverted to 3

**Comment by tokudu** [comment]
3.1.1 is not fully compatible with 3.0.0. Please refer to the sample app.
