### ISSUE TITLE
ListView in ViewPager not scrollable and disable expansion above anchor

### ISSUE THREAD

**Issue by zelin** [umano/AndroidSlidingUpPanel#531]
I have a slidingPanel defined as

        mSlidingUpPanelLayout.setPanelHeight(mapHeight); // you can use different height here
        mSlidingUpPanelLayout.setScrollableView(mPager, mapHeight);
        mSlidingUpPanelLayout.setAnchorPoint(0.7f);
        mSlidingUpPanelLayout.setPanelSlideListener(this);

When i scroll above anchor point it automatically expands itself. Is there any way i can disable this expansion, infact i don't want it to move before anchor point. I can drag to collapse once its on anchor but not expandable.

Secondly i have a listView in pager. Once its on anchor, i can't make listView scrollable.

**Comment by tokudu** [comment]
Fixed in master. Use `layout_weight` attribute
