### ISSUE TITLE
Disable click collapse and only allow drag

### ISSUE THREAD

**Issue by RonEskinder** [umano/AndroidSlidingUpPanel#532]
I need help on how to disable the Click to collapse/expand, and only allow the user to drag the panel. Any ideas?

**Comment by niqueco** [comment]
This is a hack but works:

```java
			SlidingUpPanelLayout supl = (SlidingUpPanelLayout)getActivity().findViewById(R.id.sliding_layout);
			supl.getChildAt(1).setOnClickListener(null);
```
It has to be done after "onCreate" (when the clicklistener has already been installed) or it won't work.

**Comment by tokudu** [comment]
`setDragView(null)`

**Comment by nisan-abeywickrama** [comment]
> This is a hack but works:
> 
> ```java
>             SlidingUpPanelLayout supl = (SlidingUpPanelLayout)getActivity().findViewById(R.id.sliding_layout);
>             supl.getChildAt(1).setOnClickListener(null);
> ```
> 
> It has to be done after "onCreate" (when the clicklistener has already been installed) or it won't work.

This doesnt work for me
