### ISSUE TITLE
Occasional NullPointerException in SavedState.writeToParcel

### ISSUE THREAD

**Issue by alwaysthecritic** [umano/AndroidSlidingUpPanel#536]
We're seeing occasional crashes in the field (thanks Crashlytics) in writeToParcel(). I don't have a local repro for this.

    com.sothree.slidinguppanel.SlidingUpPanelLayout$SavedState.writeToParcel (SlidingUpPanelLayout.java:1504)
    android.os.Parcel.writeParcelable (Parcel.java:1292)

The line of code in question is:

    out.writeString(mSlideState.toString());

Presumably mSlideState is null for some reason. Perhaps someone very familiar with the code might see how this could happen? I'm not in a good position to "thought-debug" it unfortunately.

**Comment by soarcn** [comment]
Turn on "Don't keep activies" in Developer options will help to reproduce this defects
if null or empty object pattern should be applied to protect the code

**Comment by mrsasha** [comment]
I second that, I also see these occasionally (17 crashes on 18k installs - not many, but I don't have that many crashes):
```Fatal Exception: java.lang.NullPointerException in
com.sothree.slidinguppanel.SlidingUpPanelLayout$SavedState.writeToParcel (SlidingUpPanelLayout.java:1505)
android.os.Parcel.writeParcelable (Parcel.java:1290)```

**Comment by plastiv** [comment]
Faced this as well. Started to happen after update 3.0.0 to 3.1.0.
While this could be an indication of illegal state issue, we can at least add null check. See #584

**Comment by tokudu** [comment]
Fixed in master

**Comment by ngheungyu** [comment]
hi @tokudu 

I've been seeing rare crash on 3.2.0...I'm upgrading to 3.3.0 to see if it happens too. Here's the log for your investigation. Thanks

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.sothree.slidinguppanel.SlidingUpPanelLayout$PanelState.toString()' on a null object reference
at com.sothree.slidinguppanel.SlidingUpPanelLayout$SavedState.writeToParcel(SlidingUpPanelLayout.java:1505)
```
