### ISSUE TITLE
How to programmatically scroll 'SlidingLayout' by scrolling 'MainContaint' ?

### ISSUE THREAD

**Issue by AzimAnsari** [umano/AndroidSlidingUpPanel#537]
![capture](https://cloud.githubusercontent.com/assets/10906758/9786795/79db6af4-57da-11e5-91a5-a6f0530f6870.PNG)

Currently I can scroll comment section to insert comments. I want to enable image scroll also to open comment section.

Whenever I scroll image up comment section should respond to scroll events.

I have added up/down scroll gestures to image but how can I pass these events to SlidingLayout?

**Comment by vsahu1986** [comment]
+1

**Comment by vsahu1986** [comment]
seems similar to 
#540

**Comment by vipinhelloindia** [comment]
+1

**Comment by tokudu** [comment]
Dupe of https://github.com/umano/AndroidSlidingUpPanel/issues/529

**Comment by vipinhelloindia** [comment]
Hi @tokudu  #537 is closed in 3.3.0  milestone ..
