### ISSUE TITLE
Improper resize if keyboard is open when panel collapses

### ISSUE THREAD

**Issue by danPixel** [umano/AndroidSlidingUpPanel#545]
If the keyboard is open when you collapse the panel. Then you close the keyboard. The main content is incorrectly sized leaving a space between the top of the collapsed panel and the bottom of the main content.

![near me bug2](https://cloud.githubusercontent.com/assets/11277851/10200351/0ed19542-6763-11e5-9c86-33f701b35191.png)
![near me bug](https://cloud.githubusercontent.com/assets/11277851/10200350/0ecf3a86-6763-11e5-835c-a787ac2778e6.png)

**Comment by ylyc** [comment]
@danPixel  I'm experiencing the same thing.  Do you have a fix by any chance?
Can't just replace adjustResize with adjustPan as it causes other issue in my case.

**Comment by roger-sala-forcemanager** [comment]
@danPixel @ylyc could you fix that? Do you have any option?
Thanks! I've tried to "invalidate" the Google Maps in onConfigurationChange but the bug stills happen.

**Comment by danPixel** [comment]
I didn't figure anything out in the time I alotted for it so I just disallowed the keyboard to be open when the sliding panel was open. It worked okay for my needs but obviously won't for everyone.

**Comment by silviahisham** [comment]
I have the same problem, did anyone find a solution for this?

**Comment by charlesannic** [comment]
I think we should use onKeyPreIme on the focused EditText to detect the onPressedBack and know when the keyboard closes.
At this point we should find a way to inform the SlidingUpPanel that the view must be resized. (When opening the SlidingUpPanel again, it updates the size of the view. I tried to open and immediately close the panel without success ...)
Sorry if my english is bad, I hope I was understood and helpful!

**Comment by charlesannic** [comment]
I just find a solution to this problem. The only constraint is that the umanoPanelHeight must be of 0. If you find a solution to the latter problem tell me!
Hoping that my code can help: https://github.com/charlesannic/BottomSheet

**Comment by Lighted** [comment]
I met this problem too,when the soft keyboard showing,if we unfold the slidingpanel,there will be a big empty space on the screen after the soft keyboard dismiss,any one have good idea?

**Comment by tokudu** [comment]
Fixed in https://github.com/umano/AndroidSlidingUpPanel/commit/58efe1bb658fba4481df12decc328041e35b9534
