### ISSUE TITLE
Can not make a event click on View after Sliding UP

### ISSUE THREAD

**Issue by thanhsontube** [umano/AndroidSlidingUpPanel#547]
Hi team, 
I have updated from 3.0.0 -> 3.1.1
I'v got a problem:
Couldn't click TextView/Button on The view After Sliding up.

Please have a look on it. I have to down it to 3.0.0 again. thanks

**Comment by IHNEL** [comment]
Need to know solution too.

**Comment by rabyunghwa** [comment]
I'm using 3.2.0 and it works just fine. Did you set the onClickListener inside onCreate() or onPanelExpanded()?

**Comment by pamartineza** [comment]
I'm experiencing same Issue, I have a recyclerview inside the sliding layout and with 3.0.2 I can't click list items, reverting to 3.0.0 fixes problem

**Comment by tokudu** [comment]
Please update to the latest version.

**Comment by pamartineza** [comment]
I meant the bug is happening in 3.2.0, can't see there is a newer release

**Comment by tokudu** [comment]
Can you create a sample project with an issue? I can't seem to reproduce it.

**Comment by pamartineza** [comment]
I fixed it adding the recyclerview id to sothree:umanoScrollableView attribute

**Comment by tokudu** [comment]
Please reopen if still having issues.
