### ISSUE TITLE
Panel collapse when scrolling down listview.

### ISSUE THREAD

**Issue by mujeebulhasan** [umano/AndroidSlidingUpPanel#549]
I have a listview in second layout of SlidingUpPanel.
When listview is showing first item and I scroll down panel collapses.
I want panel not to collapse when touching listview.

I tried to setDragView 
(as mentioned in README.md) but its not working.

File with slidingUpPanel =>

<com.sothree.slidinguppanel.SlidingUpPanelLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/sliding_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="bottom"
        sothree:umanoPanelHeight="50dp"
        sothree:umanoDragView="@+id/npRl1"
        sothree:umanoScrollableView="@+id/dragListView">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <include
                android:id="@+id/toolbar_actionbar"
                layout="@layout/toolbar_default"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

            <FrameLayout
                android:id="@+id/container"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:clickable="true" />
        </LinearLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <include layout="@layout/now_playing"></include>

        </LinearLayout>

    </com.sothree.slidinguppanel.SlidingUpPanelLayout>

now_playing.xml =>

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:CircleProgressView="http://schemas.android.com/apk/res-auto"
    xmlns:dslv="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <RelativeLayout
        android:id="@+id/npRl1"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:background="#f00">

        <ImageView
            android:id="@+id/imageView"
            android:layout_width="40dp"
            android:layout_height="40dp"
            android:layout_centerVertical="true"
            android:layout_marginLeft="10dp"
            android:src="@drawable/avatar" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerVertical="true"
            android:layout_marginLeft="10dp"
            android:layout_toRightOf="@+id/imageView"
            android:singleLine="true"
            android:text="Song title" />

        <ImageButton
            android:id="@+id/queue_play"
            android:layout_width="40dp"
            android:layout_height="40dp"
            android:layout_alignParentEnd="true"
            android:layout_alignParentRight="true"
            android:layout_centerVertical="true"
            android:layout_marginRight="10dp"
            android:background="#f00"
            android:src="@drawable/ic_play_arrow_black_36dp" />

    </RelativeLayout>

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clickable="true"
        android:layout_below="@+id/npRl1">

        <RelativeLayout
            android:id="@+id/np_albumArt"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_above="@+id/np_controls"
            android:visibility="gone">
            

            <ImageView
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:scaleType="centerCrop"
                android:src="@drawable/avatar" />

        </RelativeLayout>

        <RelativeLayout
            android:id="@+id/np_queue"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_above="@+id/np_controls"
            android:visibility="visible">
            

            <ListView
                android:id="@+id/dragListView"
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

            </ListView>

        </RelativeLayout>

        <RelativeLayout
            android:id="@+id/np_controls"
            android:layout_width="match_parent"
            android:layout_height="100dp"
            android:layout_alignParentBottom="true"
            android:background="#f00">

            <ImageButton
                android:id="@+id/prev"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentLeft="true"
                android:layout_centerVertical="true"
                android:layout_toLeftOf="@+id/tv1"
                android:background="#f00"
                android:src="@drawable/ic_skip_previous_black_36dp" />

            <TextView
                android:id="@+id/tv1"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerVertical="true"
                android:layout_marginRight="5dp"
                android:layout_toLeftOf="@+id/playLayout"
                android:text="00:00" />

            <RelativeLayout
                android:id="@+id/playLayout"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerInParent="true">

                <at.grabner.circleprogress.CircleProgressView
                    android:id="@+id/circleView"
                    android:layout_width="90dp"
                    android:layout_height="90dp"
                    CircleProgressView:barColor="#000"
                    CircleProgressView:barWidth="5dp"
                    CircleProgressView:contourSize="0dp"
                    CircleProgressView:maxValue="100"
                    CircleProgressView:rimColor="#fff"
                    CircleProgressView:rimWidth="5dp"
                    CircleProgressView:seekMode="true"
                    CircleProgressView:textColor="#00796B"
                    CircleProgressView:unit="%"
                    CircleProgressView:unitColor="#000" />

                <ImageButton
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerInParent="true"
                    android:background="#f00"
                    android:src="@drawable/ic_play_arrow_black_36dp" />

            </RelativeLayout>

            <TextView
                android:id="@+id/tv2"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerVertical="true"
                android:layout_marginLeft="5dp"
                android:layout_toRightOf="@+id/playLayout"
                android:text="4:33" />

            <ImageButton
                android:id="@+id/next"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentRight="true"
                android:layout_centerVertical="true"
                android:layout_toRightOf="@+id/tv2"
                android:background="#f00"
                android:src="@drawable/ic_skip_next_black_36dp" />

        </RelativeLayout>

    </RelativeLayout>
</RelativeLayout>

**Comment by tokudu** [comment]
This is by design, once the top of the list view is reached, it will start scrolling down.
