### ISSUE TITLE
Making second child of SlidingUpPanelLayout invisible breaks touch handling.

### ISSUE THREAD

**Issue by Lingviston** [umano/AndroidSlidingUpPanel#551]
I have SlidingUpPanel with dragView attribute set. On touching the first child I hide the second one, on the second touch I show it again. After hiding-showing second child dragView doesn't response to touch event anymore i.e. I can't drag it or tap to expand the slidingUpPanel.

I've just updated my dependency from the very old module where was no such issue.

**Comment by Lingviston** [comment]
Looks like the reason is in these lines:
    if (mSlideableView.getVisibility() != VISIBLE) {
        mSlideState = PanelState.HIDDEN;
    }
So once mSlideableView made invisible the whole View continously marked as hidden in each onMeasure call.

**Comment by silviahisham** [comment]
+1

**Comment by Lingviston** [comment]
I dound out that I need to use setPanelState(HIDDEN) instead.

**Comment by cupadhyay** [comment]
I had the same issue.

To solve: I used extra child layout in Second [Slideable] Layout and making it invisible/visible won't be causing the issue anymore.
```
<!-- MAIN CONTENT -->
<FrameLayout
	android:layout_width="match_parent"
	android:layout_height="match_parent">
	....
        .....
</FrameLayout>

<!-- SLIDING LAYOUT -->
<FrameLayout
	android:layout_width="match_parent"
	android:layout_height="wrap_content">
	<!--Additional layout required, for fixing UI freeze/no-touch issue-->
	<FrameLayout
		android:id="@+id/sliding_content"
		android:layout_width="match_parent"
		android:layout_height="wrap_content"/>
</FrameLayout>
```

**Comment by tokudu** [comment]
This is expected. Instead you should be using setPanelState hidden.
