### ISSUE TITLE
ViewPager has RecyclerView, How to set umanoScrollableView ?

### ISSUE THREAD

**Issue by xiaolongyuan** [umano/AndroidSlidingUpPanel#553]
tk

**Comment by xiaolongyuan** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                android:layout_width="match_parent"
                android:layout_height="match_parent">

	<com.sothree.slidinguppanel.SlidingUpPanelLayout
			xmlns:sothree="http://schemas.android.com/apk/res-auto"
			android:id="@+id/sliding_layout"
			android:layout_width="match_parent"
			android:layout_height="match_parent"
			android:gravity="bottom"
			sothree:umanoPanelHeight="140dp"
			sothree:umanoFadeColor="@android:color/transparent"
			sothree:umanoShadowHeight="4dp"
			sothree:umanoParallaxOffset="100dp"
			sothree:umanoDragView="@+id/slidingTabs"
			sothree:umanoOverlay="true"
			sothree:umanoScrollableView="@+id/pager">

		
		<include
				layout="@layout/qm_fragment_city_main"
				android:layout_width="match_parent"
				android:layout_height="match_parent"/>

		
		<LinearLayout
				android:id="@+id/dragView"
				android:layout_width="match_parent"
				android:layout_height="match_parent"
				android:background="#ffffff"
				android:orientation="vertical"
				android:clickable="true"
				android:focusable="false"
				>

			<LinearLayout
					android:layout_width="match_parent"
					android:layout_height="@dimen/sliding_size"
					android:orientation="horizontal">

				<com.m.ui.widget.SlidingTabLayout
						android:id="@+id/slidingTabs"
						android:layout_width="match_parent"
						android:layout_height="@dimen/sliding_size"
						android:background="@color/white"/>

			</LinearLayout>

			<android.support.v4.view.ViewPager
					android:id="@+id/pager"
					android:layout_width="match_parent"
					android:layout_height="0dp"
					android:clipChildren="false"
					android:clipToPadding="false"
					android:layout_weight="1"
					/>

		</LinearLayout>
	</com.sothree.slidinguppanel.SlidingUpPanelLayout>

</RelativeLayout>

**Comment by xiaolongyuan** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:app="http://schemas.android.com/apk/res-auto"
                android:layout_width="match_parent"
                android:layout_height="match_parent">

		<in.srain.cube.views.ptr.PtrClassicFrameLayout
			android:id="@+id/srl_refresh"
			android:layout_width="match_parent"
			android:layout_height="match_parent"
			android:background="#f1f1f1"
			app:ptr_duration_to_close="200"
			app:ptr_duration_to_close_header="1000"
			app:ptr_keep_header_when_refresh="true"
			app:ptr_pull_to_fresh="false"
			app:ptr_ratio_of_header_height_to_refresh="1.2"
			app:ptr_resistance="1.7">

		<com.m.ui.widget.FixedRecyclerView
				android:id="@+id/recycleView"
				android:listDivider="@color/red"
				android:layout_width="match_parent"
				android:layout_height="match_parent"/>
		
	</in.srain.cube.views.ptr.PtrClassicFrameLayout>

	<com.qumei.ifitting.ui.widget.EmptyLayout
			android:id="@+id/error_layout"
			android:layout_width="match_parent"
			android:layout_height="match_parent"
			android:visibility="gone"/>

</RelativeLayout>

**Comment by vsahu1986** [comment]
Hi @xiaolongyuan  Please clone the AndroidSlidingUpPanel
and switch to branch viewpager-demo

**Comment by xiaolongyuan** [comment]
@vsahu1986 
Tk,fix it.
https://github.com/xiaolongyuan/AndroidSlidingUpPanel/tree/viewpager-recyclerview-demo

**Comment by QianHong** [comment]
> @vsahu1986
> Tk,fix it.
> https://github.com/xiaolongyuan/AndroidSlidingUpPanel/tree/viewpager-recyclerview-demo

i have the same problem,but the url is 404 not found .
