### ISSUE TITLE
Hide the slidinguppanel

### ISSUE THREAD

**Issue by Rajeshn576** [umano/AndroidSlidingUpPanel#561]
Is it possible to hide or close the slidinguppanel on ACTIONDOWN or dragingdown the anchorview?

**Comment by devslava** [comment]
I need this feature too.
It is very intuitive. Why if there is way to swipe up to expand, there is no way to hide the panel by swiping down?

**Comment by Rajeshn576** [comment]
I solved it by setting by writing computePanelTopPosition(0.0f);

**Comment by devslava** [comment]
Can you describe what have you changed at the code, please? There is a lot of if statements here
