### ISSUE TITLE
Panel stuck in DRAGGING state when Hidding & Expanding the panel programmatically

### ISSUE THREAD

**Issue by Shusshu** [umano/AndroidSlidingUpPanel#562]
The panel get stuck in DRAGGING state after multiple calls to hidding & expanding in a very quick succession

**Comment by charlesdurham** [comment]
Having the same issue

**Comment by PhilippLgh** [comment]
had the same issue while using setPanelHeight() after changing the visibility of one item in the surrounding main view ( causing a resize of the panel).
had the same issue while showing/hiding the keyboard and setting panel height ~simultaneously.

potential source for the problem could be smoothSlideTo() -> onViewDragStateChanged(). The onViewDragStateChanged() method calculates a new state based on mSlideOffset. I was able to reach all kinds of wrong states from ANCHORED to HIDDEN based on invalid offsets. I'm not sure if this is a direct issue in the sliding panel though.

what worked for me was to wait for all UI events to finish before manipulating the panel dimensions. In case of very quick hiding&expanding you probably just want to throttle/defer these events.

**Comment by tokudu** [comment]
I think this should be fixed in master. Will be released in 3.3. Let me know if you still see the issue.
