### ISSUE TITLE
DrawerLayout + Slider

### ISSUE THREAD

**Issue by MohamadAtieh** [umano/AndroidSlidingUpPanel#568]
Hey, thanks for the amazing work. I have a drawer layout already as my root view of my activity. Will changing the root view to the library's and to `include` the drawer layout (+ sliding drawer) as my main content work?

**Comment by ml653** [comment]
So did it work?

**Comment by MohamadAtieh** [comment]
@ml653 Yes.

https://github.com/Redgram/redgram-for-reddit/blob/master/Redgram/app/src/main/res/layout/activity_main.xml

SlidingUpPanel -> DrawerLayout -> CoordinatorLayout
