### ISSUE TITLE
Screen Rotation

### ISSUE THREAD

**Issue by MatthewTrout** [umano/AndroidSlidingUpPanel#575]
Can't see anything referenced / issues raised regarding rotation so I'll post one here.
Having unpredictable behaviour re rotating.  Just doesn't appear to be calculating it's height properly, and leaves a blank coloured 'shadow' in place, until you collapse / close it and reopen it.  May well just be my particular layout as opposed to anything problematic in the sliding layout,  but just wanted to check what general experience was regarding rotation?

**Comment by tokudu** [comment]
Can you provide a sample project? Rotation works fine in the sample.

**Comment by tokudu** [comment]
Please reopen if still having issues.
