### ISSUE TITLE
Views in sliding panel canoot be accesed on android 6.0

### ISSUE THREAD

**Issue by marinica94** [umano/AndroidSlidingUpPanel#576]
I am having some problems changing some views in Sliding up Panel, I have a button that represents play/pause of a music and when the slide is down and I access the main view button the button inside slide out isn't changing. Also I have a textview that need to update the current time where song is playing, this isn't updating too. All this features work in lollipop and previous.

**Comment by tokudu** [comment]
Please create a sample problem if you are still having issues. This doesn't seem related to the library.
