### ISSUE TITLE
The project don't build in Android Studio 1.4.1

### ISSUE THREAD

**Issue by flamoedo** [umano/AndroidSlidingUpPanel#579]
The project don't build in Android Studio 1.4.1

**Comment by tokudu** [comment]
what error are you getting?

**Comment by flamoedo** [comment]
Hí tokudu!

Please find the error below:


Error:(22, 0) Gradle DSL method not found: 'android()'
Possible causes:The project 'AndroidSlidingUpPanel-master' may be using a version of Gradle that does not contain the method.
Open Gradle wrapper file The build file may be missing a Gradle plugin.
Apply Gradle plugin

![image](https://cloud.githubusercontent.com/assets/4040913/11024350/1fe68038-8674-11e5-8b84-b3306eaa8c6b.png)


Best Regards,

Flávio Amoedo

**Comment by tokudu** [comment]
I just updated to the latest Android Studio and everything is working fine. Please update and let me know if you are still having issues.
