### ISSUE TITLE
Panel Dragging on Click

### ISSUE THREAD

**Issue by kshitijcode** [umano/AndroidSlidingUpPanel#581]
I wish to disable panel expand on clicking. The Panel should expand only when drag event is done.
How to fix this ?

**Comment by diabloo** [comment]
dragview.setClickable(false); 
this works for me , i don't know if it's the best solution

**Comment by kshitijcode** [comment]
Sorry, this would disable the entire panel , even the drag option. 

I would love to hear a solution for this.

**Comment by diabloo** [comment]
yes my bad you just have to put a listner on the dragview
like this, it works for me    
```java
            @Override
            public void onPanelCollapsed(View view) {
                dragview.setOnClickListener(null); }
```

**Comment by tokudu** [comment]
What @diabloo said. Just set the onClickListener to null.
