### ISSUE TITLE
Collapsed view doesn't expand on click when app starts

### ISSUE THREAD

**Issue by FrancoSabadini** [umano/AndroidSlidingUpPanel#596]
The collapsed view doesn't expand on click when the app starts for the first time (after being killed). However the slide up gesture works fine. Once the view is expanded for the first time (using the slide up gesture) then the click gesture works fine to expand/collapse the views.

**Library version:** 3.2.0 (issue was also present on 2.4.0)

**Comment by adrianhrMD** [comment]
Are you sure you don't have something stealing the click event. For instance I had a problem with a scroll view stealing the click and scrolling an inner view of the slide up panel instead of expanding it.

**Comment by tokudu** [comment]
+1, please provide a simple sample project if you believe it's an issue. It works fine in the sample app.
