### ISSUE TITLE
Can't scroll inner listview when setenabled(false)

### ISSUE THREAD

**Issue by ncapdevi** [umano/AndroidSlidingUpPanel#600]
When there is an inner ListView, it is no longer scrollable if the SlidingUpPanelLayout.setEnabled(false) is called

**Comment by tokudu** [comment]
Thx, that seems like a bug. Will fix for next release

**Comment by robertoestivill** [comment]
This is also happening when using `setTouchEnabled(false)`

**Comment by tokudu** [comment]
Actually, I thought about it more. Can't you just use `setTouchEnabled`?

**Comment by tokudu** [comment]
Fixed in https://github.com/umano/AndroidSlidingUpPanel/commit/966fee4f049c43c1fded6371d1501d761f043395. Will be released in 3.3
