### ISSUE TITLE
setVisibility() on parent locks state in DRAGGING

### ISSUE THREAD

**Issue by charlesdurham** [umano/AndroidSlidingUpPanel#612]
Steps to repo:

1. `setPanelState(EXPANDED)`
2. `setPanelState(HIDDEN) `
3. set the parent's visibility to `GONE` (key here is that the visibility changes while the panel is dragging)
4. set the parent's visibility to `VISIBLE`
5. The panel will no longer respond to calls to `setPanelState()` since it is stuck in a `DRAGGING` state

**Comment by tokudu** [comment]
Should be fixed in master. Will be released in 3.3. Let me know if you still see the issue.
