### ISSUE TITLE
Main content has viewpager with Recyclerview inside 

### ISSUE THREAD

**Issue by h4h13** [umano/AndroidSlidingUpPanel#613]
Hi Thanks for help, I Have Recyclerview inside viewpager main content, my problem is the last items is not is covering with panel how to scroll above that

**Comment by adrianhrMD** [comment]
I had the same problem. If you add 
`sothree:umanoOverlay="false"`
to your `<com.sothree.slidinguppanel.SlidingUpPanelLayout>` element it will make the recycler view scrollable
