### ISSUE TITLE
How to slide the panel directly at the position I want? Not  use smoothSlideTo method.

### ISSUE THREAD

**Issue by CTancy** [umano/AndroidSlidingUpPanel#614]
Hey,I use SlidingUpPanel in my project. It's really a great work!
In my project , I use a viewpager.  There are serveral SlideupPanels in my pages. My problem is when I slide up  the panel in current page. How can I make the  other panels  in other pages slide follow the current panel? 
My idea is fetch the slide event and make other panels slide  by the smoothSlideTo(float slideOffset, int velocity) method. But  the panels will have some delays. They  will slower than the current panel.
Are there  any good devices? Thanks a lot!

**Comment by tokudu** [comment]
Set an anchor point and then use setPanelState to ANCHORED.
