### ISSUE TITLE
When expanded can not drag to the bottom - panel returning to the top.

### ISSUE THREAD

**Issue by skir** [umano/AndroidSlidingUpPanel#615]
When panel expanded, I can't drag it to the bottom - panel stops and then returns back to the top, when I remove my finger. This occurs when I touch it at the top half. If I start dragging with touching it at the bottom half, then it will stop at the half way and then it will fall to the bottom. How can I make it draggable without such "sticking" to the top?

**Comment by tokudu** [comment]
This is working as intended, if you fling, the panel will not stick to the top. it's a much more natural interaction. What your desire is not supported.
