### ISSUE TITLE
SlidingUpPanelLayout_umanoScrollInterpolator missing

### ISSUE THREAD

**Issue by Murphybro2** [umano/AndroidSlidingUpPanel#618]
When I download the zip and try to compile the SlidingPanelLayout class, it is missing R.styleable.SlidingUpPanelLayout_umanoScrollInterpolator in the constructor. How can I get this?

**Comment by tokudu** [comment]
I will release the library version 3.3 soon, which will include it. If you want it now, just pull from master.
