### ISSUE TITLE
Alternative Layout When SlideUpPanel is Expanded

### ISSUE THREAD

**Issue by mrdrewbeats** [umano/AndroidSlidingUpPanel#620]
Hello, is it possible to provide an alternative layout when the slideup panel is fully expanded or when it is anchored?using soundcloud's app as an example, when you touch on the slide up panel the layout changes(perhaps redrawn?) completely. thanks

**Comment by tokudu** [comment]
Sure. You can use the on slide listener and update the layout on your own.

**Comment by mrdrewbeats** [comment]
Yeah thaks, it worked great, i figured i had to  replace the layout when the panel state litener is changed
