### ISSUE TITLE
Images Click on Sliding Panel not working

### ISSUE THREAD

**Issue by shiprasinghal1** [umano/AndroidSlidingUpPanel#622]
I have to double click the images , exist in Sliding Panel to open it . I don't know why but this is Happening .

**Comment by tokudu** [comment]
Make sure to set the drag view using setDragView to a different view inside of the sliding panel.

**Comment by shiprasinghal1** [comment]
Hey , I don't think it's an drag issue .Thing is ,  I have a sliding panel layout consist of some text views and imageviews . Now , i have set an click event on image views . But I don't know why , clicking an image two times call the onclick event . This is an issue .

**Comment by shiprasinghal1** [comment]
Hey , I don't think it's an drag issue .dragging panel is different in a layout . Thing is , I have a sliding panel layout consist of some text views and imageviews . Now , i have set an click event on image views . But I don't know why , clicking an image two times call the onclick event . This is an issue .
