### ISSUE TITLE
"Height must have an exact value or MATCH_PARENT" exeption in android 6 only

### ISSUE THREAD

**Issue by faraz20** [umano/AndroidSlidingUpPanel#623]
Hi
I'm using this library in my project and it works fine in all android version from 4.1 to 5.1, but in android 6, when i set the layout_height of slidingUpPanel to a exact dimention like '160dp', it throw an exeption and say 'Height must have an exact value or MATCH_PARENT' , and when i set the height to match_parent it was okay.

this is my layout : 

<RelativeLayout
        android:id="@+id/content"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <RelativeLayout
            android:id="@+id/scoreContainer"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentTop="true"
            android:background="@drawable/purple_shadow_background">

            <LinearLayout
                android:id="@+id/matchActivity_timer_progress_guess"
                android:layout_width="match_parent"
                android:layout_height="2dp"
                android:background="@color/app_green1"
                android:orientation="horizontal" />

            <RelativeLayout
                android:id="@+id/activity_userInfoContainer"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentLeft="true"
                android:layout_centerVertical="true"
                android:layout_marginBottom="@dimen/global_large_margin"
                android:layout_marginLeft="@dimen/global_small_margin">

                <ir.idek.drawandplay.ui.customui.PicHolder
                    android:id="@+id/activity_userPic"
                    android:layout_width="@dimen/match_userProfile_size"
                    android:layout_height="@dimen/match_userProfile_size"
                    android:layout_centerVertical="true" />

                <LinearLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerVertical="true"
                    android:layout_marginLeft="@dimen/global_small_margin"
                    android:layout_toRightOf="@+id/activity_userPic"
                    android:orientation="vertical">

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:ellipsize="end"
                        android:singleLine="true"
                        android:textColor="@color/app_white"
                        android:textSize="@dimen/global_small_txtSize" />

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:ellipsize="end"
                        android:singleLine="true"
                        android:textColor="@color/app_white_light"
                        android:textSize="9dp" />

                </LinearLayout>
            </RelativeLayout>

            <RelativeLayout
                android:id="@+id/activity_enemyInfoContainer"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentRight="true"
                android:layout_centerVertical="true"
                android:layout_marginBottom="@dimen/user_info_container_margin"
                android:layout_marginRight="@dimen/global_small_margin">

                <LinearLayout
                    android:id="@+id/activity_enemyNameInfo"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerVertical="true"
                    android:layout_marginRight="@dimen/global_small_margin"
                    android:gravity="right"
                    android:orientation="vertical">

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:ellipsize="end"
                        android:singleLine="true"
                        android:textColor="@color/app_white"
                        android:textSize="@dimen/global_small_txtSize" />

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:ellipsize="end"
                        android:singleLine="true"
                        android:textColor="@color/app_white_light"
                        android:textSize="9dp" />
                </LinearLayout>

                <ir.idek.drawandplay.ui.customui.PicHolder
                    android:id="@+id/activity_enemyPic"
                    android:layout_width="@dimen/match_userProfile_size"
                    android:layout_height="@dimen/match_userProfile_size"
                    android:layout_centerVertical="true"
                    android:layout_toRightOf="@+id/activity_enemyNameInfo" />

            </RelativeLayout>

            <ir.idek.drawandplay.ui.customui.Timer
                android:id="@+id/matchActivity_timer"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerInParent="true"
                android:paddingTop="10dp" />

        </RelativeLayout>

        
        <ir.idek.drawandplay.ui.customui.GuessView
            android:id="@+id/guess_view"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            android:layout_below="@+id/scoreContainer"
            android:background="@android:color/white" />

        
        <com.sothree.slidinguppanel.SlidingUpPanelLayout
            android:id="@+id/guessWordSlider"
            android:layout_width="match_parent"
            android:layout_height="162dp"
            android:gravity="bottom"
            sothree:dragView="@+id/dragView">

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

            
            <LinearLayout
                android:id="@+id/bottomBar"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@drawable/match_footer_panel"
                android:gravity="center"
                android:orientation="vertical" />

        </com.sothree.slidinguppanel.SlidingUpPanelLayout>

    </RelativeLayout>

**Comment by pamartineza** [comment]
I getting the same problem, ¿did you find any solution?

**Comment by faraz20** [comment]
I put the slidingPanel in a layout and set size to the layout, like this : 

<RelativeLayout
            android:id="@+id/bottomBar_drawing_container"
            android:layout_width="match_parent"
            android:layout_height="@dimen/drawOptionSliderSize"
            android:layout_alignParentBottom="true"
            android:gravity="bottom">

            
            <com.sothree.slidinguppanel.SlidingUpPanelLayout
                android:id="@+id/drawingOptionSlider"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:clickable="false"
                android:focusable="false"
                android:gravity="bottom"
                sothree:dragView="@+id/shadowLayoutAbove"
                sothree:panelHeight="@dimen/drawOptionPanelSize">


            </com.sothree.slidinguppanel.SlidingUpPanelLayout>

</RelativeLayout>

**Comment by tokudu** [comment]
I can't seem to repro this issue in the latest android studio.

**Comment by BrianOn99** [comment]
I have reproduced this issue in android studio.  An app I am participating in is using AndroidSlidingUpPanel.  Some of our user report the app crashes, and the logcat is

>  java.lang.IllegalStateException: Height must have an exact value or MATCH_PARENT
>         at com.sothree.slidinguppanel.SlidingUpPanelLayout.onMeasure(SlidingUpPanelLayout.java:721)
>          at android.view.View.measure(View.java:19719)

which is reported from *Nexus 6 Android 6.0.1*.
At first, I also cannot reproduce in android studio, but when I run it on Android N (available for download in AVD, x86 Image tab), the bug occurs.

**Comment by BrianOn99** [comment]
Here is how to reproduce it by modifying the demo accompanied in this github repo:
change the demo/src/main/res/layout/activity_demo.xml to following:
``` xml
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:sothree="http://schemas.android.com/apk/res-auto"
    android:id="@+id/scoreContainer"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_alignParentTop="true">

<com.sothree.slidinguppanel.SlidingUpPanelLayout
    android:id="@+id/sliding_layout"
    android:layout_width="match_parent"
    android:layout_height="300dp"
    android:gravity="bottom"
    sothree:umanoPanelHeight="68dp"
    sothree:umanoShadowHeight="4dp"
    sothree:umanoParallaxOffset="100dp"
    sothree:umanoDragView="@+id/dragView"
    sothree:umanoOverlay="true"
    sothree:umanoScrollableView="@+id/list">

    <!-- MAIN CONTENT -->
    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">
        <android.support.v7.widget.Toolbar
            xmlns:sothree="http://schemas.android.com/apk/res-auto"
            xmlns:android="http://schemas.android.com/apk/res/android"
            android:id="@+id/main_toolbar"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            sothree:theme="@style/ActionBar"
            android:layout_width="match_parent"/>
        <TextView
            android:id="@+id/main"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginTop="?attr/actionBarSize"
            android:gravity="center"
            android:text="Main Content"
            android:clickable="true"
            android:focusable="false"
            android:focusableInTouchMode="true"
            android:textSize="16sp" />
    </FrameLayout>

    <!-- SLIDING LAYOUT -->
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#ffffff"
        android:orientation="vertical"
        android:clickable="true"
        android:focusable="false"
        android:id="@+id/dragView">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="68dp"
            android:orientation="horizontal">

            <TextView
                android:id="@+id/name"
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:textSize="14sp"
                android:gravity="center_vertical"
                android:paddingLeft="10dp"/>

            <Button
                android:id="@+id/follow"
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:textSize="14sp"
                android:gravity="center_vertical|right"
                android:paddingRight="10dp"
                android:paddingLeft="10dp"/>

        </LinearLayout>

        <ListView
            android:id="@+id/list"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1">
        </ListView>

        <!--<ScrollView-->
            <!--android:id="@+id/sv"-->
            <!--android:layout_width="match_parent"-->
            <!--android:layout_height="0dp"-->
            <!--android:layout_weight="1"-->
            <!-->-->
            <!--<TextView-->
                <!--android:layout_width="match_parent"-->
                <!--android:layout_height="wrap_content"-->
                <!--android:text="The standard Lorem Ipsum passage, used since the 1500Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Section 1.10.32 of  written by Cicero in 45 t perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?1914 translation by H. RackhamBut I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete accouof the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."/>-->
        <!--</ScrollView>-->
    </LinearLayout>
</com.sothree.slidinguppanel.SlidingUpPanelLayout>
</RelativeLayout>
```
Then the app will crash, only with android N image

**Comment by BrianOn99** [comment]
It turns out, a view with "dp" nested in another view, android N with say the MeasureSpec is AT_MOST (instead of EXACTLY)
I will make a pull request

**Comment by tokudu** [comment]
Awesome. Thanks! I will have a look and merge.

Anton

**Comment by ashishjohn1908** [comment]
"Height must have an exact value or MATCH_PARENT" 
This error can also occur if you are using SlidingPanel inside scrollview
