### ISSUE TITLE
How to set Z index for panel 

### ISSUE THREAD

**Issue by ajit-sharma** [umano/AndroidSlidingUpPanel#626]
I am working with navigation bar and sliding panel in same activity. problem is when navigation bar is open my sliding panel is on top of that, i want to show sliding panel below to navigation bar. 
I could not find any kind of property to set same. please help.

**Comment by tokudu** [comment]
Simply place the sliding layout as the first child in your main layout and the navigation toolbar as the second.

**Comment by icangku** [comment]
can u give me the example?
