### ISSUE TITLE
The ListView bottom cannot scroll

### ISSUE THREAD

**Issue by zhupengGitHub** [umano/AndroidSlidingUpPanel#640]
mLayout.setAnchorPoint(0.5f);
mLayout.setOverlayed(true);
mLayout.setParallaxOffset(0);

when I set anchor to 0.5,The bottom list in panel cannot scroll

**Comment by tokudu** [comment]
Are you setting a scrollableView?

**Comment by tokudu** [comment]
Reopen if still having issues.
