### ISSUE TITLE
Disable expand to full

### ISSUE THREAD

**Issue by BrunoVT1992** [umano/AndroidSlidingUpPanel#641]
Hi,

I want to be able to slide to my anchor point but not passed that point is some situations when the remaining of my data is not loaded. How can I accomplish this?

**Comment by tokudu** [comment]
set the layout_weight of the sliding panel to the desired percentage instead of using an anchor point.

**Comment by septemberboy7** [comment]
I can't add layout_weight to Sliding Layout (LinearLayout with id "drag_vew") in the demo app. Can you show me an example code please?
