### ISSUE TITLE
Setting the sliding up view to transparent. 

### ISSUE THREAD

**Issue by EugeneHoran** [umano/AndroidSlidingUpPanel#644]
How would I go about making the sliding up view transparent?

**Comment by hendraanggrian** [comment]
I am also very interested in this, the panel child view's backgroundColor seems to match the backgroundColor of SlidingUpPaneLayout.

**Comment by null-dev** [comment]
Try reading the README.md...
![selection_031](https://cloud.githubusercontent.com/assets/9571936/12699951/77a6f04a-c79d-11e5-82f9-eefeabf02975.jpg)

**Comment by hendraanggrian** [comment]
@null-dev well that certainly was my fault for not reading the documentation carefully. Thank you for pointing that out, it works well now.
