### ISSUE TITLE
Request: add scrolling listener

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [umano/AndroidSlidingUpPanel#646]
So that we could perform extra transitions/animations as the user moves the bottom sheet.
Example here:
https://github.com/AndroidDeveloperLB/ThreePhasesBottomSheet

**Comment by charlesdurham** [comment]
Are you looking for `PanelSlideListener`? 

https://github.com/umano/AndroidSlidingUpPanel/blob/master/library/src/com/sothree/slidinguppanel/SlidingUpPanelLayout.java#L227

**Comment by AndroidDeveloperLB** [comment]
hmmmm... I think so... 
So I guess it is possible to do the same as I did? With AppBarLayout,CoordinatorLayout , etc ... ?
Can I also set the size of the peeked bottom sheet (when it's at the bottom) ? Even have wrap content height?
Can the bottom sheet content be in a fragment? 
And how does the library handle orientation changes and keyboard?

**Comment by tokudu** [comment]
Yeah you can do all of those things. Please read the readme file.

**Comment by AndroidDeveloperLB** [comment]
@tokudu Nice . Thank you for your time and effort.
