### ISSUE TITLE
panel height is larger than the available height

### ISSUE THREAD

**Issue by BrunoVT1992** [umano/AndroidSlidingUpPanel#650]
Hi,

I have in my panel a linearlayout witch is approximately 1500px high, I need to be able to scroll all the way to the bottom but the panel stops at the available height on the screen (1100px). How can I make the panel scroll higher?

**Comment by alexwhb** [comment]
@BrunoVT1992 I had the same issue, then I read though the docs carefully: `By default, the panel pushes up the main content. You can make it overlay the main content by using setOverlayed method or umanoOverlay attribute. This is useful if you would like to make the sliding layout semi-transparent. You can also set umanoClipPanel to false to make the panel transparent in non-overlay mode.`

so just for clarification  in your your layout file inside of `<com.sothree.slidinguppanel.SlidingUpPanelLayout` you set `sothree:umanoOverlay="false"` should solve your problem.
