### ISSUE TITLE
How to stop sliding to exactly position which is dragging stopped?

### ISSUE THREAD

**Issue by JosephLuns** [umano/AndroidSlidingUpPanel#651]
Hello,

I am going to stop sliding up/down to exactly position which is dragging stopped.
Seems its automatically moving to 3 positions which is top (EXPANDED)/bottom (COLLAPSED)/anchor.

Is that possible with this library?
Else do u know the alternative way to archive it?

Thanks
Joseph

**Comment by tokudu** [comment]
Unfortunately, no. Only specific 3 states are supported.

**Comment by maximPetlyuk** [comment]
If you want such behavior, you need to override DragHelperCallback - comment the next code in the function "onViewReleased":

mDragHelper.settleCapturedViewAt(releasedChild.getLeft(), top);

**Comment by taimoor99** [comment]
you found any solution for this?
