### ISSUE TITLE
setTouchEnabled not working?

### ISSUE THREAD

**Issue by iampawan** [umano/AndroidSlidingUpPanel#652]

**Comment by sergiomarquesmoura** [comment]
any answer on this? setTouchEnabled(false) is not working for me, since I can still drag the panel

**Comment by tokudu** [comment]
Use setEnabled

**Comment by sergiomarquesmoura** [comment]
Thanks for the answer @tokudu. What I would really want was to not being able to drag but still be able to click on the views inside the panel. However, setEnable(false) also prevents me from clicking on those views. Any solution on this ?

**Comment by tokudu** [comment]
How about setTouchEnabled?

**Comment by iampawan** [comment]
@sergiomarquesmoura my question is also same. @tokudu please help on this.

**Comment by sergiomarquesmoura** [comment]
@tokudu right now I am using setTouchEnabled. I've tried both

**Comment by tokudu** [comment]
I look to see if setTouchEnable is buggy

**Comment by tokudu** [comment]
Fixed in https://github.com/umano/AndroidSlidingUpPanel/commit/966fee4f049c43c1fded6371d1501d761f043395. Will be released in 3.3
