### ISSUE TITLE
Prevent swiping but still enable clicking to expand/collapse

### ISSUE THREAD

**Issue by apkelly** [umano/AndroidSlidingUpPanel#654]
Hi,

Is there a way to turn off the swiping gesture to expand/collapse the sliding panel? 

Also, is there an easy way I can capture clicking outside of the sliding panel, e.g. to collapse it again when the user clicks on the exposed main content behind?

Thanks.

**Comment by tokudu** [comment]
Both features are available in the master. Use setTouchEnabled(false) for the former. The latter will be released in 3.3.
