### ISSUE TITLE
Panel stuck in dragging state

### ISSUE THREAD

**Issue by Wahyd** [umano/AndroidSlidingUpPanel#662]
Hi everyone,

With the last version (3.2.1) I have my dragView (which encapsulate a scrollable view) stuck in dragging state :  

Here the steps 
 - set panel state to collapsed
 - drag manually to setpanelstate to expanded
 - drag a little bit (from to the top of the screen) to stuck in dragging state to debug, when i set a panelslidelistener, we see slideOffset stuck to 0.7 or 0.8 or 0.9.

The slidinguppanel does not respond to setPanelState method after that
Thks in advance,

**Comment by tokudu** [comment]
Should be fixed in master. Will be released in 3.3. Let me know if you still see the issue.
