### ISSUE TITLE
Nested panels

### ISSUE THREAD

**Issue by devX95** [umano/AndroidSlidingUpPanel#667]
I'd like to have a sliding panel inside a panel, like phonographs now playing screen, I can get the two panels, however the second panel doesn't intercept drag events. Clicking on the panel opens it but the recyclerview inside isn't scrollable, the first panel works perfectly.

**Comment by tokudu** [comment]
you probably need to set on panel as the scrollable view of the other panel and create a custom scrollable view helper

**Comment by devX95** [comment]
@tokudu Thanks, im kind of a newbie, could i get an example?

**Comment by jaytj95** [comment]
I'm in the same boat...

**Comment by niteshvuliv** [comment]
Can someone please help me with this situation? I am stuck in the same situation.
