### ISSUE TITLE
SlidingPanel stops touch events from getting passed to the container view 

### ISSUE THREAD

**Issue by lappalj4** [umano/AndroidSlidingUpPanel#673]
Hi!
I would like to have a sliding panel inside a swipeable card. The idea is the user can tap the card to slide up more information about it, or swipe it away. 

The problem is when I use the sliding panel, it consumes all of the touch events and so the swipe is not being registered in the parent view. I don't need the SlidingPanel itself to respond to any touch events, I can handle opening/closing it programmatically.

So how can I have my swipeable card receive all touch events while having the sliding panel inside it?

**Comment by charlesdurham** [comment]
You can disable touch events for the sliding panel.

`slidingUpPanelLayout.setTouchEnabled(false)`
