### ISSUE TITLE
Is this possible? 

### ISSUE THREAD

**Issue by paulcanning** [umano/AndroidSlidingUpPanel#676]
Wasn't sure where else to ask, but I need to know a few things. 

With this sliding panel, can I set an initial "preview" where the user can open the panel and it just shows say a heading and maybe a small icon. Then, the user can drag the panel up and make it full screen to show say, a large image or large body of text, under the heading? 

A two stage slide?

**Comment by tokudu** [comment]
Yes, you can use an anchor point for having a two stage slide.
