### ISSUE TITLE
Crash :  IllegalStateException

### ISSUE THREAD

**Issue by dev01-adroitinfosol** [umano/AndroidSlidingUpPanel#678]
java.lang.IllegalStateException
android.widget.ListView.layoutChildren(ListView.java:1582)
android.widget.AbsListView.onLayout(AbsListView.java:2644)
android.view.View.layout(View.java:16942)
android.view.ViewGroup.layout(ViewGroup.java:5409)
android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
android.view.View.layout(View.java:16942)
android.view.ViewGroup.layout(ViewGroup.java:5409)
**# com.sothree.slidinguppanel.SlidingUpPanelLayout.onLayout(SlidingUpPanelLayout.java:860)**
android.view.View.layout(View.java:16942)
android.view.ViewGroup.layout(ViewGroup.java:5409)
android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
android.view.View.layout(View.java:16942)
android.view.ViewGroup.layout(ViewGroup.java:5409)
android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
android.view.View.layout(View.java:16942)
android.view.ViewGroup.layout(ViewGroup.java:5409)
android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
android.view.View.layout(View.java:16942)
android.view.ViewGroup.layout(ViewGroup.java:5409)
android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
android.view.View.layout(View.java:16942)
android.view.ViewGroup.layout(ViewGroup.java:5409)
android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1037)
android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:747)
android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1156)
android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:760)
android.view.View.layout(View.java:16942)
android.view.ViewGroup.layout(ViewGroup.java:5409)
android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
android.view.View.layout(View.java:16942)
android.view.ViewGroup.layout(ViewGroup.java:5409)
android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
android.widget.FrameLayout.onLayout(FrameLayout.java:514)
android.view.View.layout(View.java:16942)
android.view.ViewGroup.layout(ViewGroup.java:5409)
android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
android.view.View.layout(View.java:16942)
android.view.ViewGroup.layout(ViewGroup.java:5409)
android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
android.widget.FrameLayout.onLayout(FrameLayout.java:514)
android.view.View.layout(View.java:16942)
android.view.ViewGroup.layout(ViewGroup.java:5409)
android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
android.view.View.layout(View.java:16942)
android.view.ViewGroup.layout(ViewGroup.java:5409)
android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
android.widget.FrameLayout.onLayout(FrameLayout.java:514)
android.view.View.layout(View.java:16942)
android.view.ViewGroup.layout(ViewGroup.java:5409)
android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2457)
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2160)
android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1300)
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7017)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
android.view.Choreographer.doCallbacks(Choreographer.java:590)
android.view.Choreographer.doFrame(Choreographer.java:560)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
android.os.Handler.handleCallback(Handler.java:739)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:145)
android.app.ActivityThread.main(ActivityThread.java:6897)
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke(Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by tokudu** [comment]
This exception is not related to the library. The top line is android.widget.ListView.layoutChildren(ListView.java:1582)
