### ISSUE TITLE
Snack-bar Interference with Sliding up panel

### ISSUE THREAD

**Issue by aebmgroup** [umano/AndroidSlidingUpPanel#680]
I used this code to create snackbar within sliding up panel:
```
Snackbar.make(mMainCoordinatorLayout, "Some Message" , Snackbar.LENGTH_LONG).show();
```
Sliding up panel is first view group in my layout and Coordinator layout is within sliding up panel.
Here is the result:
![snackbar1](https://cloud.githubusercontent.com/assets/8916044/13567228/525bc394-e46f-11e5-9f8c-cbc18a801a6a.png)

I also sent sliding up panel layout to snack bar , this time snackbar appeared over sliding up panel but this caused sliding up panel to flicker and be laggy!
```
Snackbar.make(mSlidingUpPanel, "Some Message" , Snackbar.LENGTH_LONG).show();
```

Am i doing something wrong or this is a bug?

**Comment by tokudu** [comment]
Do not use the snackbar against the panel. Instead wrap the panel with a FrameLayout and use the snackbar on that layout.
