### ISSUE TITLE
我想设置成 从上往下滑动的 有这个功能吗？

### ISSUE THREAD

**Issue by wushge11** [umano/AndroidSlidingUpPanel#723]
我想设置成 从上往下滑动的 有这个功能吗？

**Comment by JiajiaGuo** [comment]
有的，设置android:gravity为"top"

**Comment by SeekMyCosmic** [comment]
But it looks like some bad experience for users because of the system status bar overhead.

**Comment by tokudu** [comment]
Please reopen in english if possible.
