### ISSUE TITLE
Is it possible to make only Drag enable??

### ISSUE THREAD

**Issue by sandeeptengale** [umano/AndroidSlidingUpPanel#726]
Its given that we can disable action by applying setTouchEnable(boolean), but I want only click to get disable not drag? How to do it?

**Comment by mtyy** [comment]
id like that feature also, currently i did it by overriding the function where the clicklistener is set.

public class ControllableSlidingLayout extends SlidingUpPanelLayout {

    private boolean mClickToCollapse = true;

    public ControllableSlidingLayout(Context context) {
        super(context);
    }

    public ControllableSlidingLayout(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public ControllableSlidingLayout(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
    }

    public void setClickToCollapseEnabled(boolean enabled){
        mClickToCollapse = enabled;
    }

    @Override
    public void setDragView(View dragView) {
        super.setDragView(dragView);
        if (dragView != null) {
            dragView.setClickable(true);
            dragView.setFocusable(false);
            dragView.setFocusableInTouchMode(false);
            dragView.setOnClickListener(new OnClickListener() {
                @Override
                public void onClick(View v) {
                    if (!isEnabled() || !isTouchEnabled()) return;
                    if (getPanelState() != PanelState.EXPANDED && getPanelState() != PanelState.ANCHORED) {
                        if (getAnchorPoint() < 1.0f) {
                            setPanelState(PanelState.ANCHORED);
                        } else {
                            setPanelState(PanelState.EXPANDED);
                        }
                    } else if (mClickToCollapse){
                        setPanelState(PanelState.COLLAPSED);
                    }
                }
            });
        }
    }
}

**Comment by HoWeiHang** [comment]
@mtyy  Your solution solve my problem! But i still have some question, is there any solution to remain original clicklistener when panelState.COLLAPSE while using setDragView (your override method) when panelState.EXPANDED?

**Comment by mtyy** [comment]
I don't really understand. But you can listen for panel state changes and if you set mClickToCollapse true it will behave exactly like the original method. Or in the last boolean add getPanelState to make it true when you need to.

**Comment by HoWeiHang** [comment]
It's still no work. 
I'd like to find out a way to allow  the panel can be draggable and clickable when it is COLLAPSE,  but when it is EXPANDED, I want to disable clicking function, and still enable the dragging function, is there any solution?
