### ISSUE TITLE
Map is parallaxed

### ISSUE THREAD

**Issue by novo-dimaporo** [umano/AndroidSlidingUpPanel#734]
Hello,
I'm trying to customize the code so it wont parallax my map but I cant manage to make it work. It keeps on resizing my map after collapsing.

I recorded it here
https://drive.google.com/file/d/0B0FlmU52DWskNkhxX0tXcVZrSWM/view?usp=sharing

**Comment by novo-dimaporo** [comment]
I just figure it out. I remove some code inside <i>onPanelDragged(int newTop)</i>

**Comment by Eyadoos** [comment]
@novo-dimaporo How did you manage to solve this out?
