### ISSUE TITLE
Scrolling behaviaour at anchor point not working

### ISSUE THREAD

**Issue by salihyalcin** [umano/AndroidSlidingUpPanel#755]
Hello Guys, 
First of all thanks for great library. I use listview inside panel layout.   `slidingUpPanel.setScrollableView(listView);` code block allow me to use nested scroll functionality like a charm. 
When setting anchor point for panel with  ` slidingUpPanel.setAnchorPoint(0.5f);` scrolling functionality not working at acnhor point. 

I looked source code. Try to find solution my own. I think motion event disable this functionality. 

How can I gain this functionality. 

Thanks

**Comment by tokudu** [comment]
Please reopen with more specific information what's not working. Or provide a sample project demonstrating the issue. Thanks
