### ISSUE TITLE
Remove main layout

### ISSUE THREAD

**Issue by sayoojvalsan** [umano/AndroidSlidingUpPanel#758]
Is it possible just to use the sliding panel and not worry about the Main content ?

I am looking for something where there is just this panel which I can swipe up without having to worry about the main layout.

I am looking for a way to nest panel. For instance when first panel is expanded, I see another panel at the bottom.

Currently I am not able to do this coz of the restrictions of having only 2 layouts and also the first layout eats the touch events.

**Comment by tokudu** [comment]
You can just use a transparent view instead of the main content.
