### ISSUE TITLE
v3.3.0 is missing setPanelSlideListener

### ISSUE THREAD

**Issue by eladnava** [umano/AndroidSlidingUpPanel#764]
Hi there,
Thanks so much for this library!

Is there any chance that v3.3.0 is missing the `setPanelSlideListener` method for the `SlidingUpPanelLayout` class?

**Comment by eladnava** [comment]
In the meantime, I ended up using v3.2.1 which does have this method.

**Comment by tokudu** [comment]
use `addPanelSlideListener`
