### ISSUE TITLE
Custom width of the panel

### ISSUE THREAD

**Issue by Leonid-Kiev** [umano/AndroidSlidingUpPanel#790]
Thanks so much for the amazing library.
Is it possible to make bottom panel not match_parent, but with custom width and custom background.
I need the panel width In collapsed state to be not full screen, but rather custom width in the middle of the bottom part. Something like this: [https://drive.google.com/open?id=0BwlM_nfKeY2NWHNreFhON0ZkamM](url)
And it has to slide up with the panel when it expands. 
is it possible to implement?

**Comment by pgill** [comment]
Yes, just make the panel transparent and contain a view of your required
proportions.

Anton

**Comment by Leonid-Kiev** [comment]
Firstly thank you for a quick reply.
And secondly wow! Thanks! It solves my task perfectly with umanoOverlay="true", umanoShadowHeight="0dp" and custom background of the panel.
Then this library is just incredible. Thanks a bunch!
