### ISSUE TITLE
Can't scroll RecyclerView to bottom

### ISSUE THREAD

**Issue by tijee** [umano/AndroidSlidingUpPanel#793]
Hi, I'm facing an issue with a RecyclerView inside the sliding panel: when the panel is anchored, if I want to scroll the RecyclerView to the bottom, the scroll stops before the end. I can understand why, as the bottom of the RecyclerView is actually outside of the screen, but is there a way to fix it?

**Comment by charlesdurham** [comment]
Have you taken a look at this? https://github.com/umano/AndroidSlidingUpPanel#scrollable-sliding-views

**Comment by tijee** [comment]
Thanks, actually I'm not sure it's enough in my case because I have two RecyclerViews in my sliding panel (one visible at a time), but I think it's the solution to what I posted.
