### ISSUE TITLE
Panel to slide under the status bar when expanded.

### ISSUE THREAD

**Issue by NikithShetty** [umano/AndroidSlidingUpPanel#806]
Imagine the sliding panel has a bar that's visible when collapsed and it is also the clickable area. Now when the panel is in its expanded state, this bar needs to be hidden under the status bar, i.e., it should overshoot the top and go under the status bar to hide the bar.
Please do tell how to achieve such effect if its already present, else including such feature in future would be gladly welcomed.

**Comment by akent** [comment]
Check #270, just set a negative marginTop on the panel.
