### ISSUE TITLE
Appcompat-v7:25 conflicts with slidingpanel 3.3.1

### ISSUE THREAD

**Issue by hwin16** [umano/AndroidSlidingUpPanel#816]
I try to add slidinguppanel library to compile dependency and it is conflicted with appcompat version 25. How do I fix this? Is newer sliding panel library coming out? 

Thank you!!

**Comment by lukesleeman** [comment]
This seems to be because slidingpanel has a dependency on the 23 version of app compat Recycler view.  In my case I was able to fix it by putting to following in my gradle build file:

```
compile('com.sothree.slidinguppanel:library:3.3.1') {
        transitive = false;
}
```

**Comment by hwin16** [comment]
Thank you Luke. This solves my problem.
