### ISSUE TITLE
How to make the sliding view to stop when 50% of the parent layout?

### ISSUE THREAD

**Issue by liuzhen2008** [umano/AndroidSlidingUpPanel#845]
I tried to add a layout weight parameter in the XML but it doesn't seem to actually work?

```
<com.sothree.slidinguppanel.SlidingUpPanelLayout
    xmlns:sothree="http://schemas.android.com/apk/res-auto"
    android:id="@+id/sliding_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="bottom"
    sothree:umanoPanelHeight="68dp"
    sothree:umanoShadowHeight="4dp">

    <TextView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center"
        android:text="Main Content"
        andorid:layout_weight="1"
        android:textSize="16sp" />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center|top"
        android:text="The Awesome Sliding Up Panel"
        andorid:layout_weight="1"
        android:textSize="16sp" />
</com.sothree.slidinguppanel.SlidingUpPanelLayout>

```

**Comment by nsmith1024** [comment]
look at the demo code in main_activity.java, they have a percentage telling how far up the sliding panel should be and you have to set the anchor.

        mLayout = (SlidingUpPanelLayout) findViewById(R.id.sliding_layout);
        if (mLayout != null) {
            mLayout.setAnchorPoint(0.5f); // slide up 50% then stop
            mLayout.setPanelState(SlidingUpPanelLayout.PanelState.ANCHORED);
        }

**Comment by liuzhen2008** [comment]
Looks like you are right!
THanks

**Comment by YxmCute** [comment]
(⊙o⊙)…
when dragview locates in half,I do not want it to slip up, just to let it go falling
the slidinglayout' gravity is  android:gravity="bottom"
what should I do? @nsmith1024
