### ISSUE TITLE
Update library to Android Oreo

### ISSUE THREAD

**Issue by sidvenu** [umano/AndroidSlidingUpPanel#869]
SlidingUpPanel doesn't work on Android Oreo devices - please update it

**Comment by lucazin** [comment]
i'm trying to look something, but its hard to get work..

someone can help us?

**Comment by tokudu** [comment]
I tried the demo on an Oreo device (Pixel XL), and it works just fine. What issues are you seeing?

**Comment by sidvenu** [comment]
Sorry 'bout that, I had a slight problem with my code that was not due to the library. Transparent slide up panel was not working - turns out I did't set the overlay attribute.
