### ISSUE TITLE
Can't use the library

### ISSUE THREAD

**Issue by sakar97** [umano/AndroidSlidingUpPanel#960]
While writing the dependencies I get this Issue called Bad Gateway and sync build failed due to this Error what to do ???

Could not resolve com.sothree.slidinguppanel:library:3.4.0.
  Required by:
      project :app
   > Could not resolve com.sothree.slidinguppanel:library:3.4.0.
      > Could not get resource 'https://jcenter.bintray.com/com/sothree/slidinguppanel/library/3.4.0/library-3.4.0.pom'.
         > Could not HEAD 'https://jcenter.bintray.com/com/sothree/slidinguppanel/library/3.4.0/library-3.4.0.pom'. Received status code 502 from server: Bad Gateway

**Comment by peter-yeh** [comment]
can u provide more details on your problems?
