### ISSUE TITLE
Is there a way to remove shadow if panel is expanded?

### ISSUE THREAD

**Issue by rutherfn** [umano/AndroidSlidingUpPanel#963]
I have been trying to find a way to get rid of background shadow, when bar is expanded. Is there a way that I can do this?

**Comment by abhriyaroy** [comment]
Did you find a way?

**Comment by abhriyaroy** [comment]
Well, I figured, doing this solves the issue :
`slidingLayout.coveredFadeColor = android.R.color.transparent`

**Comment by rutherfn** [comment]
Ya I found a way, thanks!
